### ISSUE TITLE
Symbol triplication in the HTM manual, & updating hyperlinks

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#100]
On the HTM manual found at:
```
http://kappa-dev.github.io/docs/KaSim-manual-master/KaSim_manual.htm
```
* Most of the symbols got triplicated throughout the file. Unless the syntax has been expanded for such chaining of rules, it now reads for example:
```
'assumed binary AB'  A(x),B(y)→…→…→… @ γ2γ2γ2
```
* The link to KappaLanguage.org in the title points to a non-existent page:
```
http://kappa-dev.github.io/docs/KaSim-manual-master/KappaLanguage.org
```
* Suggestion: have KaSim's readme.md point to the HTM manual, instead of the page of releases.

**Comment by feret** [comment]
-> I do have the tripification of the symbols. Is it comming from the browsers ? 
Which OS and which webbrowser are you using ? 

 -> I have updated the the link in the KaSim/man 
I have tried to use dev/update-web.sh to push the new version, but it has failed:

[master 7680c54] Sync website with Kappa-Dev/KaSim@00a918a7863f50833be9bb5cb57c66872400eca6 bugfix: size of the logo on the htm version.
 9 files changed, 194 insertions(+), 143 deletions(-)
 rewrite docs/KaSim-manual-master/generated_img/abc_contact.png (99%)
 rewrite docs/KaSim-manual-master/generated_img/abc_influence.png (98%)
 rewrite docs/KaSim-manual-master/generated_img/cflow.png (99%)
 rewrite docs/KaSim-manual-master/generated_img/flux.png (99%)
 rewrite docs/KaSim-manual-master/generated_img/plot-abc.png (99%)
 rewrite docs/KaSim-manual-master/generated_img/plot-abc2.png (99%)
 rewrite docs/KaSim-manual-master/generated_img/poly.png (98%)
remote: Anonymous access to Kappa-Dev/Kappa-Dev.github.io.git denied.
fatal: Authentication failed for 'https://:@github.com/Kappa-Dev/Kappa-Dev.github.io.git/'
No Changes

**Comment by hmedina** [comment]
The triplication seems to be a browser / OS issue. Firefox on Windows shows triplication; Firefox on Android doesn't; Chrome on Windows doesn't.
I've sent Mozilla some feedback on this, don't know if/when they might check on it though.

**Comment by pirbo** [comment]
I hijack this thread by raising an purely technical point: 
Am I allowed to provide a static -seed in the man/scripts/*.sh so that the generated images don't change when the documentation don't change ?
I ask because else the generated_img/*.png change at each commit in KaSim and the kappa-dev.github.io git repository will soon become gigantic ...

**Comment by feret** [comment]
@Pierre: You are not allowed. You HAVE to do it !!!
All the more so since, we expect the manual to change as less as possible.

**Comment by feret** [comment]
@Hector, I have noticed some triplification in a transient phase. just after the browser has opened the html file, MathMl expressions are not interpreted properly from the beggining, it takes time to proceed. 
Maybe in your case, this interpretation has stalled, or has been interrumpted by a bug in the browser.

**Comment by hector** [comment]
@feret I think you may be writing to another "hector"

**Comment by pirbo** [comment]
There is something mysterious.
At 35d41a7b17257c91c0247e312285535d7df06531 (after last changes of @feret) all symbols have been escaped in html (which is very good !).
 But after mine, (at 7706bdf3c11895b41b9c4be29a0bf4da97d9f4a5) travis pushes back a version with dangerous symbols. I don't see any reason for that. Do you ?

**Comment by feret** [comment]
Firstly, it is not fun to laugh at me because github has decided to send email to people I do not know. 
Secondly, no sorry, I do not know what has cause the conversion of math symbols to html ASCII symbols. You have to understand that I am not clever enough to have it done on purpose..

**Comment by vd1** [comment]
Dear all

I was trying to compile the latest kasim and got this:

celodv:KaSim V$ make bin/KaSim

ocamlbuild -use-ocamlfind -I KaSa_rep/lib/light KaSim.native

+ ocamlfind ocamlopt -c -bin-annot -package str -package unix -I main -I
siteGraphs -I simulation -I pattern -I KaSa_rep -I grammar -I Error -I
dataStructures -I cflow -I KaSa_rep/tools -I KaSa_rep/sanity_test -I
KaSa_rep/reachability_analysis -I KaSa_rep/pipeline -I KaSa_rep/main -I
KaSa_rep/lib -I KaSa_rep/influence_map -I KaSa_rep/export_to_KaSim -I
KaSa_rep/error_handlers -I KaSa_rep/data_structures -I
KaSa_rep/counting_enumeration -I KaSa_rep/config -I
KaSa_rep/automatically_generated -I KaSa_rep/lib/light -I
KaSa_rep/frontend/preprocess -I KaSa_rep/data_structures/mvbdu -o
main/kappa_files.cmx main/kappa_files.ml

File "main/kappa_files.ml", line 1:

Error: Wrong file naming: KaSa_rep/main/filename.cmi

contains the compiled interface for

Filename when FileName was expected

Command exited with code 2.

Compilation unsuccessful after building 108 targets (107 cached) in
00:00:00.

make: *** [KaSim.native] Error 10


any idea what I am doing wrong?

Vincent

**Comment by feret** [comment]
Dear Vincent,

This is strange, I have just tested on both Mac OS & Ubuntu and it works properly:

git clone git@github.com:Kappa-Dev/KaSim.git
cd KaSim
make 

Best wishes. 
Jerome.

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by pirbo** [comment]
First of all, Have you tried do 
$ make clean
and then
$ make bin/KaSim
again ?

Pierre B.

**Comment by vd1** [comment]
ah-ah that worked! thanks
Vincent
