### ISSUE TITLE
bin/sanity_check

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#114]
What does sanity_check do ? Is it something a end user would use ?
It may be more relevant to put it in the "check" target of the makefile than in the "all" one, doesn't it ?
In any case, it should probably be erased by make clean ...

**Comment by feret** [comment]
Dear Pierre, 

This binary computes some tests about data structures (in particular BDDs). 
Yes it would be more relevant to put it in the check target. 

Cheers. 
Jerome.

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr
