### ISSUE TITLE
Warning when the longest prefix convention may not be respected

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#121]
A rule of the form

'r' A(),B() -> B(), A() @ 1
should generate the warnings:
"Rule 'r' induce the deletion and the creation of an agent of type A"
"Rule 'r' induce the deletion and the creation of an agent of type B"

**Comment by pirbo** [comment]
What should be the formal rule to trigger the warning ?
 - There is a permutation of the right hand size that imply less deletion/creation ?
 - There is a permutation of the right hand size that imply NO deletion/creation ?

**Comment by feret** [comment]
I would warn on both (with a distinct message). 
I would also warn if both conventions (the one that looks at the interface (currently activated) and the one that does not) do not coincide. 

Ultimately, a config file or directives should be used to toggle on/off each kind of warnings.
