### ISSUE TITLE
Does this project needs to compile under windows?

### ISSUE THREAD

**Issue by UnixJunkie** [Kappa-Dev/KaSim#122]
If not, maybe I can create an obuild script for KaSim.
I guess it will then compile faster than with ocamlbuild.

**Comment by feret** [comment]
Dear François, 
Thank you for your help, but, yes, it has to compile under Windows. 
It is meant to be broadly used by modelers.
Cheers.

**Comment by UnixJunkie** [comment]
Too bad!
