### ISSUE TITLE
KaSim fails compilation

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#123]
As of commit fed055f0c35bcb215392baa0135126ed5f7c0ae1, KaSim fails compilation with the following message:

    ...
    + ocamlfind ocamldep -package str -package unix -modules cflow/kappa_instantiation.ml > cflow/kappa_instantiation.ml.depends
    File "cflow/kappa_instantiation.ml", line 30, characters 12-13:
    Error: Syntax error: 'end' expected
    File "cflow/kappa_instantiation.ml", line 27, characters 0-3:
    Error: This 'sig' might be unmatched
    Command exited with code 2.
    Compilation unsuccessful after building 230 targets (0 cached) in 00:00:28.
    Makefile:52: recipe for target 'KaSim.native' failed
    make: *** [KaSim.native] Error 10

**Comment by feret** [comment]
This is quite strange, what is your ocaml version ? 
Mine is 4.02.3
and under which platform do you compile (I have tried both on Ubuntu 14.04 and Max OS X) ?

**Comment by hmedina** [comment]
Ah, I'm using OCaml 4.01.0, so that's probably the issue.
Sadly, that's the latest release on Cygwin, and Opam doesn't work in it (it's circular dependencies don't help...), so I have to fall back to the KaSim 3.5 release.

**Comment by jkrivine** [comment]
Can't you use the binaries ?

**Comment by feret** [comment]
Dear Jean, 

I think that the last binaries for Windows are from Nov 2014. 
It is the old KaSim 2.5 release. 

Cheers. 
Jerome

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by jkrivine** [comment]
I could generate a new one for windows then I guess.

**Comment by feret** [comment]
Dear Jean, 

If not too time consuming, it would be great. 

Cheers. 
Jerome.

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by jkrivine** [comment]
It seems there are binaries for windows on the release page Jerome. It 
says KaSim 3.5 (and not 2.5!)

**Comment by feret** [comment]
Yes, sorry my finger has fallen on the next touch on my keyboard. 
It is 3.5 and it is from Nov 2014, isn’t it ? 

Cheers. 
Jerome.

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by hmedina** [comment]
@jkrivine , I frequently need to use more than 2GB of RAM, hence my usage of the Cygwin 64bit compilers. If there were releases for 64bit Windows, I'd use them.
@pirbo , thanks for the update, seems to be working now.
