### ISSUE TITLE
KaSa mis-reads unpaired bond identifiers as self-bindings

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#124]
The following code is being read by KaSa without throwing an error, and in the resulting contact map there appears a self bond on both site 'b' of 'B' and site 'a' of 'C'. Both these sites have unpaired bond markers, so an error should be thrown.

```
A(s~o, a!1), B(b!1,c!2), B(d!2, b!3), C(a!4) -> A(s~x, a!1), B(b!1,c!2), B(d!2, b!3), C(a!4) @ 1.0
```

![contact](https://cloud.githubusercontent.com/assets/1588553/10569632/2c2226d2-75f7-11e5-9e41-dcf574ac3c3d.png)

**Comment by vd1** [comment]
Nice find!

**Comment by feret** [comment]
Dear Hector,

At the moment, there is no sanity check applied on what you give to Kasa.
Thus, it is recommended to first compile with KaSim, and use Kasa only if 
it works.

I have patched KaSa, to detect dandling bonds (and they are now replace 
with free site, while raising an alarm).

The correspondance between the alarm and the Kappa file is not described, 
but it will be done in further versions.

Cheers.
Jerome.



-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by feret** [comment]
I have changed dandling bonds into bonds to an unspecified site.
(And I still raise an alarm)

**Comment by feret** [comment]
Sorry the fix was wrong it should work better now. 
I have also prompted a warning in KaSim when KaSa reports an alarm. 

Yet, I think that this is not a good practice to send ill-formed expressions to KaSa. 
This syntactic analysis should be performed just after parsing, and report an alarm before starting semantics analysis.
