### ISSUE TITLE
download link is broken 

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#125]
Download link at www.kappalanguage.org/downloads.html (that is https://github.com/Kappa-Dev/KaSim/tree/master/bin ) is broken

**Comment by feret** [comment]
Thank you Anton, 

I am preparing the material for the course. 
You may download what you need there: 
http://www.di.ens.fr/~feret/teaching/2015-2016/master_AIV/ <http://www.di.ens.fr/~feret/teaching/2015-2016/master_AIV/>

I will advertise it on the moodle soon. 

Unfortunately, I have no access to the source of kappalanguage.org, thus I cannot correct it directly. 

Best regards. 
Jerome.


-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by feret** [comment]
I am a bit lost here. 
Which website should we advertise to the users ? 

This one: 
http://dev.executableknowledge.org
?

**Comment by pirbo** [comment]
kappalanguage.org redirects to dev.executableknowledge.org that have the good download links
