### ISSUE TITLE
KaSa badly fails when a link number is only mention 1 time

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#126]
On the model :
```
%agent: A(x)
'just_for_KaSa' A(x), C(x) -> A(x!1),A(x!1) @ 1
'broken' A(x!1),A(x) -> A(x),A(x) @ 1
```
bin/KaSa toto.ka outputs : 
```
Kappa Static Analyzer (DomainBased-94-gfe67970) (without Tk interface)
Analysis launched at 2015/11/10 14:42:12 (GMT-5) on air-pirbo.local
Parsing toto.ka...
done
Compiling...
Fatal error: exception Not_found
```
This makes KaSim failing too.

Because the exception is raised by KaSa_rep/frontend/preprocess/preprocess.ml line 660 (a line changed my patch you hated the most on earth Jérome), I want you to notice that it failed in the absolutely exact same way before (my example is done at revision fe679700c4807fc3c5a4303437537b993a9eb42f that is before my patch)

**Comment by feret** [comment]
This is a follow up of issue #124.

**Comment by feret** [comment]
Dear all, 

Today I was very surprised to see a slide with a decent contact map in D3 (made by Jean Coquet in Rennes).. 
I asked Adrien (Basso-Blandin), and he told me that he knew how to do it. 
Thus, we could use it directly, or fetch the position of nodes and plug to Gkappa (with a D3 output) to get more advanced layout. 

Cheers. 
Jérôme. 

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by pirbo** [comment]
I don’t see the link with this bug report anyway : THIS IS SOMETHING I TRY TO DO FOR MONTHS!
There is an option to print out stories directly in html (rendering using D3). I’m writing currently exactly right now a direct html renderer of flux map using D3 too.
Anyway, site graphes are still too much for me … Of course getting a forced based layout of snapshots (and contact map (and rules (and …))) where only agents appears was a 2 hours long exercice I did on a rainy saturday.
BUT, printing the sites at the beginning and at the end of edges as well as reserve some space for and print free sites is les standard and I never been achieve it in the limited amount of time I authorize myself to look at this question. If Adrien provides a solution, I’m merging the patch in the minute I see it :-)

Cheers,
Pierre B.
PS : Is Jean Coquet code available somewhere ? I would be happy to reverse-ingenier it too :-)
