### ISSUE TITLE
KaSa outputs files that are not requested

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#127]
The instruction:
``KaSa kaScript.ka --output-influence-map inflMap.dot``

Produces two files, an influence map named "inflMap.dot" and a contact map named "contact.dot". Likewise, the instruction:

``KaSa kaScript.ka --output-contact-map contMap.dot``
Produces two files, an contact map named "contMap.odt" and an influence map named "influence.dot".

This behavior is due to KaSa having as default behavior to compute the influence and contact maps (plus do reachability analysis). However, it is generating files the user did not request, and assigning them the default file names. Would it make sense to have KaSa resort to default behavior only when there are no command-line instructions, and if there are such instructions, to do only what is instructed?

**Comment by feret** [comment]
Dear Hector, 

There are two issues here. 
Firstly, the command line options that starts with --output do not toggle on/off some functionalities. 
They are redirecting outputs. 

To switch on/off you have to use the following ones:
0_Actions
  --do-all
      launch everything
  --reset-all
      reset everything
  --(no-)compute-contact-map    (default: enabled)
      compute the contact map
  --(no-)compute-influence-map    (default: enabled)
      compute the influence map
  --(no-)compute-reachability-analysis    (default: enabled)
      Compute iteration between the sites of agents


Secondly, the library interprets command line options one by one from left to right. 
Thus, asking to compute a contact map will not disable the computation of the influence map, and there are no contextual analysis that looks simultaneously for the instance of several options in the command line. 

To get the behavior that you expect, you can tune KaSa by choosing any of the three following methods:
1) You may create an alias (or a script) for the behavior you want.
2) You may use the command line option --reset-all to tune off each parameters and then ask to have the contact map:
KaSa --reset-all --compute-influence-map foo.ka
or
KaSa --reset-all --compute-influence-map --output-influence-map inflMap.dot foo.ka
or 
KaSa --no-compute-contact-map --no-compute-reachability-analysis --output-contact-map contMap.dot foo.ka
or 
KaSa --no-compute-contact-map --no-compute-reachability-analysis --output-contact-map contMap.dot --output-influence-map inflMap.dot foo.ka 
3) You may go into the file KaSa_rep/config/config.ml 
and change the default behavior, before compiling KaSa again (but I am not sure you can compile on your OS)

Cheers. 
Jérôme.

**Comment by hmedina** [comment]
Hi Jérôme!

I now understand what is happening. I misunderstood the explanation of the
options and thus thought there was a bug in the code; I see that is not the
case.
Just to be clear, when you say "reset everything", you don't mean "set from
whatever value to default", but mean "set from whatever value to off" ?
Thus ```$KaSa foo.ka --reset-all``` would do absolutely nothing?

Best,
Héctor

**Comment by feret** [comment]
I have put a better hint for the command line option --reset-all.
