### ISSUE TITLE
Causal flows: Detection of siphons is done on the full trace.

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#129]
The trace should be restricted to the events that are in the causal past of at least one  observable, before doing the detection of siphons.

**Comment by vd1** [comment]
Does this have anything to do with "siphons" in Petri nets (a subset X of
the set of species
such that X+ \subseteq X- meaning every reaction that produces one A in X
must consume on B in X - equivalently if the current marking projects to 0
on X
it will stay so forever)?

Vincent

**Comment by feret** [comment]
No this is not related.
For stories, a syphon is when an event 'e' makes an agent 'ag' go back in its initial state, and that nothing in the causal past of the agent 'ag', flows after the event 'e'.
