### ISSUE TITLE
Question mark in the right hand side are legitimate

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#130]
In current repository, the command `bin/KaSa models/large/big/*.ka` returns
```
Kappa Static Analyzer (DomainBased-213-gafe6925-dirty) (without Tk interface)
Analysis launched at 2015/11/19 15:48:56 (GMT-5) on air-pirbo.local
Parsing models/large/big/big_2.ka...
done
Parsing models/large/big/big_1.ka...
done
Parsing models/large/big/big_0.ka...
done
Compiling...
Generating the raw contact map...
Generating the raw influence map...
Refining the influence map...
Reachability analysis...
Some exceptions have been raised
error: file_name: Preprocess; message: line 228; exception:Exit
error: file_name: Preprocess; message: line 555, question marks should not appear on the rhs; exception:Exit
error: file_name: Preprocess; message: line 555, question marks should not appear on the rhs; exception:Exit
error: file_name: Preprocess; message: line 555, question marks should not appear on the rhs; exception:Exit
```
I havent done a minimal example because I'm lazy but rules of skeleton `A(x~n?) -> A(x~p?)` are OK and not equivalent to their version without a ? on  the right.

**Comment by feret** [comment]
Dear Pierre, 

There are two kinds of issues in the model. 
* big_2.ka: %var: 'n5mCG' DNA(init~mC!_, base~C!_) (line 30)
  The site init cannot be bound, thus, it has no binding state in KaSa, I have to implement a trick, to say that the concentration is always 0. 

* big_2.ka: 'SSB' DNA(e3~lig!1),DNA(e5~lig!1,base?,e3!2),DNA(e5!2) -> \
                            DNA(e3~P!1),DNA(e5~NA!1,base~AP?,base_state~gapped,init~damaged,e3~NA!2),DNA(e5~P!2) @ 'k_SSB'
(line 26)

Here is KaSa reasoning:
DNA does not have the same interface in the lhs and in the rhs. 
Thus, it is degraded, then created, and we are not allowed to create agents with question marks. 
So, this is fair to reject this model, and it should be detected by KaSim in the sanity tests check. 

It is important to refine KaSa warning, especially, that I can have access to precise location in the kappa file. 
I will do it, but it it not in the top of the stack. 

Do you share my interpretation, or should I change anything in KaSa?

Cheers. 
Jérôme. 

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by pirbo** [comment]
I agree that not seing the problem in 
>* big_2.ka: 'SSB' DNA(e3~lig!1),DNA(e5~lig!1,base?,e3!2),DNA(e5!2) -> \
>DNA(e3~P!1),DNA(e5~NA!1,base~AP?,base_state~gapped,init~damaged,e3~NA!2),DNA(e5~P!2) @ 'k_SSB' (line 26)
is a mistake of KaSim.
I've also rediscuss with Hector that the new longest prefix convention is absolutely not intuitive for users and that KaSim must explain what we understand before reporting this error else the error is completely cryptic! Maybe, flushing warnings before failing is enough and easy, I'll look ...

On the contrary, KaSim cannot see the problem in 
>* big_2.ka: %var: 'n5mCG' DNA(init~mC!_, base~C!_) (line 30)
before getting a contact map from KaSa so you have to deal with it :-)

**Comment by feret** [comment]
Sure I will fix KaSa so as to deal with unreachable states. 
I know how to do it in a clean and robust way.
But it is not my priority at the moment.

**Comment by feret** [comment]
For the convention, I think that in any cases, if we want to have a compact syntax, there is a need for a convention, and that whatever the one we take, it needs to be explained. 

What I did not like between the former one in KaSim, is that it was very permissive from a syntactic point of view. And my colleagues were just making mistake and it was not catch by KaSim, because KaSim was giving a meaning to everything.
