### ISSUE TITLE
Missing stories

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#140]
In the following model:

%def: "displayCompression"  "weak" 
%def: "showIntroEvents" "true"

%agent: A(x)
%agent: B(x,y~u~p)

'r1' A(x),B(x,y~u) -> A(x!1),B(x!1,y~u) @1
'r2' B(y~u) -> B(y~p) @1

%init: 1 A(x),B(x,y~u)
%init: 1 A(x!1),B(x!1,y~u)

%obs: 'Bond' |A(x!2),B(x!2,y~p),A(x!1),B(x!1,y~p)|
%obs: 'Not_bond' |A(x),B(x,y~p),A(x!1),B(x!1,y~p)|

%mod: [true] do $TRACK 'Bond' [true]
%mod: [true] do $TRACK 'Not_bond' [true]

The story 'Bond' is never trigerred. 
KaSim finds one of the two potential stories for the observable "Not+bond", 
or reach a deadlock without reporting a story. 

Unless I am wrong, the system utlimately reach one of the two observed states, thus the simulator should send a story to compress, at any run. 

What is wrong with my model ? 

Cheers. 
Jérôme.

**Comment by pirbo** [comment]
You may want to add this in the test-suite ...
