### ISSUE TITLE
Random_tree.random is not random when activity is infinity

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#141]
Is it problematic ?

It is trivial to fix, replace l.155 `IntSet.choose` by `IntSet.random` et voilà

**Comment by vd1** [comment]
The way "infinity" is used is always conflict less - so that one gets the
same result no matter what the order is;
so I would say it is ok as it is (as long as it is doumented somewhere).
But one can argue for random as well.

**Comment by feret** [comment]
Is it enforced by construction? 
It reminds me a discussion with a modeler (not a biologist, but a computer scientist / logician indeed) outside of the scope of our dev/user groups. 
 1)X:  We use infinite rates, this is not a problem: we are careful and only use noetherian and confluent systems of rewrite rules with infinite rates. 
 2)JF: Oh look, these two rules with an infinite rate, they actually  make a decision, your system is not confluent. 
 3) X: Oh we do not care, the system is noetherian, and they have an infinite rate anyway...

**Comment by vd1** [comment]
No it is not enforced by construction, just the way I see people using
infinite rates, that is the problem. So perhaps random is better.
