### ISSUE TITLE
Make the documentation of @@ syntax for rule rates independent from rule left hand side

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#144]

**Comment by vd1** [comment]
that looks like an interesting feature!

**Comment by pirbo** [comment]
This experimental feature has been removed.
It is not clear to integrate it with the fact that selecting injections from pattern to graph connected component by connected component can lead to clashing instances. The activity of rules is corrected to reflect that in the standard case but it would have been the user duty to do it here. Things impossible without knowing the simulator internals ...

**Comment by rhz** [comment]
Couldn't that problem be solved by not advancing time when a clash happens in the case of a @@ rule?
