### ISSUE TITLE
KaSim throw an exception Not_found on this example. 

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#145]
The example is at the end of the message. 

If I replace the line:
-> A() @ 'k'
with 
-> A() @ 10 ;
the simulation works fine. 

%agent: A()

%var: 'kon' 10
%var: 'koff' 0

%var: 'lon' 10
%var: 'loff' 0 

%var: 'k' 'kon'
%var: 'l' 'loff' 

%obs: 'A' A()

-> A() @ 'k'
A() -> @ 'l'

%mod: repeat 'A'>10 do ($UPDATE 'k' 'koff';$UPDATE 'l' 'lon') until [false]
%mod: repeat 'A'<10 do ($UPDATE 'k' 'kon';$UPDATE 'l' 'loff') until [false]

**Comment by pirbo** [comment]
I'm sorry I cannot reproduce with bin/KaSim -e 10000 -d /tmp/truc -o data.svg -p 200 models/permanent_update.ka

**Comment by feret** [comment]
Yes, I do understand, it is working now. 
Sorry for the disturbance.

**Comment by vd1** [comment]
On 17 December 2015 at 08:51, Pierre Boutillier <notifications@github.com>
wrote:

> I'm sorry I cannot reproduce with bin/KaSim -e 10000 -d /tmp/truc -o
> data.svg -p 200 models/permanent_update.ka
>
so you can input without the -i option? and "data.svg" is that outputting
direct in svg?
V.

**Comment by pirbo** [comment]
> Le 17 déc. 2015 à 07:53, Vincent Danos <notifications@github.com> a écrit :
> 
> On 17 December 2015 at 08:51, Pierre Boutillier <notifications@github.com>
> wrote:
> 
> > I'm sorry I cannot reproduce with bin/KaSim -e 10000 -d /tmp/truc -o
> > data.svg -p 200 models/permanent_update.ka
> >
> so you can input without the -i option?
Yes
> and "data.svg" is that outputting direct in svg?
Yes
> V.
:-)

**Comment by vd1** [comment]
awesome!
