### ISSUE TITLE
Fatal error: exception Not_found

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#146]
The following code:
```
%agent: fE(c,s)
%agent: fC(e,s)
%agent: fS(c,e,s~o~x)

'f:E.C+' fE(c), fC(e) -> fE(c!1), fC(e!1) @ 1.0e-4 (1.0e-3)
'f:E.C-' fE(c!1), fC(e!1) -> fE(c), fC(e) @ 1.0e-2

'f:C.O+' fC(s), fS(c,s~o) -> fC(s!1), fS(c!1,s~o) @ 1.0e-4 (1.0e-3)
'f:C.O-' fC(s!1), fS(c!1,s~o) -> fC(s), fS(c,s~o) @ 1.0e-2
'f:C.X+' fC(s), fS(c,s~x) -> fC(s!1), fS(c!1,s~x) @ 1.0e-4 (1.0e-3)
'f:C.X-' fC(s!1), fS(c!1,s~x) -> fC(s), fS(c,s~x) @ 1.0e-1

'f:E.O+' fE(s), fS(e,s~o) -> fE(s!1), fS(e!1,s~o) @ 1.0e-4 (1.0e-3)
'f:E.O-' fE(s!1), fS(e!1,s~o) -> fE(s), fS(e,s~o) @ 1.0e-2
'f:E.X+' fE(s), fS(e,s~x) -> fE(s!1), fS(e!1,s~x) @ 1.0e-4 (1.0e-3)
'f:E.X-' fE(s!1), fS(e!1,s~x) -> fE(s), fS(e,s~x) @ 1.0e-1

'f:S->P' fE(), fS(s~o) ->  fE(), fS(s~x) @ 0.0 (1.0)
%obs: 'fS(s~o)' |fS(s~o)|
%obs: 'fS(s~x)' |fS(s~x)|

%init: 1000 fC()
%init: 10 fE()
%init: 10000 fS()
```
Produces a fatal error. If some of the rules have smaller rates (e.g. 'f:E.X-'), the error occurs less frequently. If some rules are removed (e.g. 'f:S->P' or the 'f:?.X[+|-]'), the error also occurs less frequently. With all the rules provided, it reliably occurs every time in less than 1000 bio-seconds of simulation.

**Comment by hmedina** [comment]
Issue current as of version:
Kappa Simulator: DomainBased-471-g1057e80

**Comment by feret** [comment]
Can be reproduced with: 
-t 120 -seed 56235278

**Comment by pirbo** [comment]
This reveals a problem in the storage of the simulation state. Potential instances of unary rules are stored as 2 maps:
 - rule_number -> pair of "root" of connected component
 - pair of "root" -> path between them

For now when I remove a pair of root of the candidates for a rule. i also remove the path between these "roots". In the example, 2 different rules share the same potential roots.
If one rule does not apply anymore for a given pair of roots, we must not remove the corresponding path between the roots as this path is important for the other rule (that remains possible for these roots).

A trivial but disgusting fix is to never remove paths. A less trivial but still ugly solution is to store how many rules rely on each path and remove a path only when this number reaches 0.

**Comment by feret** [comment]
Would there be a tiny chance that you could use the beautiful lattice structure, to describe exactly to which contexts each root is compatible, or not ?

**Comment by pirbo** [comment]
When roots are not member of a loop in the contact map, using the lattice structure is smart and should be done! When "it polymerases" we discuss building the lattice of connected roots up to a given maximal distance but it didn't convince our biologists ;-)
