### ISSUE TITLE
Missing error when requesting stories but not specifying compression level

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#147]
The following code executes successfully but produces no output.
```
%agent: A(c,q)
'r' A(c), A(q) <-> A(c!1), A(q!1) @ 1, 1
%mod: [T] > 0 do $TRACK A(c!1), A(q!1) [true]
%mod: |A(c!1), A(q!1)| = 1 do ( $TRACK A(c!1), A(q!1) [false] ; $STOP )
%init: 2 (A())
```
If however the following line is added,
```
%def: "displayCompression" "none"
```
then the story is printed to a file. It would be useful if KaSim would issue an error when a story is requested, but the compression level is not specified. Alternatively, if there is a default behavior (e.g. no compression), then it could be a warning instead.

**Comment by hmedina** [comment]
Kappa Simulator: DomainBased-524-g8331032

**Comment by feret** [comment]
@Hector: could you check that you are happy with this solution ? 
@Pierre: could you see if it is compatible with KaSim policy, and decide whether we should provide a formatter to add_events, and/or whether we should redraw the progress bar after a warning. 
Any alternative solution would be welcome.

**Comment by pirbo** [comment]
The usage initiated by Jean is to get the warnings before the beginning of the simulation. Therefore I would be less precise than what you did and generate a warning in grammar/eval.ml at the bottom if tracking_enable && not (!Parameter.causalModeOn || !Parameter.weakCompression || !Parameter.mazCompression || !Parameter.strongCompression) saying "An observable may be tracked but any compression level to render stories has been specified"

**Comment by feret** [comment]
Voilà, ça doit aller mieux maintenant.

**Comment by hmedina** [comment]
This may be just a usage thing, but why is this a warning and not an error? My rationale is that, if the user requested a track, and the simulator performs the track, but is unable to do anything with it (other than the compression_status.txt and profiling.text files), then performing the track was pointless. This seems like a waste of processing time. In a bad case where the tracked event requires a long runtime, this behavior would yield an unproductive but time consuming KaSim execution.

**Comment by feret** [comment]
Dear Hector, 

I am very open on this. 
I used a warning because to me, it is not blocking, and maybe the user would like to have the result of the simulation anyway. 
Moreover it provides a way to turn off compression by commenting one line of code only, which is quite convenient. 

So let me know what it the opinion of the majority on this, and I will follow it. 

Cheers. 
Jérôme.
