### ISSUE TITLE
Story profiling file not directed to directory specified with -d command line option

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#148]
When invoking KaSim with the ```-d [dir]``` option, most files get directed to ```[dir]```, except the file produced by the story engine, ```profiling.txt```, which is created at the current directory.

Kappa Simulator: DomainBased-524-g8331032

**Comment by hmedina** [comment]
Correction: two files are generated, an empty ```profiling.txt``` in the current directory, and a filled in file ``profiling.txt``` in ```[dir]```.

**Comment by feret** [comment]
I have renamed both files in commit db52b23  

The first one: "compression_status.txt" gives the current status of the search engine. 
The information is logged each 10 minutes, this is why it is empty in most cases. 

The other "profiling.txt" logs the CPU consumption of each step of the pipeline. 

Both files are now located in the directory provided by the -d option.

**Comment by pirbo** [comment]
An empty profiling.txt is still generated in the current directory
