### ISSUE TITLE
Fatal error: exception Failure("Matching.reconstruct renaming error")

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#149]
Do you know where this exception is coming from ? 
Unfortunately, I do not know whether I can share the model, or not. 

I have contacted the author to see if I can send the model to Pirbo, or if I can show it to him in Boston.

**Comment by pirbo** [comment]
This is a big issue! This reveals probably a bug in the negative update.
Module Matching is in module Connected_component in folder term/ reconstruct is the function which given a connected pattern and a root of an EXISTING injection returns the complete injection.
Indeed, I cannot go further without being able to reproduce.

**Comment by feret** [comment]
Modèle envoyé sur email privé.
