### ISSUE TITLE
Flux map not output for some models

### ISSUE THREAD

**Issue by johnbachman** [Kappa-Dev/KaSim#150]
I'm working on a Python wrapper for kasim and am testing flux map generation. I've been finding that with some models the flux map is output but for others the file just doesn't appear. Can someone help me figure out why the following model (below, and attached) doesn't produce a flux map? Apologies in advance if it's something trivial.

-------------- Model -------
%agent: A(b)
%agent: B(a,c)
%agent: C(b)

%var: 'k' 1.000000e-03
%var: 'A_0' 1.000000e+02
%var: 'B_0' 1.000000e+02
%var: 'C_0' 1.000000e+02

'A_binds_B' A(b),B(a) -> A(b!1),B(a!1) @ 'k'
'C_binds_B' C(b),B(c) -> C(b!1),B(c!1) @ 'k'

%obs: 'ABC' A(b!1),B(a!1,c!2),C(b!2)

%init: 'A_0' A(b)
%init: 'B_0' B(a,c)
%init: 'C_0' C(b)

%mod: [true] do $FLUX "test_flux_map_fm.dot" [true]

--- Command line ---

I run kasim with the args

$ kasim -i test_flux_map.ka -t 10 -p 100 -o test_flux_map.out

I get test_flux_map.out with a trajectory for ABC but the flux map dot file does not appear.

I am running the version of KaSim tagged 'last-KaSim3'.

---- Output ---

$ kasim -i test_flux_map.ka -t 10 -p 100 -o test_flux_map.out
+ Command line is: 'KaSim' '-i' 'test_flux_map.ka' '-t' '10' '-p' '100' '-o' 'test_flux_map.out'
Parsing test_flux_map.ka...
done
+ Self seeding...
+ Initialized random number generator with seed 58216766
+ Compiling...
     -simulation parameters
     -agent signatures
     -variable declarations
     -initial conditions
     -rules
     -observables
     -perturbations
     Done
+ Analyzing non local patterns...
+ Building initial simulation state...
     -Counting initial local patterns...
     Done

File "test_flux_map.ka", line 13, characters 6-36:
Warning: Deprecated variable syntax: use |kappa instance| instead.
____________________________________________________________
############################################################
Simulation ended
[test_flux_map.txt](https://github.com/Kappa-Dev/KaSim/files/92144/test_flux_map.txt)

**Comment by johnbachman** [comment]
This appears to have been fixed as of 7da423614bab6fb. Closing.

**Comment by feret** [comment]
This commit is not related to the issue.
