### ISSUE TITLE
Confusion between rate and unary rate

### ISSUE THREAD

**Issue by icristescu** [Kappa-Dev/KaSim#155]
In the rule
lhs -> rhs @ (10)
we expect an error as only a unary rate is provided. However as rates are algebraic expressions, the parentheses are allowed and the rate is not interpreted as an unary rate.

**Comment by vd1** [comment]
Hello

Why would you like an error? To prevent people from writing this?
Or would like a warning maybe?

Cheers
Vincent

**Comment by pirbo** [comment]
I would also expect 
lhs -> rhs @ (10)
and
lhs -> rhs @ 0 (10)
to be synonym ... 
Maybe putting unary rates in between [] or {} is a better fix than to forbid regular rates in parenthesis

**Comment by jkrivine** [comment]
This is dangerous. How would you parse

  L -> R @ ('x'/'y'+1)

Maybe the (_) notation should be replaced by [_] to avoid ambiguities?

**Comment by pirbo** [comment]
Is someone against the fact to put unary rate of rules between curly brackets ?

**Comment by feret** [comment]
Good idea indeed. 

Cheers. 
Jérôme.
