### ISSUE TITLE
ui fixes

### ISSUE THREAD

**Issue by majorseitan** [Kappa-Dev/KaSim#157]
1. pass runtime via args
2. handle webworker exception in chrome
3. fix token not found
4. stop simulation

**Comment by pirbo** [comment]
- it still looks for harness.js
- you should remove the debug messages in the console when it is ready
- It completely crash if you launch a simulation asking for 0 points in the plot

**Comment by pirbo** [comment]
- one Firebug.console##log remains
- Warnings about compilation are in the log that's cool, warnings during (and at the end of execution are running (models/abc-by-tok.ka raises one if you need a test))

**Comment by pirbo** [comment]
- time_yield (from WebWorkers) should be used in Embedded mode too

**Comment by majorseitan** [comment]
all items have been addressed
