### ISSUE TITLE
WebSim REST API 1.1.0-DRAFT

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#162]
I created an issue https://github.com/Kappa-Dev/KaSim/issues/161 to discuss issues that I face with current API, but I also have some ideas how we can restructure an API. 
I created a wiki page for the draft of future API ( https://github.com/Kappa-Dev/KaSim/wiki/Kasim-Rest-API-NEXT---DRAFT ) It is separate from Kasim-Rest-API because the previous one is for documentation and should be insync with the master branch of KaSim while in the draft we can experiment with breaking changes.

In the draft I used previous API and proposed few changes (watch wiki history to see the difference)
1) Most of the parameters that we have in API are marked optional even in places where we will certainly have something (for instance there is no point to send simulation for execution without anything in the code field, so the code field should be required) this creates additional problems for people who will write clients as they will have to put Option[Something] everywhere. So I made some params nonoptional (where it looked obvious that they will be needed)
2) Renamed Parameter entity to RunParameters to avoid confusion and also added it into Status
3) Other change proposals will be seen in wiki history and further comments to this issue

**Comment by majorseitan** [comment]
Closing in anticipation of new API.
