### ISSUE TITLE
%def: "storeUnaryDistance" "true" must be documented in the reference manual

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#163]
It would reply to question raised  by @antonkulaga  in #161.

**Comment by antonkulaga** [comment]
@pirbo could you give me any model where %def: "storeUnaryDistance" "true" works well in WebSim?
I am trying to get some unary distances in the latest nighty build but it always returns me an empty list in the json.

**Comment by antonkulaga** [comment]
I tried some models from https://github.com/Kappa-Dev/KaSim/tree/master/models/test_suite/simulation but WebSim does not return me any distances from them

**Comment by hmedina** [comment]
Possibly unrelated, but the manual in table 6.2 writes it as <<
storeUnaryDistances>>, in plural.

**Comment by pirbo** [comment]
`%def: "storeUnaryDistance" "true"` has been unplugged as it is unfinished work in WebSim (technically, api_v1 runs `finalize` (and therefore `State_interpreter.end_of_simulation`) only during `stop` aka just before discarding the simulation so the array which is filled by end_of_simulation is never returned...)

**Comment by pirbo** [comment]
Everything here is addressed, isn't it?
