### ISSUE TITLE
passing seed to wensim process

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#165]
For the sake of integration testing it would be nice to be able to pass seed to WenSim when I am starting the simulation

**Comment by pirbo** [comment]
It would not do what you think ...
The random number generator is a global state of each executable. It means that several simulations running in the same WebSim uses the same random number generator and numbers given to each interleaves...
The only reasonable thing we can provide is to specify the seed when you launch a server and then if you want determinism, it is your duty to ensure that on this server 2 threads won't never ever ask for random numbers at the same time! This is part of #167.
