### ISSUE TITLE
fix ui bugs

### ISSUE THREAD

**Issue by majorseitan** [Kappa-Dev/KaSim#171]
This is a catch all that is expected to be updated by everyone. Currently there
are a few bugs in the UI.

**Comment by majorseitan** [comment]
Error messages not being cleared.

**Comment by pirbo** [comment]
Probably related:
1/ Start to launch a simulation with nothing into max event and nothing into time limit in WebWorker or embedded mode
It says Error at line 0, characters -1--1: : There is no way for the simulation to stop.
2/ set a time limit and launch the simulation. It will launch the simulation and return back to the control panel BUT the simulation will run in the back ground (with no possibility to stop it)
3/ You can launch as many simulation you want that will create a complete mess into the plot panel:-)

**Comment by majorseitan** [comment]
Fixed.
