### ISSUE TITLE
+ display something for localhost:8080 and also display 404

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#175]
When I open websim it does not display anything for http://localhost:8080 , maybe redirection to http://localhost:8080/v1/ would be nice? Also, it would be useful to have 404 on wrong links, so when you make a typo in a link you will get 404 that makes understand that it is a typo and not a problem with the server or parameters that you pass

Note: I know you are very busy, that is why I want to say that this issue of a little importance to me

**Comment by majorseitan** [comment]
Switched to 404.
