### ISSUE TITLE
Better window for small screen

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#185]
When half the screen is less than 80 cols wide. The model text should take all the width of the screen.

More difficult and less critical. It would be fancy in this case to integrate the model as one tab mixed with the outputs ones instead of putting the outputs "below".

**Comment by majorseitan** [comment]
Unless there is a critical need for this I am going to close as there is no support in codemirror to provide this functionality.

**Comment by pirbo** [comment]
Not critical indeed
