### ISSUE TITLE
Scroll in model input zone

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#190]
It may be a code mirror issue but I'd love that scrolling with the mouse when the pointer over the model text scroll the model text and not the web browser window ...

**Comment by pirbo** [comment]
The problem is in fact more precise and should be rephrase: After loading a file using the load button, scrolling the model does not work at first. You have to put the focus in the input part and "go down" until the model scroll to "enable" scrolling using the mouse.

**Comment by majorseitan** [comment]
Would setting the focus when a file is loaded address this problem?

**Comment by pirbo** [comment]
I cannot reproduce the bug anymore, sorry for the noise
