### ISSUE TITLE
request a "Parse" only at the end of the edition of a line

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#194]
If I'm not forgetting anything it means "parse" when the cursor position change of line/leave the input **after** an edition by:
  * \n
  * up/down arrow
  * scroll
  * click

**Comment by pirbo** [comment]
I'm sorry I'm never happy. I find that the delay is exactly what you expect "before receiving an error" but that it is annoying to wait to see whether you've fixed it.
Maybe we should try a 2 modes mode: While there is no error reported, delay parse. When an error is highlighted, parse every edition.
Anyway, it is very low priority. This is better with always the delay than with no delay!

**Comment by hmedina** [comment]
How about putting a button that says "parse now" ?
When editing observables, I assume the parser has to work more than when
editing rules, and when editing perturbations it would be much faster, so
maybe the behavior can be cursor-position specific?

**Comment by vd1** [comment]
+1
sounds like a great feature.

**Comment by pirbo** [comment]
Great Thanks
