### ISSUE TITLE
Show contact map graphically

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#199]
This is the version of #197 where several edges starts for the same site.

**Comment by majorseitan** [comment]
KaSim/api/api.ml
let contact_map,_kasa_state =
        Eval.init_kasa Remanent_parameters_sig.JS raw_ast
KaSa_rep/export_to_KaSim/export_to_KaSim.ml
val get_contact_map: state -> state * (string list * (string*string) list) String2Map.t

**Comment by pirbo** [comment]
Are still missing:
- self binding
- internal states

**Comment by pirbo** [comment]
Only remaining step is #256

**Comment by jkrivine** [comment]
I love the new contact map displays. Simplifies a lot the layout problem!

Any hope we can have internal states for the class?

J


Le 01/07/2016 à 16:55, Pierre Boutillier a écrit :
>
> Are still missing:
>
>   * self binding
>   * internal states
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Kappa-Dev/KaSim/issues/199#issuecomment-229968251>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AAR5jnvMl95PsQkt8zze1gm5R97BHlwHks5qRSpbgaJpZM4H-u8l>.
>

-- 
Chargé de recherche à l'IRIF
Équipe PPS - Univ. Paris Diderot
+33 1 57 27 93 38
