### ISSUE TITLE
KaJaSim: plot marks are too dense when number of plot points is high

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#203]
In the Kappa Javascript Simulator, one can plot the variables. These get presented with a mark (e.g. a square, a triangle, a circle) once per plot point. In cases where there are many plot points, the marks cluster and give the appearance of a very thick solid trace. It would be useful to use plot lines connecting the plot points instead of using big plot marks.

**Comment by majorseitan** [comment]
Switched to lines while I address address this issue.

**Comment by pirbo** [comment]
1 more point: scale with respect to the visible observables (do not take into account hidden one)

**Comment by majorseitan** [comment]
@pirbo  @hmedina I have addressed the scaling issue can you close this ticket if there are no follow up for this issue.

**Comment by hmedina** [comment]
The plot now scales to accommodate what is being displayed in the plot.
