### ISSUE TITLE
KaJaSim feature idea: multi-file support with toggable inclusion

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#206]
Kappa scripts are usually written in multiple parts (e.g. a file for some rules, a file for other rules, a file for observables). It would be useful if one could "load" these files into a workbench area where they then could be ran.

Additionally, some of these files are usually different versions, i.e. model variants. It would be useful if one could toggle (i.e. check boxes) which of the files in the workbench get concatenated into the executed script.

**Comment by antonkulaga** [comment]
I suggest to change websim API for running models to make it easier to provide multiple files. Maybe instead of just code string we can allow to have a dictionary of filename->filecode  and in error reporting there should be not only line numbers and eror messages but also file names ?

**Comment by pirbo** [comment]
Congratulation !!!
