### ISSUE TITLE
Stalled models should check for perturbations

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#21]
If model has a deadlock (no rule can be applied) at time t, and if there is a perturbation at time t+Dt then it should increment time of Dt and apply the perturbation.

Note that if it deadlocks at event E and a perturbation is defined at event E+dE it should deadlock (and output a warning)

**Comment by pirbo** [comment]
This problem of precondition that depends on biological time is way more general than this issue with deadlocks!
For now, preconditions that contains f(t)=0 are forbidden unless f is an affine function that go not involve neither var nor e! In with cases, going to the potential stopping time even if it is after a deadlock is correctly handled.
Yes if a user writes f(var,t,e) > 0 we would deadlock too eagerly but so much problems and non intuitive behavior appear in thus situation that I consider deadlock management negligible!
