### ISSUE TITLE
legend is corrupted in WebSim json response

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#212]
When I run simple abc model to WebSim I get wrong observables names (when each legend observable name is concatenated with previous).
Here is what I get for abc model ( https://github.com/Kappa-Dev/KaSim/blob/master/models/abc-cflow.ka )
```
"legend":["'AB'","'AB''Cuu'","'AB''Cuu''Cpu'","'AB''Cuu''Cpu''Cpp'"]
```
As you see: instead of "Cpp" I get "'AB''Cuu''Cpu''Cpp'"

**Comment by majorseitan** [comment]
Using curl, could you provide a complete message (pastebin etc.) along with the curl command used.

**Comment by pirbo** [comment]
I cannot reproduce. Does it still happen?

**Comment by antonkulaga** [comment]
I do not observe it after updating to master. Seems like you fixed it

**Comment by antonkulaga** [comment]
I have to reopen it because I get strange legend values when I send just abc.ka model. What is interesting is that the bug does not exist on webworker version but appeared in the latest version of websim.

Here is the json I sent to run the model:
[TestRequest.json.txt](https://github.com/Kappa-Dev/KaSim/files/357609/TestRequest.json.txt)

The CURL is the following:
```bash
curl -vX POST http://localhost:8080/v1/process -d @TestRequest.json.txt --header "Content-Type: application/json"
```
then I get a token and here is the results that I see on this token: 
[TestResults.json.txt](https://github.com/Kappa-Dev/KaSim/files/357612/TestResults.json.txt)

(note: github does not allow to load .json files to comment so I had to make them .json.txt)

As you may notice the value of legend is "legend":
```json
"legend":["'AB'","'AB''Cuu'","'AB''Cuu''Cpu'","'AB''Cuu''Cpu''Cpp'"]
```
while it should be something like:
```json
"legend":["AB","Cuu","Cpu","Cpp"]
```
The system that I tested it on is Linux Mint (Ubuntu) with UTF8 as default encoding.

**Comment by pirbo** [comment]
With what version of ocaml do you compile WebSim?

**Comment by antonkulaga** [comment]
4.02.1

**Comment by antonkulaga** [comment]
With latest ocaml I have constant Segmentation fault errors, not sure how to deal with them....

**Comment by antonkulaga** [comment]
@pirbo you were right, it is an ocaml version issue: with  4.02.3 it works fine.
