### ISSUE TITLE
KaSa produces profiling output even when called with --reset-all

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#214]
When calling KaSa with the ```--reset-all``` option, which the help option says should "launch nothing", a directory called "output" is created containing a "profiling.txt" file. My understanding of a "launch nothing" is that it would simply evaluate the file and report problems to standard output.

When trying to evaluate if a kappa file is valid (e.g. proper syntax, not unreachable observables), KaSim is not advisable as it will initialize the mixture (and demand non-zero plot points...). KaSa should be able to do this without silently outputing directories and files.

If this would not be desirable for what ```--reset-all``` means, maybe there should be a ```--stdout-validity-check``` option.

**Comment by feret** [comment]
The profiling output is always generated.
This is not a functionality. It just logs CPU time of each phase. 
This is the equivalent of a console, and cannot be disabled.
