### ISSUE TITLE
Standardize KaSim's data output (like KaJaSim's)

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#215]
The OCaml simulator's space-separated-values formatted output has the following issues:
* KaSim and KaSa allow spaces in variable names. These would be printed in the first line of the output file as column headers. A space-separated-file with non-delimiter spaces is not user-friendly.
* If there are ```n``` observables, KaSim produces ```n+1``` space-separated-values for all the data lines, but ```n+2``` space-separated-values for the header line. The first element is a cryptic ```#``` (vestige of when outputing event number was default?), the second element is the expected time column.

The OCaml simulator's output would be more user-friendly if it followed the Javascript simulator's tab-separated-file format.

**Comment by pirbo** [comment]
Super easy to implement but huge backward incompatibility cost.
It would break any post-processing script/application/... other datas such as @plucky auto-refresh-gnuplot-plotter :-)
I think we should go for it but I don't take the responsibility alone.

**Comment by hmedina** [comment]
Actually, since the inconsistent format starts with a <<#>>, it could serve as a flag. It would be easy to have a script that calls the custom scripts or the standard readers based on that flag. That would preserve backward compatibility while remaining true to the spirit of write-your-own-parser.

**Comment by pirbo** [comment]
On the second look, having column names as the last line of the file header (so starting by a #) is exactly how gnu plot expects the data...

**Comment by hmedina** [comment]
Then how about supporting ``.tsv`` in addition to ``.out`` ? The codebase already supports both formats, and a way of formatting the output based on file extension. For example, if the user were to invoke ``$KaSim -o myOutput.out`` (s)he would get a GNUplot compliant file, but if invoking ``$KaSim -o myOutput.tsv`` (s)he would get a standard tab separated values file.
