### ISSUE TITLE
KaSim fails cryptically

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#216]
The following code crashes KaSim without error.
```
%agent: A(x,y)
%agent: B(x,y)
'Ax.xA+' A(x), A(x) -> A(x!1), A(x!1) @ 1.0e-4 / 2 (0)
'Ax.xA-' A(x!1), A(x!1) -> A(x), A(x) @ 1.0e-2 / 2
'Ay.yA+' A(y), A(y) -> A(y!1), A(y!1) @ 1.0e-4 / 2 (0)
'Ay.yA-' A(y!1), A(y!1) -> A(y), A(y) @ 1.0e-2 / 2
'Bx.yB+' B(x), B(y) -> B(x!1), B(y!1) @ 1.0e-4 (0)
'Bx.yB-' B(x!1), B(y!1) -> B(x), B(y) @ 1.0e-2
%init: 10000 (A(), B())
```
This is the invokation and stdout:
```
$ KaSim -i myFile.ka -t 100 -seed 299681189
+ Command line is: 'KaSim' '-i' 'myFile.ka' '-t' '100' '-seed' '299681189'
Parsing myFile.ka...
done
+ Initialized random number generator with seed 299681189
+ Sanity checks
+ KaSa tools initialization
+ Compute the contact map
+ Compiling...
+ Building initial simulation conditions...
         -simulation parameters
         -variable declarations
         -rules
         -perturbations
         -observables
         -initial conditions
         Done
____________________________________________________________
#
```
This crash is frequent with the above seed and parameters, but does not always happen. Some runs the simulation succeeds, some runs it crashes at other sim-times.
```
$ KaSim --version
Kappa Simulator: DomainBased-1190-gd0fa48b
```

**Comment by pirbo** [comment]
Arg, I cannot reproduce. 5 attempts 5 success under both my MacOS and my debian testing. 
My guess for failing with no error would be memory corruption but that's strange!

**Comment by hmedina** [comment]
After re-compiling the same source code, the crash stops happening. Our conclusion is that "the compiler was in a bad mood". A few times it complained about "index out of bonds" before crashing, but it mostly just crashed silently.
