### ISSUE TITLE
KaJaSim feature idea: define plot boundaries (aka zoom-in)

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#218]
Once a simulation is ran and the data is generated, it would be useful to define what range it is to be plotted. The default could be to plot all the data (i.e. all the amounts for all timepoints), but the user could then re-do the plot with a different [lower,upper] bound for each axis, plotting only what's inside that window.

**Comment by pirbo** [comment]
This is an other facade of #297

**Comment by majorseitan** [comment]
@hmedina 
By setting the number of points and using the slider should end up with the same user experience.

**Comment by pirbo** [comment]
The slider is visible only when simulation is paused that's why I did not see it in the first time. Excellent, this is exactly what we need!
