### ISSUE TITLE
KaJaSim: parser does not demand a rate for irreversible rules

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#221]
The Kappa Javascript Simulator's parser flags as an error when reversible rules don't have rates, but does not flag as an error when irreversible rules lack rates. E.g.
```
%agent: A(x)
'x.x+' A(x), A(x) <-> A(x!1), A(x!1)
```
```
Error at line 2, characters 7-36: : Incompatible arrow and kinectic rate for inverse definition
```
But the similar irreversible rules receives no parse error:
```
%agent: A(x)
'x.x+' A(x), A(x) -> A(x!1), A(x!1)
%init: 10 A()
%obs: 'A()' |A()|
```
In fact, it allows the simulation to be launched, reaches the deadlock, and then spews a very large number of copies of the expected error. Notice that it also complains about the rule in line 3, even though there is no rule in line 3.
```
+ Building initial simulation conditions...
 -simulation parameters
 -variable declarations
 -rules
 -perturbations
 -observables
 -initial conditions
 Done
 ?
 A deadlock was reached after 0 events and 0.000000E+00s (Activity = 0.00000)
 line 2, characters 36-36: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 3, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 36-36: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 36-36: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 36-36: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 36-36: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 36-36: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
 line 2, characters 35-35: Warning: Rule has no kinetics. Default rate of 0.0 is assumed.
```

**Comment by pirbo** [comment]
There are 2 issues in this issue. First warnings are not showed correctly in the IDE. True, @majorseitan is working on that, that's "minor". More important indeed:
Do not provide a rate to an irreversible rule is a warning whereas providing 0 or 1 rate for a reversible rule is an error (well providing 0 is 1 warning and 1 error :-)).

3 possible fixes:
 - Not providing a rate to an irreversible rule is an error (my preference but rules without rate are present in the test-suite so their must be a reason...)
 - Not providing a rate for the reverse direction of a reversible rule is a warning and
    * the default value is 0.0
    * the default value is the one of the forward direction

@jkrivine, @feret, any one ... an opinion?

**Comment by hmedina** [comment]
What does a default rate even mean? Depending on the "scale" of the other rates, it could have dramatic, comparable, or negligible effects... And setting it to the reverse rate would imply arity independence for bimol <-> unimol reactions.

If it defaults to zero, that rule would never happen. KaSim would have no use for it. Would the rate-blind KaSa? It seems like it shouldn't.

**Comment by feret** [comment]
I would vote for correcting the test-suite, and issue an error.
Use the forward rate is I think the worst solution, since if the LHS and the RHS does not have the same number of connected components, it would violate Physics laws. 

Cheers.
Jérôme.

**Comment by feret** [comment]
Which test-case miss backward rates ? 
In kasa_preprocessing, I have rules which no rates at all, which is OK, if the model is not simulated, or ODEified. 
(But we can require that each rule to have a rate is you prefer).

Cheers.
Jérôme.

**Comment by pirbo** [comment]
The easiest is that not providing a rate is a parse error in which case you must provide rates even if you only use kasa.
The alternative is to change the type of a rule in Ast so the the rate become optional, change the sanity checks so that it does not complain if there is no rate and make a specific KaSim check that requires rates.
(I have the patch that add ``` @0``` to all the rules in KaSa test suite so no need to do it yourself, I'll push it if it is OK)

**Comment by feret** [comment]
Dear Pierre,

If we go this direction, I would prefer the patch to put constant 1 for 
missing rates. The point is that I would like to keep the value 0 to stand 
for ignore the rule unless the rate changes.

This is important for automaton abstraction, that gives the set of species 
available according to the mode of the simulations (by mode I means the 
valuations of the variables (that can be changed by perturbations).

Cheers.
(This was also the previous convention: no rate -> rate is equal to 1).

Jerome.


-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by pirbo** [comment]
Since
commit 42ea957f5e4d715fe3549fc415ea8d600f13b601
Author: Krivine
Date:   Wed Sep 28 18:08:47 2011 +0200

the default value was 0.0 not 1 ...

**Comment by feret** [comment]
je pense que les regles de taux 0 ne sont jamais appliquées, non ?
Si c'est bien toujours le cas, il faut donc mettre un dans ces fichiers, et non zero.

Amitiés 
Jerome

**Comment by pirbo** [comment]
Indeed
Pushed with 1 as rate
