### ISSUE TITLE
KaJaSim feature idea: debugging (breakpoints, rule trace, DIM, & story)

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#230]
When debugging a large ruleset, it would be advantageous to pause the simulator. This could be triggered when a particular rule is triggered, or even via perturbations. One could then inspect the reaction mixture (i.e. snapshot) & tokens.

If one could obtain the trace & flux map between breakpoints, it would also inform one of what rules were active since initialization or last pause. Here, the flux map would serve as a summary of the rules & their activity, in addition to graphing their inter-relationships. Having the "draw now" button on the flux map would aid interactivity.

Finally, one could even request the story of the breakpoint. In this case, having the breakpoint-breakpoint trace, defining the breakpoint-rule as the event-of-interest, the IDE would have all the information required to deliver the story (uncompressed by default?).

**Comment by feret** [comment]
You could also imagine having a keyboard shortcut to pause the simulation manually.
Then entering an interactive mode, in which you could apply interactively perturbations from the keyboard. 
Story is not a problem, as long as the trace is logged properly from the beginning of the simulation (which is memory intensive).

Cheers. 
Jérôme.

**Comment by jkrivine** [comment]
It seems you can define all these using the $STOP perturbation no?

**Comment by hmedina** [comment]
Hi @jkrivine , I think using the $STOP would indeed be technically possible, however I don't think it would be user friendly.

Use-case: I see weird trajectories. I would have to abort the simulation, save state to a kappa snapshot (not a potato-diagram one), and go edit the ruleset. How do I trigger a perturbation when a rule is triggered? My first thought would be to create a new flag token to use as a condition for the $STOP perturbation. So I would define the new token, initialize it to zero, add a token++ to the RHS of the rule I'm interested in checking, and add the corresponding $STOP perturbation. Then I'd have to remove all the %inits, and add the snapshot as initial condition, and re-launch the simulation. Assuming I administer my snapshots carefully, I could crawl through multiple invocations of the breakpoint. Similarly, I could add the $TRACK statements, where the flag token also marks the arrest of tracking, and the tracked entity is the RHS of the rule of interest (I'm not entirely sure this would work, but I haven't thought this part through...).

Although quite possible with the current non-interactive tools, I am just suggesting how to make the IDE more user-friendly.

**Comment by pirbo** [comment]
Interactive mode in command line now exists.
The signal you are talking about @feret is Ctrl-c (or SIGINT for the intimate).
Breakpoint are not that trivial to set up but $RUN takes a facultative "pause condition" so by introducing the machinery proposed by @hmedina you can say `$RUN |breakpoint_token| = 1`
The javascript UI just miss the possibility to define a pause condition with all the exprecivity of perturbation. I'll open a distinct issue for that

**Comment by feret** [comment]
Very nice!
But as far as I understand the meaning of Ctrl-c is now contextual. 
During a simulation it pauses the simulation and give the power to the user. 
During the initial phase of story compression (which now longer logs any information to the user, by the way, which makes me wait in front of my screen with no information about what was going on during 1 whole minutes on a small example ???), it interrupts the process. 
During the regular phase of story compression, it stops the current compression phase, and go to the next one, with the stories already computed. 

Is there a way for the user to have the real-time meaning of Ctrt-C ?

**Comment by pirbo** [comment]
Since yesterday, KaSim does not compute stories itself. It dumps the trace in a temporary file and launches KaStor on it. The minute of silence you see is this new phase of printing (by KaSim)/parsing (by KaStor).
The printing phase will disappear next week because KaSim will stream the trace to the file during simulation (and therefore will never have the full trace in RAM).
On the other hand, it might be worth logging "I'm loading the trace in RAM" on the KaStor side!

I don't really get what you have in mind behind the final question. I guess the answer is "You've summed up quite well the behaviour of SIGINT, we should copy this explanation in the refman". I don't have any better idea.

**Comment by feret** [comment]
> Le 4 nov. 2016 à 19:22, Pierre Boutillier <notifications@github.com> a écrit :
> 
> Since yesterday, KaSim does not compute stories itself. It dumps the trace in a temporary file and launches KaStor on it. The minute of silence you see is this new phase of printing (by KaSim)/parsing (by KaStor).
> The printing phase will disappear next week because KaSim will stream the trace to the file during simulation (and therefore will never have the full trace in RAM).
> On the other hand, it might be worth logging "I'm loading the trace in RAM" on the KaStor side!
> 
I am not so sure. 
I have checked the profiling file, there were one minute spent in causal compression, without any message logged. 
> I don't really get what you have in mind behind the final question. I guess the answer is "You've summed up quite well the behaviour of SIGINT, we should copy this explanation in the refman". I don't have any better idea.
> 
> 
Yet, my worry is that is it clear for the user to know which phase is in process. 

Maybe a sentence prompted with the actual status of the engine saying: 
 - Press Ctrl-C to enter interactive mode 
 - Press Ctrl-C to abord the computation (warning no result has been computed so far) 
 - Press Ctrl-C to give up the computation of the next stories, and pursue with the already computed ones. 

What do you think about it ?

**Comment by pirbo** [comment]
Commits that removes logs in stories are:
4bc55e81e5d17a01a2ff2cd615c56f6f9450fe78
5aebe1d72070f28b8482f3b9d5d97f2197e4c14d

**Comment by pirbo** [comment]
Well 1121506b697fbcd0e0835b5b178cf89eee2178bf 
> Commenting any use of formatters.
> -> To be properly changed into access to loggers which can be used according to the environement.
> -> UNderstand what to do with progress bar ? Help needed.
looks like the perfect suspect

**Comment by feret** [comment]
I have restored the logging of stories when launched via KaSim, 
Could you check, @pirbo, that it has no bad side-effect in the other modes ?
