### ISSUE TITLE
KaJaSim bug: "token not found" for snapshots

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#232]
When asking for snapshots, the IDE complains about a "token not found".

Example:
```
%agent: A()
'A' -> A() @ 1.0
%mod: [E]>1 do $SNAPSHOT
```

KaSim will output a file called "snap.ka", while KaJaSim complains about a "token not found". Even if I give the snapshot a name, the error persists.

**Comment by jkrivine** [comment]
The same if I patch the default model and add
%mod: [T]=30 do $SNAPSHOT "t30"

**Comment by hmedina** [comment]
This bug seems to interfere with the ability to plot. The code:
```
%agent: B(b,v)
%agent: C(q,k)
%init: 3 (B(),C())
'Bb.qC' B(b),C(q) <-> B(b!1),C(q!1) @ 1e-2 (1), 1e-4
'Bv.kC' B(v),C(k) <-> B(v!1),C(k!1) @ 1e-2 (1), 1e-4
%obs: '[B]' |B(b,v)|
%mod: [E] = 50 do $SNAPSHOT "snap.ka"
```
With invokation of ``50`` events and ``50`` plot points, fail to generate the plot.
It *does* however produce the snapshot, with the right name. It therefore *is* simulating and reaching event 50, but fails to hand over the plot data...

Worth noting, removing agent C, and rendering agent B self-binding does not elicit this bug.

**Comment by pirbo** [comment]
Should be OK now, reopen if it reappears
