### ISSUE TITLE
KaJaSim bug: contact map doesn't include self-bindings

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#236]
The following code produces a contact map containing a single potato for agent A, with not binding information. When putting the cursor over it, I don't get the amount popup.
```
%agent: A(a)
'o' A(a),A(a) <-> A(a),A(a) @ 1,1
%init: 2 A()
```

**Comment by pirbo** [comment]
This is part of #199

**Comment by hmedina** [comment]
![cm](https://cloud.githubusercontent.com/assets/1588553/17153531/2150ac7e-534b-11e6-86b3-0e5436b8b830.png)
Solved.
