### ISSUE TITLE
Graphical representation of snapshots don't have abundance information

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#240]
The snapshots saved by the IDE don't retain abundance information when outputted to SVG or PNG. That information is available at the IDE when one mouse-overs a species, and a gray text rectangle appears with the abundance of that species. That data are not present if the snapshot is exported as SVG or PNG. See the attached PNG files for comparison.

A screenshot showing the abundance popup:
![capture](https://cloud.githubusercontent.com/assets/1588553/15882285/2a5cbf94-2d0b-11e6-8bef-93178df88a28.PNG)

The export of that same snapshot:
![snapshot](https://cloud.githubusercontent.com/assets/1588553/15882295/3b433658-2d0b-11e6-8400-163a677607df.png)

**Comment by pirbo** [comment]
New rendering has
