### ISSUE TITLE
KaJaSim feature idea: display unary distance distribution

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#241]
When saving the unary distances at which rules trigger, one gets a plot where the X-axis is time, the Y-axis is the distance (in agent number), and every point is the firing of rules using unimolecular rates.

It would be useful to have, additionally, the probability distribution of such distances, annotating mean, mode, standard deviation, etc.

**Comment by pirbo** [comment]
As we need to stay focus on reasonable tasks, Kappa IDE should only deal with things "others cannot do for us". Therefore, I want to argue that this is out of the scope (but I'm of course open to discussion)
For me, Kappa IDE goals are:
 - give access to data KaSim generates (export is the key for me)
 - produce renderings that gives the user glitches of what happen during interactive model construction or simulation run.
It is NOT (yet) the place where you interpret simulation results (maybe it will become later when will be hundreds of devs on the project ;-)).

**Comment by hmedina** [comment]
In suggesting this, I merely thought it was low-hanging fruit. For example, this code:
http://code.runnable.com/U_Xx5lx5j28q1_zv/d3-timeseries-barplot-for-d3-js-and-javascript

generates these nice distributions:
http://code.runnable.com/V3a8s7U7VVx3jA8p/output

**Comment by pirbo** [comment]
Moved to ReConKa
