### ISSUE TITLE
KaJaSim feature idea: toggle rules in unary distance plot

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#243]
In heavily connected models, most binding events will have a unary embedding capacity. This will crowd the tab for plotting unary distances. It would be useful to toggle the rendered rules. If the functionality of the trajectories plot could be re-used (i.e. click label's color to toggle dotted, continuous, or absent rendering), that would solve this issue.

**Comment by pirbo** [comment]
This is now the duty of ReConKa
