### ISSUE TITLE
KaSim bug: init that requires kappa expression's value won't run nor complain

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#249]
The code:

```
%agent: A(s)
%agent: B(s)
'r' A(s),B(s) <-> A(s),B(s) @ 1,1
%init: 1 A()
%init: |A()| B()
```

Seems to run fine, but does not generate an output file, only a blank `profiling.html` file.

```
$ KaSim -i trial.ka -e 5 -o trial.out
+ Command line is: 'KaSim' '-i' 'trial.ka' '-e' '5' '-o' 'trial.out'
Parsing trial.ka...
done
+ Self seeding...
+ Initialized random number generator with seed 540570727
+ Sanity checks
+ KaSa tools initialization
+ Compute the contact map
+ Compiling...
+ Building initial simulation conditions...
         -simulation parameters
         -variable declarations
         -rules
         -perturbations
         -observables
         -update_domain construction
         -initial conditions
+ Building initial state
Done
____________________________________________________________
############################################################
Simulation ended
```

If this code should not run, then an error should be returned. If it should run, then an output file should be printed.

Should the usage of something like

```
%init: 1 A()
%init: |A()| B()
```

be treated like variables? I.e. if `|A()|` has already been initialized, then it has a value, else it has not value and this should be an error? Or should this usage be forbidden, requiring the user declares variables?

**Comment by pirbo** [comment]
Several points here:
1/ No output file: There is neither %plot: nor -p instruction so there is nothing to output and therefore no need to generate trial.out
2/ What does ```%init: |A()| B()``` means? subtle question that should appears in a FAQ.

**Comment by hmedina** [comment]
1/ No output file: I was under the impression at least the first column (i.e. time points) would be plotted. Now that I think about it, I wouldn't know how many plot points would be done: one per event? one per second? Should there be a default number of plot points, say the number of time points? That said, given the above code, you are absolutely right, there is nothing to plot. Perhaps there should be a "warning: requested .out file but no observables to plot" ?

2/ I would think these would be treated like variables. E.g.
```
%init: 1 A()
%init: |A()| B()
```
Would assign an initial condition of 1 copy of B. However:
```
%init: |A()| B()
%init: 1 A()
```
Would throw an "error: amount of pattern A() is unset" (or maybe get a default value of zero?)

**Comment by feret** [comment]
Wait, I thought the order of declaration (except variable definitions) shall not matter (manual page 15).  

Thus the semantics should be a constraint, that is to say:
both:
> %init: 1 A()
> %init: |A()| B()
and:

> %init: |A()| B()

> %init: 1 A()
should mean (in the absence of other introduction of As and Bs) that the number of As and Bs at initial state are the same. 

and the meaning of:
> %init: |B()| A()
> %init: |A()| B()
should be underspecified. 

Which semantics is implemented ? 
Also the manual says that the order of variable declaration matters, but I do not find the definition of the semantics (e.g scoping rules, especially in the case of multi-files models). 

Cheers. 
Jérôme.

**Comment by pirbo** [comment]
I hided the current semantic because I disagree with it :-)
It used to be "values are computed all at once before any introduction" which means every | | expression is evaluated to 0. I liked that.
By mistake, I change it to "values are computed in lexical order with the current state" which violates manual statement and means
> %init: 1 A()
> %init: |A()| B()

inserts 1 B and 
> %init: |A()| B()
> %init: 1 A()

inserts 0 B

Your solution Jerome (if possible) is extremely subtle to implement and I would not go into that direction.

**Comment by feret** [comment]
> Your solution Jerome (if possible) is extremely subtle to implement and I would not go into that direction.
> 
I just meant a topological sort (if acyclic, then well defined, otherwise underspecified). I do not see what is subtle in that solution. 

> It used to be "values are computed all at once before any introduction" which means every | | expression is evaluated to 0.
> 

I like it as well, but I expect a warning when a pattern expression is used to specify the number of protein to introduce. 



By the way, I find it very dirty that the semantics depends on the order in which files are parsed. 
as in:

var1.ka:
%var: 'k’ 1

var2.ka: 
%var: ‘k’ 2

rule.ka:
%agent: A()
%init: 'k' A()

A() -> A() @1 

%obs: 'A' |A()|

I think that KaSim should warn in case of multiple unguarded declarations of variables.

**Comment by pirbo** [comment]
To rephrase the issue: currently `%init foo bar` is syntactic sugar for `%pert: [E] = 0 do $ADD foo bar` and the second one is (legitimately) sensible to the order of declaration (RefMan is wrong see #284)

**Comment by feret** [comment]
You mean in KaSim. 
In KaDe for instance, the programmer has completely ignored perturbations (so far).
And he is interpreting introduction statements and variables declarations/assignments following the 
topological ordering  (thus the semantics  is independent from the order of the instructions).

**Comment by pirbo** [comment]
> And he is interpreting introduction statements and variables declarations/assignments following the 
topological ordering (thus the semantics is independent from the order of the instructions).

Where is the code, we must share it ...

**Comment by feret** [comment]
The first difficulty is that you need the relation between patterns and the (initial) mixtures they occur in. 
The second one is that you need to mix initial states and variables declarations. 

The actual implementation relies on the type network, which you do not want, if you want to use it throughout the engines. 
If you want to go for this semantics (which I recommend), it would be worth providing a clean implementation. 

You may have a look at: 
convert_var_defs
line 734 of odes.ml.
