### ISSUE TITLE
KaJaSim feature idea: display contact map after KaSa removes dead rules

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#250]
The minimal code:

```
%agent: A(a,b)
%agent: B(a)
'A.A+' A(a),A(a) -> A(a!1),A(a!1) @ 1
'A.A-' A(a!1),A(a!1) -> A(a),A(a) @ 1
'A.B-' A(b!1),B(a!1) -> A(b),B(a) @ 1
%init: 10 A(), B()
```

Produces a contact map where there is a bond between agents `A` and `B`. However, KaSa clearly knows rule `A.B-` is dead. KaJaSim should therefore have an option to display the "effective" contact map, in addition of the raw one.

In the context of Kami, where dead rules are produced en masse, this would enhance readability of the contact map.

**Comment by feret** [comment]
Dear Hector, 

At the moment, no effort has been put to interface KaSa with the rest of the Kappa galaxy. 
This feature is obviously in the stack, but it is not available yet. 

Also not sure that analysing the result of Kami compilation is the appropriate pipeline. 
We may have scalability issue (in the compilation), if too many spurious rules are generated, an analysis beforehand would avoid this. 

Cheers. 
Jérôme.

**Comment by hmedina** [comment]
So you would suggest analyzing the result of the LCG-to-Kappa compilation with KaSa? That sounds like low-hanging fruit for @abassobl et al.

**Comment by feret** [comment]
What I suggest is to have a Kami front-end, so that we can analyse models before their compilation into Kappa.

**Comment by pirbo** [comment]
The `High` accuracy of contact map in the UI is exactly that, isn't it?

**Comment by hmedina** [comment]
I wouldn't know: the meaning of 'accuracy' for the contact map is not
documented in the manual.

On Thu, Aug 10, 2017 at 4:03 PM, Pierre Boutillier <notifications@github.com

**Comment by pirbo** [comment]
> The High accuracy of contact map in the UI is exactly that, isn't it?
It is
