### ISSUE TITLE
create validate svg for snapshots

### ISSUE THREAD

**Issue by majorseitan** [Kappa-Dev/KaSim#254]
1. The svg export of snapshots can not be opened in editor.
2. The svg export of snapshots is not valid svg.

**Comment by majorseitan** [comment]
1. Verified that snapshot svg's can be opened in illustrator.
2. Verified that snapshot svg's can be validated by w3c
    https://validator.w3.org
    *Note* the doc type has been specified so it will autodect the character encoding and the document type.

**Comment by hmedina** [comment]
The SVG file is now validated and plays nicely with Illustrator.
