### ISSUE TITLE
KaSa scheduler is too coarse grain

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#275]
The following should be done:
if the potential state of a tuple t of sites is modified, 
every rule that test/mod a tuple t' of sites such that t & t' have a non empty overlap should be put in the working list. 
Until this is done, the final result might not be a post-fixpoint.

**Comment by lykimquyen** [comment]
Solved by f32c6d2d7b06162a19d74415d9bcd8eed9bfd74b
