### ISSUE TITLE
Could we use http://www.webgraphviz.com/ to display stories?

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#285]
It may have been suggested already, but it could be a good way to render stories within the web app.

**Comment by feret** [comment]
AIV students had problem displaying (not so big)-stories with webgraphviz. 
Also, I thought it was the purpose of the HTML/SVG output of stories, why not using it ?

**Comment by pirbo** [comment]
The problem is not there. The issue was to get a story extractor that can return its results elsewhere than directly on files on hard drives. @feret has done its part of the job, I'll do mine very soon.
