### ISSUE TITLE
Manual missing content: --interactive is undocumented

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#290]
The [KaSim & KaSa reference manual](http://dev.executableknowledge.org/docs/KaSim-manual-master/KaSim_manual.htm) does not document the usage of the interactive mode.

As a side note, are the usages of `--interactive` in the command line, and the perturbation bar in the Javascript simulator expected to converge? E.g. could I type `$RUN 5` into KaSimWeb and run for 5 additional seconds?

**Comment by pirbo** [comment]
`--interactive` is now `-node interactive` and is mentioned in the refman
