### ISSUE TITLE
Websim bug: plot stop after approximatively 25.000 points

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#297]
It seems the frequency at which one is taking points for the curve induces a premature termination of the plotting deamon.
To reproduce:
from the abc basic model online ask time limit = 1000
and pp = 0.1 
simulation seems to stop at t=255
This is reproducible with any model that asks more than 25.000 points

**Comment by pirbo** [comment]
Indeed the browser says: `RangeError: Maximum call stack size exceeded`.
@majorseitan will argue that the UI is not expect to deal with that many values and that the issue is in the design of the API which should not provide queries whose reply are that big...

**Comment by jkrivine** [comment]
One needs some kind of a sliding window where old points are discarded ?

**Comment by pirbo** [comment]
Tested
Thank you!
