### ISSUE TITLE
plot_period for events

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#298]
I see that you changed API and now I have to provide plot_period. When I limit the time of the simulation I can predict how many plot points I will get. 
But when I limit the event number then it plots me according to time (not events), so it is hard for me to predict how many plot points I will eventually get. It would be nice to have an ability to either be able to set events_plot_period or to choose between plot period and number of points per simulation.

**Comment by hmedina** [comment]
It seems to me plot periodicity should be in the units of the simulation
invocation: plot points per simulated second if launching with time units,
or events between points if launching with a number of events.
Thus a simulation of 200 events with periodicity 10 would have 20 plot
points.

Obviously, if using events then periodicity should be greater than or equal
to one, and probably an integer.

**Comment by antonkulaga** [comment]
@hmedina +1

**Comment by pirbo** [comment]
And if you provide both?

**Comment by feret** [comment]
Disjunction is always conservative… 
If you have both, why not plotting if the condition on time OR the condition on event is satisfied ?

**Comment by hmedina** [comment]
If the user gives both a period (points per second) and a frequency (events
per point), I would think the user is requesting two distinct indexes, ergo
outputs. I would give two outfiles, one for the period the other for
frequency. E.g.

$KaSim -i foo.ka -pp 10 -op periodic.out -pf 0.5 -of frequent.out

(If two characters per option is maybe too terse, you could use a Jérômian
namespace ;)

If the user gives two end clauses, as Jérôme suggests, I would expect to
terminate when the first is realized.

**Comment by pirbo** [comment]
Because I don't want to multiply the option and because the conclusion of a recent discussion about the ui has been "you never want to specify both max_time and max_event". Let me propose solution (1): providing 3 new command line options:
-l (this is a L non capital) to specify a limit to the simulation (default is None)
-pp to specify the plot period of the plot (default is 1)
-u to specify the unit in which you are talking (default is time alternative is event)

I sum up currently implemented solution (2) (which is a bit more in the continuity of the past):
-t for max_time
-e for max_event
Simulation stops when one of them is reached
-pp for plot period in time unit (default 1. and 0 means no plot)
(deprecated -p that when -pp is not given but -t is sets plot period to max_time / nb_points)
No command line option for plot_period in event but the possibility to say in your model
```
%mod: repeat [E] [mod] 'ppe' = 0 do $PLOTENTRY until [false]
```

Please vote!

**Comment by hmedina** [comment]
So:
``$KaSim -i m.ka -l 10 -pp 0.1 -u hours``
Would simulate 10 hours and plot 100 plot points?

``$KaSim -i m.ka -l 10 -pp 0.1 -u events``
Would produce a simulation with 10 events, and 100 plot points? (if `-u events` I think `-pp` should be forcefully an integer, or throw a warning if not)

``$KaSim -i m.ka -l 10 -pp 10 -u seconds``
Would simulate 10 seconds and plot 1 point?

I'm fine with this behavior.

**Comment by pirbo** [comment]
KaSim does not count in term of second, it counts in term of arbitrary time unit... So there won't be seconds, minute, hours, what ever choices. There will be literally only 'time' or 'event'.
I can make `-l 10 -pp 0.1 -u events` works as you suggest but it is completely useless so I would go for failing if -pp or -l is not an integer in event mode

**Comment by hmedina** [comment]
Fully agree: fail in event mode if options are non-integers.

Side-note, is 0 an integer? What would ``-pp 0`` do? What would ``-l 0`` do, would just parse?

**Comment by feret** [comment]
For teaching purpose, it would be nice if backward compatibility is ensured. 
It is quite a difficult task to ensure that all intervenants have their slides up-to date with the last 
version of the command-line options. 

Would it be possible to also support for the previous options ? 
It is OK if they are removed from the manual and the help list, but I would recommend that their behavior is maintained. 

I use the classification Hidden for command line options that are either obsolete but maintained for backward compatibility, or 
in the edge of the current development.

**Comment by feret** [comment]
OK we should use positive number (at least for frequency) then. 
But the English terminology is quite confusing for French people (at least for me). 
I really prefer the French word-to-word translation: strictly positive number. 

If we use non negative number. 0 could mean: do not simulate for -l; 
or plot each change of the state for the frequency.

**Comment by rhz** [comment]
I prefer option (1). I think it's more consistent. Regarding backwards compatibility, perhaps the old options could be accepted but given a warning with indications on how to use the new options?

**Comment by pirbo** [comment]
Backward incompatible option -u(nit) -l(imit) -p(lot_period) has been implemented! Teaching material will have to be updated, sorry ...
-l 0 indeed means just parse
-p 0 means do not print anything (well you can still use $PLOTNOW)
-u event KaSim takes the `int_of_float (floor v)` of -l `v` and -p `v`.

Please reopen if you're not happy.

**Comment by feret** [comment]
This is very nice. 
Yet I still think that when changes like this are made. Former options should be supported even if they disappear from the documentation. Or at least, a message should be prompted to say that this option is obsolete, while proposing the new command line.
At least, it would spare me from receiving phone call to tell me that KaSim is broken. :-)

**Comment by pirbo** [comment]
Right, I'll reintroduce them back ... (For my defence, this break should have been announced yesterday on the googlegroups but it has been lost in a blackhole ...)
