### ISSUE TITLE
data-base of simulations?

### ISSUE THREAD

**Issue by vd1** [Kappa-Dev/KaSim#30]
here is an idea: when running a simulation it would be nice to have an option to get an archive of 1) all the files used, 2) the command line used and even possibly 3) the output files themselves - to guarantee the _replayability of the simulation_

a simpler version of this idea is to give as a default long name for an output file the command-line that generated the file - with an additional number to distinguish it from the previous ones 

in both cases the intention is to make it simpler, when one works with different variants of a model, to map result files to variants of the model and conditions in which they were produced (aka the context of the simulation)

to go a little further, we could have an entire data-base of models and simulations - which we could interact with by scripting (I know MLstate has done some work on this perhaps we should ask them?)

**Comment by pirbo** [comment]
I tag long-term but in fact we're getting there slowly with the UI...

**Comment by pirbo** [comment]
I think we are there.
Each run of KaSim now generates (in the directory of outputs) a file named inputs.ka that contains all you need to EXACTLY reproduce the simulation you're running.
Moreover, this file starts by a uuid that uniquely characterize this run of the simulation and all files generated during this run contains somewhere the same uuid. Therefore if
- you have a file and you want to know how it has been generated look for the inputs.ka that contains the uuid 
- you have an inputs.ka file and you want to find all the files it generates, `grep the_uuid`

KaSim does not produce an archive with everything by itself (it could but it adds a dependencies and users hate extra dependencies) but we are at 1µm of that: do `KaSim -d /tmp/outputs && zip -r my_simulation /tmp/outputs` and you've got a self contained archive of a run of a simulation.

 Is that what you expected (6 years ago !!!!!! (wouhaaaaa))?

**Comment by vd1** [comment]
Exactly! I am shouting of joy like a little rabbit hunting carrots in the
fields.

**Comment by pirbo** [comment]
Good!
