### ISSUE TITLE
no output in last build of KaSim

### ISSUE THREAD

**Issue by glucksfall** [Kappa-Dev/KaSim#300]
Hello,

I downloaded the last version of branch master and try it. However, the program doesn't write and output file with `-o` option. Even without `-o` option, the program doesn't write the data.out file as usually did it.

Thank you for your time.
Best regards.

**Comment by pirbo** [comment]
Weird ... 
How do you launch KaSim? Do you give a `-t` or a `-e`? Are you aware that `-p` has been replaced by `-pp` (see #298, the debate on this change is not closed)? Is there `%plot:` (or `%obs:) in your model?

**Comment by glucksfall** [comment]
I wasn't aware of `-p` changed into `-pp`. I doesn't tested the new way of calling because my machine still is running a bunch of simulations.

Thanks again for your help.
