### ISSUE TITLE
Document scope of unimolecular rate in dual-rate notation

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#301]
The manual does not document the usage of the scope parameter given to unimolecular rates when using the dual-rate notation. Concretely, this would be parameter `n` in:
```
'k' A(a),B(b) <-> A(a!1),B(b!1) @ 'k+1' ('ku':n), 'k-1'
```

**Comment by pirbo** [comment]
Thanks to @icristescu, there is a line mentioning horizon at http://dev.executableknowledge.org/docs/KaSim-manual-master/KaSim_manual.htm#x1-290003.4.4
