### ISSUE TITLE
NaN values results in blank simulation plots

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#307]
if a variable is initialized to NaN at the beginning of a simulation, the plot tab remains blank with no error message

**Comment by pirbo** [comment]
Please give an example of a problematic model

**Comment by jkrivine** [comment]
Try
%obs: 'x' 12/0

Le 22 novembre 2016 17:09:26 GMT+01:00, Pierre Boutillier <notifications@github.com> a écrit :
>Please give an example of a problematic model
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kappa-Dev/KaSim/issues/307#issuecomment-262283931

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
