### ISSUE TITLE
token $init and %mod conflict

### ISSUE THREAD

**Issue by glucksfall** [Kappa-Dev/KaSim#308]
Hello,
I found an error, probably regarding modification execution. I simulated the following model with Kappa Simulator: 3.5-250915. However, using Kappa Simulator: DomainBased-2269-g417fb2d-dirty, there is an `Not_found` error after `Building initial state`. When the %init: f6p is changed to 1 or other value, the model run perfectly in the last build.

Note: the %mod are unnecessary, and without them the original code runs without errors.

```
%token: g6p
%token: f6p

%var: 'on_rate' 1

%init: g6p <- 1000
%init: f6p <- 0

'pgi' |1:f6p <-> |1:g6p @ 'on_rate'*|f6p|,'on_rate'*|g6p|

%obs: 'obs_g6p' |g6p|
%obs: 'obs_f6p' |f6p|

%mod: repeat (|g6p| < 1 do (g6p <- |g6p|+1 ; f6p <- |f6p|+-1)) until [false]
%mod: repeat (|f6p| < 1 do (f6p <- |f6p|+1 ; g6p <- |g6p|+-1)) until [false]
```

**Comment by pirbo** [comment]
The issue is that `f6pù  becomes negative and therefore the rate `'on_rate'*|f6p|` become negative which is forbidden ... It raises a good question of what to do in such case ...

**Comment by hmedina** [comment]
How could the f6p token become negative? There's only one rule that
decreases it's value, and that rule requires a value greater than zero to
trigger (unless rates of zero contribute non-zero activities...)
