### ISSUE TITLE
Files exported by the UI should indicates the random seed used

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#309]
KaSim does that (but it is easier for it :-))

**Comment by hmedina** [comment]
The `.csv` time-traces are printed with the seed, as do the reproducibility files `inputs.ka` so, what's missing? Should snapshots, traces, or maps have the seed also?

**Comment by pirbo** [comment]
Seed is printed in the log by the UI as well as it is written in the inputs.ka generated by "all outputs". This is already a good improvement.
