### ISSUE TITLE
Update Kappa reference articles URL in manual

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#311]
In the reference manual as on your webpage the url for the reference papers about Kappa are http://www.pps.univ-paris-diderot.fr/~danos/pdf/eov.pdf but these does not exist anymore and http://di.ens.fr/~danos/pdf/eov.pdf does not work

**Comment by pirbo** [comment]
@feret @jkrivine Do you know where these articles can be found?

**Comment by feret** [comment]
The following link seems to work: 
http://aip.scitation.org/doi/abs/10.1063/1.2836156

:-)

**Comment by pirbo** [comment]
It is not open access, is it?

**Comment by feret** [comment]
Argh you are right. 
It must have been opened by my proxy. 
This version seems to be in open access: 
https://www.researchgate.net/publication/220370216_Agile_Modelling_of_Cellular_Signalling_Invited_Paper
