### ISSUE TITLE
Make explicit in the UI  a succesfull modification

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#312]
When you ask interactively in the UI for $SNAPSHOT or $PRINT, you see it but there is no sign that your $ADD or $DEL or $FLUX has been proceed.

My idea would be to generate a log of the performed perturbations. Something that when you have paused at [T] = 524.7351 and successfully $ADD 150 X() would print:
```
%mod: [T] = 524.7351 do $ADD 150 X()
```

**Comment by feret** [comment]
It would be excellent.

**Comment by hmedina** [comment]
Why not use the log tab that sits next to the editor and displays the KaSim stdout? That would also mimic the use of ``-mode interactive``.
Additionally, for quick perturbations of the type ``$ADD``, we could display a green check-mark next to the Perturbation box for success and a red cross for error. If nothing shows up it means nothing happened.

**Comment by jkrivine** [comment]
I support this idea because currently one has no feedback whether the perturbation was applied, so one is tempted to click several times on the perturbation button. Would it be possible to display a message to the user like "pertubation applied"
