### ISSUE TITLE
KaJaSim control box layout could be improved for narrow windows

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#314]
![capture](https://cloud.githubusercontent.com/assets/1588553/20812745/b7650a62-b7e0-11e6-92ba-4b0bd06e83aa.PNG)

If the window is narrow or resized, the buttons start blocking each other, even though there is still ample space in their box.

**Comment by pirbo** [comment]
This is a pure bootstrap grid issue and a question of what we do in .col-sm- and .col-xs- mode
