### ISSUE TITLE
KaSim "exit status 3221225477", aka Windows access violation, from node (?!)

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#324]
I'm running KaSim 0c676cf locally on Windows10 through Python's [``subprocess.run``](https://docs.python.org/3.5/library/subprocess.html#subprocess.run) method. Around 1/10 tries, I get an error:
```
+ Self seeding...
+ Command line to rerun is: 'KaSim' '-i' 'results/2016_12_15-00_56_19/0/1.ka' '-o' 'results/2016_12_15-00_56_19/0/1.csv' -seed 19485291
Parsing results/2016_12_15-00_56_19/0/1.ka...
done
+ Sanity checks
+ Compiling...
+ Building initial simulation conditions...
         -simulation parameters
         -variable declarations
         -rules
         -perturbations
         -observables
         -update_domain construction
         34 (sub)observables 8 navigation steps
         -initial conditions
+ Building initial state
Done
____________________________________________________________
Traceback (most recent call last):
  File "./SALib_test_local_launcher.py", line 104, in <module>
    main()
  File "./SALib_test_local_launcher.py", line 84, in main
    subprocess.run(worker_exec_command, check=True)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'KaSim -i results/2016_12_15-00_56_19/0/1.ka -o results/2016_12_15-00_56_19/0/1.csv' returned non-zero exit status 3221225477
```
I have no idea what exit status 3221225477 could be. After some Googling, here's my best:

A similar circumstance has been reported [here](https://github.com/sass/node-sass/issues/1283#issuecomment-169450661). It would seem ``3221225477`` is actually a ``(0xC0000005)`` access violation. And this has been tied to [nodejs](https://github.com/nodejs/node/blob/842e5a10ac59c826f875ef79e92d144e2655cc9a/test/common.js#L502-L505). If this all holds, the what is the nightly built Windows executable KaSim.exe doing with nodejs? I thought only KaBrowserSim used nodejs...

**Comment by pirbo** [comment]
Do you still have (and can yu send me) the python script that raises that?

**Comment by pirbo** [comment]
"Access violation" is the windows© for "segfault". This is indeed an instance of #325.
