### ISSUE TITLE
csv output file title line is incompatible with kappa expression

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#327]
If you try to `%plot: |A(x!1), B(x!1)|` and  say `%plot: 'foo'` title line of the output file will be
```
# [T], |A(x!1), B(x!1)|, 'foo'
```
which is understood by csv parsers as "this file has 4 columns `[T]`, `|A(x!1)`, `B(x!1)|` and `'foo'`".

**Comment by hmedina** [comment]
When parsing a CSV, functions (at least in Python & MatLab) allow one to
re-specify the quote character, including to the pipe symbol.
