### ISSUE TITLE
We can now longer interrupt a story compression.

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#329]
Ctrl-C was used to interrupt a given compression, and go directly to the following ones. 
Now, when used during story compression, it kills KaSim.

(I guess that Ctrl-C is sent directly to KaSim, and not handled by KaStor). 

Any idea about how to restore the proper behavior ?

**Comment by pirbo** [comment]
Fix was easy but it won't work under windows where processes cannot send signals one to an other...

Anyway, I've originally implemented the KaSim launches KaStor trick as a compatibility layer.
My idea was to deprecate the use of `%def: "displayCompression"` and to say to users: generating stories requires 3 steps.
- add some $TRACK in your model
- run `KaSim -trace thisisatrace.json -l ...`
- run `KaStor --weak thisisatrace.json`

**Comment by hmedina** [comment]
If you give me a test, I can run it under the Linux subsystem and find out.

**Comment by feret** [comment]
Great thank you @pirbo .
