### ISSUE TITLE
Problem with the slider when too many points are ploted

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#332]
I label as critical because there is no workaround, I don't mean to be rude ;)

To observe the bug (default ABC model)
- Set the pause condition to T> 1000
- run the simulation. After 240s the slider appears but the curve is no longer plotted. Pausing the simulation does not allow one to see the beginning of the plot either.
(On chrome OS x)

**Comment by majorseitan** [comment]
I was able to replicate and working on a fix.

**Comment by majorseitan** [comment]
@jkrivine I have pushed at patch addressing this problem let me know if this addresses your ticket without introducing additional issues.
@pirbo @jkrivine I leave it to you both to close this ticket.

**Comment by jkrivine** [comment]
Looks OK now!
