### ISSUE TITLE
Snapshot export is broken

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#334]
(critical bug because no workaround)
To reproduce: pause the default ABC simulation.
Type the perturbation
$SNAPSHOT "foo"
On the snapshot tab ask for an export to foo.svg and a window appears with the message:
`TypeError: cannot read property 'outerHTML of null'

**Comment by pirbo** [comment]
Snapshots in svg are really work in progress.
Do you manage to read and understand them? In my case, simply rendering them crash most of the time. 
You really want to export snapshots in svg? Exporting in kappa works well on the contrary.

**Comment by hmedina** [comment]
Potato diagrams of medium-to-large mixtures are massive files and difficult
to render; I would suggest the patchwork layout instead, which scales much
better to medium mixtures.

Patchwork is broken in KaWebSim because of
https://github.com/Kappa-Dev/KaSim/issues/292 but KaCommandLineSim doesn't
have this issue.

**Comment by jkrivine** [comment]
Hi Pirbo
What do you mean by exporting in Kappa? the text Kappa file? Yes I agree it's the most important feature.

To answer your question, the svg (or any image file) format is useful for teaching purpose!
But anyway I suggest to remove the svg export if it is buggy because we want a clean release for KaSim 4.0.

**Comment by pirbo** [comment]
In the export `<div>`, before the filename `<textarea>`, you've got a format `<select>`. By default, it is 'svg' which is broken but if you select 'kappa', it will work.

**Comment by pirbo** [comment]
This is now #337
