### ISSUE TITLE
KaDE is broken.

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#338]
Some logging information has been put in octave (.m) and sgml file (.xml). 
These files have a rigid structure since they have to be interpreted by other tools. 
Please use a specific logger to log information you need: 

Please log your instrumentated log on the standard output: 
  let () = Format.printf "\t -main function @." in
  
Or open your own logger: 

  let out_channel =
      Kappa_files.open_out "my_logger.txt"
    in
    let logger = Loggers.open_logger_from_channel  out_channel in

**Comment by lykimquyen** [comment]
bf90f09ab495db9e90cd44854c86ff8024075a5b

**Comment by lykimquyen** [comment]
Solved
Commit :  bf90f09ab495db9e90cd44854c86ff8024075a5b
