### ISSUE TITLE
make all not working

### ISSUE THREAD

**Issue by vd1** [Kappa-Dev/KaSim#347]
i am trying to compile KaSim and i get the following:

celodv:KaSim V$ ocaml --version
The OCaml toplevel, version 4.04.0
celodv:KaSim V$ make all
"ocamlbuild"  -I KaSa_rep/lib/light KaSim.native
Finished, 0 targets (0 cached) in 00:00:00.
+ ocamlfind ocamlc -c -g -bin-annot -safe-string -w A -package str -package num -package unix -package yojson -I term -I util -I siteGraphs -I simulation -I odes -I main -I KaSa_rep -I grammar -I generated -I Error -I dataStructures -I cflow -I KaSa_rep/tools -I KaSa_rep/symmetries_analysis -I KaSa_rep/sanity_test -I KaSa_rep/reachability_analysis -I KaSa_rep/pipeline -I KaSa_rep/main -I KaSa_rep/lib -I KaSa_rep/influence_map -I KaSa_rep/export -I KaSa_rep/error_handlers -I KaSa_rep/data_structures -I KaSa_rep/counting_enumeration -I KaSa_rep/config -I KaSa_rep/backend -I KaSa_rep/automatically_generated -I KaSa_rep/lib/light -I KaSa_rep/frontend/preprocess -I KaSa_rep/data_structures/mvbdu -o term/pattern.cmi term/pattern.mli
findlib: [WARNING] Interface operator.cmi occurs in several directories: dataStructures, term
File "term/pattern.mli", line 1:
Error: term/operator.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Command exited with code 2.
Compilation unsuccessful after building 34 targets (33 cached) in 00:00:00.
make: *** [KaSim.native] Error 10

**Comment by pirbo** [comment]
You did not update in a while, right?
`make clean` and then `make all` will work...

**Comment by vd1** [comment]
thanks! it works perfectly now.
