### ISSUE TITLE
Simulations not replicables between KaSim versions

### ISSUE THREAD

**Issue by glucksfall** [Kappa-Dev/KaSim#348]
Hello, 

I have this strange situation:
I have done a bunch of simulations in a server with `KaSim DomainBased-2393-gd69ddb6-dirty` and in the desktop pc with the updated version `KaSim DomainBased-2659-g82aaa2b-dirty`. The obvious difference is the input file written to the working path, a less obvious difference was the name of observables (`[T]` becomes `"[T]"`, `'obs1'` becomes `"obs1"`), but I noted a difference in simulation trayectories (yes, I give the same seed to correctly compare).

For example, a simulation in 2659 gives me:
`0., 7, 1, 1, 34, 1930, 0, 0, 24, 129, 195`
`1., 2, 0, 1, 13, 237, 0, 0, 9, 66, 444126`

but in 2393 the output was:
`0., 7, 1, 1, 34, 1930, 0, 0, 24, 129, 195`
`1., 1, 0, 1, 29, 1576, 0, 0, 17, 49, 249`

So... well... I don't know

**Comment by pirbo** [comment]
Check that you have the same version of OCaml (`ocaml -version`) on the server and the desktop (OCaml has changed its random number generator for security question). If yes, we've got an issue and I would be interested by having more information about your model...

**Comment by glucksfall** [comment]
In the server `ocaml -version` gives me `The OCaml toplevel, version 4.01.0` and in the desktop `The OCaml toplevel, version 4.02.3`.

**Comment by pirbo** [comment]
So yes the random number generator has changed between the 2 versions. Therefore, the same seed produces 2 different sequences... You can make the test on your desktop. You `git checkout gd69ddb6` then `make` then `bin/KaSim your_model -seed your_seed` and you should see
```
0., 7, 1, 1, 34, 1930, 0, 0, 24, 129, 195
1., 2, 0, 1, 13, 237, 0, 0, 9, 66, 444126
```

**Comment by glucksfall** [comment]
(Your response come just right when replying this)

I re-compiled KaSim 2393 with `ocaml -version 4.02.3` in the server, launched again a simulation giving the exact results as previously done (sorry, I don't remember how I compiled KaSim in the server, I think just copied compiled from the desktop because it can be compiled with ocaml 4.01.0). So, I cloned the last build 2678 in the server, compiled and the result is (very) different compared to the version 2393.

So... My concern now is, which simulation is correct? because there are a world between them

**Comment by pirbo** [comment]
I'm lost.
On 1 given machine, with 1 given ocaml version, the result of 2393 and 2659 are different. If so, there is an issue in KaSim.
I have an other issue: the version you use are not directly taken from commits from the github repo else 
https://github.com/Kappa-Dev/KaSim/commit/gd69ddb6 and https://github.com/Kappa-Dev/KaSim/commit/g82aaa2b would send us to the corresponding commits. Do you add your own commits? (`-dirty` also indicates that you have edited stuff on your own)
Can you tell me at what github commits your 2393 and 2659 correspond. I cannot try to guess what have occured in between the 2 else.

**Comment by glucksfall** [comment]
I'm more lost about this... I don't modify anything, I don't know OCaml. I just `git pull`, `make clean` and `make all` to install KaSim.

The version 2393 is the commit [d69ddb6](https://github.com/Kappa-Dev/KaSim/commit/d69ddb6) and version 2659 is the commit [82aaa2b](https://github.com/Kappa-Dev/KaSim/commit/82aaa2b) (without the not so obvious first g; I'm feeling more TOC this day).

**Comment by glucksfall** [comment]
Ok... The issue just dissapeared. I re-installed all, and now there is a little difference of one unit of an observable, so I think now they are identical simulations.

```
==> 2393.out.txt <==
# Output of 'KaSim' '-i' 'model.ka' '-l' '100' '-p' '1' '-seed' '495674475' '-o' '2393.out.txt'
[T], 'lacZ_RNA', 'lacY_RNA', 'lacA_RNA', 'lacI_RNA', 'rne_RNA', 'lacZ_Prot', 'lacY_Prot', 'lacA_Prot', 'lacI_Prot', 'Rne_Prot'
0., 7, 1, 1, 34, 1930, 0, 0, 24, 129, 195
1., 1, 0, 0, 12, 372, 0, 0, 12, 65, 680
**2., 0, 0, 0, 2, 43, 0, 0, 6, 22, 318**
3., 0, 0, 0, 0, 6, 0, 0, 1, 10, 120
**4., 0, 0, 0, 0, 0, 0, 0, 0, 3, 44**
**5., 0, 0, 0, 0, 0, 0, 0, 0, 3, 19**
6., 0, 0, 0, 0, 1, 0, 0, 0, 0, 10
7., 1, 1, 1, 1, 1, 0, 0, 0, 0, 2
8., 0, 0, 0, 0, 0, 0, 0, 0, 1, 4
9., 0, 0, 0, 0, 0, 1, 0, 1, 0, 3
10., 1, 1, 1, 0, 0, 0, 3, 1, 0, 2
11., 2, 2, 0, 0, 0, 4, 5, 4, 0, 0
12., 1, 0, 0, 0, 1, 3, 6, 6, 1, 1
**13., 1, 1, 0, 0, 1, 1, 9, 7, 0, 2**
14., 1, 0, 1, 1, 0, 2, 13, 8, 0, 1
15., 0, 1, 0, 2, 0, 6, 16, 10, 2, 0
16., 0, 0, 0, 1, 0, 8, 13, 14, 0, 0

==> 2659.out.txt <==
# Output of 'KaSim' '-i' 'model.ka' '-l' '100' '-p' '1' '-seed' '495674475' '-o' '2659.out.txt'
# "uuid" : "673499002"
"[T]", "lacZ_RNA", "lacY_RNA", "lacA_RNA", "lacI_RNA", "rne_RNA", "lacZ_Prot", "lacY_Prot", "lacA_Prot", "lacI_Prot", "Rne_Prot"
0., 7, 1, 1, 34, 1930, 0, 0, 24, 129, 195
1., 1, 0, 0, 12, 372, 0, 0, 12, 65, 681
**2., 0, 0, 0, 2, 43, 0, 0, 6, 22, 319**
3., 0, 0, 0, 0, 6, 0, 0, 1, 10, 120
**4., 0, 0, 0, 0, 0, 0, 0, 0, 3, 45**
**5., 0, 0, 0, 0, 0, 0, 0, 0, 3, 20**
6., 0, 0, 0, 0, 1, 0, 0, 0, 0, 11
7., 1, 1, 1, 1, 1, 0, 0, 0, 0, 3
8., 0, 0, 0, 1, 0, 0, 0, 0, 1, 4
9., 0, 0, 0, 0, 0, 1, 0, 1, 1, 3
10., 0, 0, 0, 0, 0, 0, 3, 1, 0, 2
11., 2, 2, 0, 0, 0, 4, 5, 3, 0, 0
12., 1, 0, 0, 0, 1, 4, 6, 6, 1, 1
**13., 1, 1, 0, 0, 1, 1, 9, 6, 0, 2**
14., 1, 0, 1, 1, 0, 2, 12, 8, 0, 1
15., 0, 1, 0, 2, 0, 6, 15, 10, 2, 0
16., 0, 1, 0, 1, 0, 8, 13, 14, 0, 0
```

**Comment by pirbo** [comment]
yes, this difference of 1 is expected (this is the fix of #330 by https://github.com/Kappa-Dev/KaSim/commit/434c3fea9307c4582d6182253782e04a956a40e3).
Thank you for taking the time to make all these tests.

**Comment by feret** [comment]
Maybe could we add a command-line option just to show the beginning of the stream of « random » numbers for a given seed. 
It could help figuring out more easily whether potential differences come from Ocaml versions, or from a potential bug. 

Cheers. 
Jérôme.

**Comment by glucksfall** [comment]
Oh @pirbo , don't worry. I should thank you for your help.

Best regards
