### ISSUE TITLE
Float logger issue in KaDE

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#352]
Take the `silly` model
```
%var: 'VSynechococcus'   2.8E-09
```
Run `bin/KaDE silly.ka --ode-backend Octave`. The var declaration has been translated into
```
var(1)=0.000000;
```

It is probably as easy to fix as replacing a `%f` by a `%g`. (if Matlab understands correctly floats printed by OCaml in the style d.ddd e+-dd)

**Comment by feret** [comment]
fixed in cb031755568212ae205427f988c6358c70f98a97
I have tested the octave output. 
I need to test in Matlab and CellDesigner...

It would have been even better if I had access to the original string instead of the float conversion.
