### ISSUE TITLE
Can't specify folder name in snapshot file-name?

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#358]
This mod line triggers `Sys_error("snapshots/linear_polymer_snap.ka: No such file or directory")`:
``%mod: [T] > 10 do ( $SNAPSHOT "snapshots/linear_polymer_snap.ka" ; $STOP )``
While this mode line works fine:
``%mod: ([T] > 10) do $SNAPSHOT "linear_polymer_snap.ka"; $STOP ``

I was under the assumption KaSim would create the folder if it did not exist already (which in my case it does). One should be able to specify a folder to dump the snapshot (hopefully not through the use of an additional `%def: snapshotFolder "folder"`... )

For reproducibility, here's the model:
```
%agent: A(n,m)
'r' A(n),A(m) <-> A(n!1),A(m!1) @ 1.0e-4 {0},1.0e-2
%init: 1.0e3 A()
%mod: [T] > 10 do ( $SNAPSHOT "snapshots/linear_polymer_snap.ka" ; $STOP )
```

KaSim version ``Kappa Simulator: DomainBased-2750-g191c0a3``

**Comment by pirbo** [comment]
How should this interact with the `-d`option? If I launch your example with `-d ../outputs`, do you expect `linear_polymer_snap.ka` to be in `snapshots/linear_polymer_snap.ka` or in `../outputs/snapshots/linear_polymer_snap.ka` (or in `../outputs/linear_polymer_snap.ka`)?

**Comment by hmedina** [comment]
With ``-d foo`` I would expect **all** outputs to be under that directory. Therefore, I would expect a snapshot named ``bar/baz.ka`` to end up in ``./foo/bar/baz.ka``. To have snapshots "break free" of this behavior, I would name the snapshot ``../bar/baz.ka``, so it doesn't end up in ``foo``.
