### ISSUE TITLE
Grammar for expressions is too restrictive. 

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#359]
%var: 'k' ((2+3-5)*3+12/12*4)

File "essai.ka", line 1, characters 6-17:
Illegal definition of variable 'k'

This expression should be valid, shouldn't it?

**Comment by pirbo** [comment]
2 issues here:
- Kappa parser does not understand the implicit `*` between parenthesis but programming language often don't so I think it is OK to ask for `%var: 'k' ((2+3-5)*3+12/124)`
- We are bitten by the super common parser problem unary minus vs binary minus ... `2+3-5` is parsed `(2)+(3)(-5)`. That's a real issue!

In the end, you would have to write for now: `%var: 'k' ((2+3- 5)*3+12/124)`

**Comment by feret** [comment]
Oups, sorry my mistake. 
The * somehow disappear in my copy paste. 

I fully agree on the first point. 
For the second point, well at least as a temporary solution I now know where to add spaces. :-)
