### ISSUE TITLE
Improvement: allow "column" text edition

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#360]
Advanced code editors allow one to select / edit text "column-wise", e.g. in Notepad++ one can shift+alt+arrows or shift+alt+click to select blocks (rather than lines) while in JetBrains IDEs, one can middle-click to do the same effect.

![capture](https://cloud.githubusercontent.com/assets/1588553/23772703/f8819d34-04e9-11e7-8423-53556f73c535.PNG)

**Comment by pirbo** [comment]
It's already there:
> hold alt key while dragging to select text.

**Comment by hmedina** [comment]
Addendum: add a link for the text editor's documentation.
