### ISSUE TITLE
When opening a file, switch to it in the editor

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#362]
When opening a file in the KaSimInBrowser, the editor remains in the default empty model named "model.ka". Other than the contact map appearing (which may take time to render) or the eventual error message, there's little indication that the file was loaded properly. It would be nice if the file displayed in the editor was the file the user just opened.

**Comment by pirbo** [comment]
Are you using up to date code? I confirm that what you describe use to be the case but @majorseitan has fixed it and https://dev.executableknowledge.org/try/ now behaves correctly for me...

**Comment by hmedina** [comment]
I'm using KaSimInBrowserHostedAtTheCloud. I believe that means it is the latest build. And the issue is still present as of this writing. Tested on Firefox 52.0 x64, Chrome 56.0.2924.87 x86, & Chrome 57.0.2987.110 x64, present in all. Don't tell me this is a Windows thing...

**Comment by pirbo** [comment]
This must be a timeout issue. I do reproduce when I open `models/large/ensembles/ensembles.ka` but the switch occurs correctly with any tiny model (if there is no error, no switch when an error is raised...)

**Comment by pirbo** [comment]
Should be fixed now...
