### ISSUE TITLE
Export filenames end up with extra .txt extension under Firefox

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#365]
When I hit export, I get a filename with an extra ``.txt`` extension under Firefox (not under Chrome). For example, if I export as ``foo.ka``, I download a file called ``foo.ka.txt``.

It seems related to this https://support.mozilla.org/t5/Firefox/How-do-I-prevent-Save-as-csv-file-alwways-appending-txt-to-the/m-p/566112

**Comment by pirbo** [comment]
The solution might be to declare ka files as `application/octet-stream` instead of `text/plain`...

**Comment by hmedina** [comment]
The secondary extension is no longer appended under OpenWith options.
