### ISSUE TITLE
Unclear load order

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#366]
I have a model in two files. The first declares variables, the second rules. I open the one with variables first. Then I open the one with rules. I get an error about illegal use of variables before their declaration.

If I change the order and open first the rule file, then the variable file, my CPU utilization goes through the roof and nothing happens for a couple minutes... (compiling?)

Should I be opening files in reverse order to their variable declaration order..?

I would suggest having a visible indicator that the file-names can be dragged and dropped to arrange the load order, something like [this icon](https://camo.githubusercontent.com/c92202623481694a52b9f0abd07ba898fa11dcdf/687474703a2f2f692e696d6775722e636f6d2f4a616667726c502e706e67). Alternatively something more old-school: two buttons, one with an up arrow, the other with a down arrow, that would re-organize the load order of files in a project.

**Comment by hmedina** [comment]
Even when presented in the right order (I presume top loads first), large models seem to struggle with load order. Let's refer to the file with variables v.ka and the ruleset r.ka :

I load v.ka then r.ka and I get the error. I drag r.ka below v.ka and I still get the error. When I re-open the drop-down box with the file names, I see the older order (r.ka before v.ka) instead of the one I just manually rearranged. KaSimInBrowserRunOnTheCloud is fighting me tryin' to keep them illegals...

**Comment by pirbo** [comment]
Timeout related issue again ...

**Comment by pirbo** [comment]
Can you retry now that @majorseitan has worked on these issues?

**Comment by hmedina** [comment]
I no longer get error messages. In fact, I get nothing. And my CPU usage maxed out.

Loading r.ka before v.ka, I don't get the error message I should be getting (i.e. var called before being defined). The same for loading v.ka before r.ka.

**Comment by hmedina** [comment]
Eventually (~30s), a contact map is displayed. I assume it finished parsing / evaluating the files. Given that it takes ~30s before I get a readout, it is unclear to me if KaSim is doing anything, but that's a separate issue #376

The editor also becomes stuck in whatever file was last open. Eventually, one is able to change files, so I assume it has finished parsing/compiling then. Loading r.ka before v.ka still doesn't yield an error message.

**Comment by hmedina** [comment]
I'm not dead yet.

**Comment by hmedina** [comment]
After updating WebSim, I'm dead.
