### ISSUE TITLE
The Gray Screen of Death is back

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#368]
Similar to what happened with https://github.com/Kappa-Dev/KaSim/issues/357 , when I press Enter after changing the value of the PauseIf box, I get a gray screen that covers everything. I can't see a dialog box, nor an error message, nor any way of re-gaining control of the editor.

![capture](https://cloud.githubusercontent.com/assets/1588553/24129638/55be296c-0dba-11e7-96e4-84c95cc215d1.PNG)

**Comment by pirbo** [comment]
Try press `esc` (this is a serious issue anyway)

**Comment by hmedina** [comment]
That was my first reaction. I could not escape its grip.

Ultimately, I deleted the element through Firefox' element inspector and rescued the code in the editor.
