### ISSUE TITLE
Data files do not always stop at tmax

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#37]
the -t T -p N option yields data files that do not always stop at T (with N+1 data points, i * T/N, i=0,...,N) but sometimes go several iterations beyond T. This seems to be a stochastic behavior... 

For example, use the attached test.ka with 
KaSim -i test.ka -t 1 -p 30 -seed 996313470
behaves as expected

KaSim -i test.ka -t 1 -p 30 -seed 850995465
does not.

It appears that when the time advance Dt is larger than a few time intervals T/N you correctly write out the (same) system state for as many T/N steps as needed to catch up with Dt. That's clearly desired. However, you also do this when you run over T

**Comment by pirbo** [comment]
Already merged as far as I understand
