### ISSUE TITLE
Bug: error message about labels existing when they don't

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#372]
Error: `1/1 [ ] Label 'A' already defined`

Code:
```
%agent: A(n,m)
'r' A(n),A(m) <-> A(n!1),A(m!1) @ 1.0e-4 {0},1.0e-2
%obs: '1' |A(n,m)|
```

Bugs:
-There is no label 'A'
-Since there is none, it can't possibly be re-defined
-Error message doesn't specify line or location
-Red circle with a white x indicator marks the problematic line as line #3

**Comment by hmedina** [comment]
It appears it loaded the same models twice, or it loaded once and injected it into `model.ka`. To reproduce:
1) Go to the webpage KaSimInBrowserAtCloud
2) File > Open > `foo.ka`
File menu will have 2 files, `foo.ka` and `model.ka`, both with the same code. That explains at least the re-definition. It doesn't explain however why or where 'A' got defined in the first place...

**Comment by pirbo** [comment]
That should have disappeared
