### ISSUE TITLE
Should permission to overwrite data.csv also overwrite inputs.ka ?

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#373]
If the trajectories output file specified by the user already exists, KaSim asks if it should erase it before outputing to it. Should the user grant access, shouldn't it also overwrite the `inputs.ka` file, instead of generating an `inputs_1.ka` file instead?

**Comment by pirbo** [comment]
Maybe... I don't know. I would like more feedback on this one before going into any direction.

**Comment by glucksfall** [comment]
Hello, I would like KaSim to write input.ka be optional, and if KaSim writes it, be overwritable.
For instance, I tested the first KaSim version that writes input.ka in a script performing a Genetic Algorithm, and at the end, I have hundreds of input_*.ka files that are the same except for variable values (that I recorded previously in another file). To me, only the first input.ka could be useful.

**Comment by pirbo** [comment]
It should be implemented by 32ba6ccaacf3e2805ad0eb22adc063757d4d4444

**Comment by pirbo** [comment]
There are now the options:
`--no-log` to not get any inputs.ka
`-log file` to rename inputs.ka into file.ka
