### ISSUE TITLE
sequential multi-site binding in Kappa?

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#387]
Hello,

I'm having trouble expressing a sequential interaction in Kappa and was hoping for a pointer in right direction. Imagine agent ``S(x,y)`` that binds to agent ``A(x)`` at rate ``k1``, and only when ``S`` and ``A`` are bound (via ``x``) then ``S(x!1,y)`` can bind to ``B(y)`` with rate ``k2``. No agent should be created or destroyed in either interaction. Attempt to formalize this:

```
%agent: S(x,y) 
%agent: A(x)
%agent: B(y)

# S binds A
'R1' S(x),A(x) -> S(x!1),A(x!1) @ k1
# When S and A are bound via x, B binds A via y
'R2' S(x!1,y),A(x!1),B(y) -> S(x!1,y!1),B(y!1) @ k2

%var: 'k1' 1.0E-2
%var: 'k2' 1.0E-3
%var: 'S_amount' 20
%var: 'A_amount' 20
%var: 'B_amount' 20

%obs: 'S' |S()|
%obs: 'A' |A()|
%obs: 'B' |B()|

%init: 'S_amount' S()
%init: 'A_amount' A()
%init: 'B_amount' B()
```

The second rule gives the error: ``This is the third occurence of link '1' in the same mixture`` which I'm not sure how to interpret?

Thanks very much.

**Comment by feret** [comment]
Hi Yarden, 

This is the rule you would like: 

'R2' S(x!1,y),A(x!1),B(y) -> S(x!1,y!2),A(x!1),B(y!2) @ k2

Everything that is tested must occur in the lhs AND in the ohs of the rule, and in the same order to please the longest prefix convention. Also, each bond must be labelled with a distinct identifier. This way, a bond identifier that occurs in a pattern occur exactly twice in this  patter). 

Best. 
Jérôme.

**Comment by yarden** [comment]
Hi Jérôme,

Thanks very much; the longest prefix convention makes sense, but I had no idea that the bonds had to be labeled differently. The rule:

``'R2' S(x!1,y),B(y),A(x!1), -> S(x!1,y!2),A(x!1),B(y!2) @ k2``

conserves ``A`` and ``B``. If I wanted ``A`` to get consumed in the reaction, I could write this:


``'R2' S(x!1,y),B(y),A(x!1) -> S(x!1,y!2),B(y!2) @ k2``

but I get the same error as before.

**Comment by feret** [comment]
Hi Yarden, 

In the latter case, the site x of S is free after the application of the rule: 
> 'R2' S(x!1,y),B(y),A(x!1) -> S(x,y!2),B(y!2) @ k2
> 
A bond identifier cannot occur exactly once in a pattern. 

Best 
Jerome.
