### ISSUE TITLE
Python 2 compatible code to interface with Kappa app?

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#390]
I'd like to use the code in ``KaSim/python/kappa_client.py`` to interface locally with ``StdSim`` via Python. Unfortunately, ``urllib`` was completely reorganized in Python 3, so the lines:

```
import urllib.error
import urllib.request
import urllib.parse
```

in ``kappa_client.py`` (and ``kappa_common.py`` which is imported) break Python 2 compatibility. Is there a Python 2 compatible version of a Python client somewhere? Or is the only way forward to rewrite all the calls to urllib to be Python 2 compatible? (Assuming there aren't other Python 3 specific idioms used).

Thanks very much.

**Comment by pirbo** [comment]
There is no more kappa_client compatible with Python 2 but I think that the StdSim backend does not use urllib at all, only the HTTP one does. So,
- you should be able to get a working_only_for_unix_backend_kappa_client.py only by erasing stuff..
- we might refactor the code to get a kappa_client_unix.py compatible python 2&3, a kappa_client_http.py python 3 only (and maybe a kappa_client.py that automatically choose the right backend from the given url as kappa_client does today)

**Comment by yarden** [comment]
Thanks @pirbo. I am trying to make kappa_client work with Python 2 but ran into an error that's probably related to my version of StdSim expecting some parameter which is not set by the client. Here's how I'm calling StdSim:

```
def get_StdSim_path(app_dir="~/Software/Kappapp.app/Contents/Resources/bin/"):
    """
    Get path to standard simulation application.
    """
    stdsim_path = \
      os.path.join(os.path.abspath(os.path.expanduser(app_dir)), "StdSim")
    return stdsim_path

def load_kappa_file(fname):
    """
    Load Kappa file into the File object the Kappa simulator
    expects. (Not worrying about closing file for now...)
    """
    if not os.path.isfile(fname):
        raise Exception, "No file %s" %(fname)
    with open(fname) as file_in:
        code = file_in.read()
        uniq_id = str(uuid.uuid1())
        file_meta = FileMetadata("file_id", 0)
        kappa_file = File(file_meta, code)
        return kappa_file

def main():
    stdsim_path = get_StdSim_path()
    if not os.path.isfile(stdsim_path):
        raise Exception, "Cannot find KaStd at %s" %(stdsim_path)
    else:
        print "using KaStd at %s" %(stdsim_path)
    kappa_fname = "test.ka"
    # make a Kappa simulator
    kappaStd = KappaStd(stdsim_path)
    # load a Kappa model from file
    kappa_file = load_kappa_file(kappa_fname)
    project_id = "test"
    simulation_param = SimulationParameter(1, project_id)
    # start the simulation
    print "starting simulation"
    print simulation_param
    kappaStd.simulation_start(project_id, simulation_param)
    print "simulation information"
    print kappaStd.simulation_info(project_id, project_id)
    print "shutting down"
    kappaStd.shutdown()

if __name__ == "__main__":
    main()
```

I'm running all of this with Python 2.7. For debugging purposes, I added some output to kappa_core - these are my versions of:

* [kappa_client.py](https://gist.github.com/yarden/72258c337da0e851406901b3c102adb2)
* [kappa_common.py](https://gist.github.com/yarden/f3e6fdf669ea2f98102e92b8867a8197)

and my model .ka file is [test.ka](https://gist.github.com/yarden/d7ade01da631aa3d1dec1ee2926f868e). When I try calling StdSim, I get the error:

```
$ python kappa_client.py 
using KaStd at /Users/yarden/Software/Kappapp.app/Contents/Resources/bin/StdSim
starting simulation
<__main__.SimulationParameter object at 0x10720f3d0>
Something went wrong...
Fatal error: exception Ag_oj_run.Error("Line 1:\nMissing record fields simulation_pause_condition, simulation_seed, simulation_store_trace")

Traceback (most recent call last):
  File "kappa_client.py", line 389, in <module>
    main()
  File "kappa_client.py", line 382, in main
    kappaStd.simulation_start(project_id, simulation_param)
  File "kappa_client.py", line 181, in simulation_start
    [project_id,simulation_parameter.toJSON()]))
  File "kappa_common.py", line 66, in dispatch
    raise KappaError("expect id {0} got {1}".format(response["id"], message_id))
kappa_common.KappaError
```

Looks like ``simulation_pause_condition, simulation_seed, simulation_store_trace`` params need to be set. Is there a reference for the interface? Not sure how to set these parameters.

Thanks very much for your help.
