### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bgyori** [Kappa-Dev/KaSim#394]
Do you plan to put up a new release at some point? We recently changed PySB and INDRA to be compatible with the latest KaSim/KaSa (as of yesterday) so a new release in the near future would be great.

**Comment by pirbo** [comment]
We do.
We've done a branch KaSim4 a few weeks ago where we put only bug fixes. Unless there is a disaster, the syntax and the command line option should not move anymore at all (sadly, we don't reach the point where the REST and Python API can be considered as stable enough to be advertised publicly).

Get sure you are compatible with this branch.
I'll tag KaSim4beta tomorrow and provide binary asap. The real release should follow soon...

**Comment by pirbo** [comment]
@feret You're still pushing quite some patch in KaSim4 branch. Do you have still stuff in your stack or can we imagine releasing soon?
In the meanwhile, I'll put binaries of the beta on github release page.

**Comment by feret** [comment]
Could you give until Monday, so that I include KaDe in the manual.

**Comment by pirbo** [comment]
A stable (hopefully) KaSim 4.0 is finally finally out (I've done it a few weeks ago but I still did not find time to advertise it...)! Corresponding kappy 4.0 is available in pip for a lot of MacOS and linuxs
