### ISSUE TITLE
Internal VS External semi-links  ???

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#399]
Is it a bug, or I was not aware that the semantics of semi-links has changed ? 

Consider the following rule: 
 A(x! _,y),B(x! _,y)-> A(x! _,y!1),B(x! _,y!1) @ 0{1}

If ! _ is interpreted as an internal semi-link, this rule should apply to the following pattern: 
 A(x!1,y),B(x!1,y) -> A(x!1,y!2),B(x!1,y_2) @ 0{1}

That is to say that when patterns are refined so as to avoid incompletely specified links, we have to consider the regular case where sites with semi-links are indeed linked to fresh species, but also the case of sites with semi-links  linked to fresh sites in existing agents, and even two sites with semi-links bonds together. 

If !_ is interpreted as an external semi-links, this rule should apply only if the bond is external to the pattern (i.e. not connected to an agent belonging to the pattern). This is Jonathan Hayman convention. 

According to the manual:  3.3.3 Link type
What should be implemented is the first definition (internal dandling bond). 

Yet when I run the following two examples: 
C() is reachable only in the second model, which would suggest that the second definition is implemented. 

%init: 10 A(),B()

A(x),B(x) -> A(x!1),B(x!1) @1
A(x! _,y),B(x! _ ,y)-> A(x! _,y!1),B(x! _,y!1),C() @ 0{100}
A(y! _) -> A(y) @1
%obs: 'goal' C()

%agent: A(x,y)
%agent: B(x,y)
%agent: C()

VS 

A(x),B(x) -> A(x!1),B(x!1) @1
A(x! _,y),B(x! _ )-> A(x! _,y!1),B(x! _,y),C() @ 0{100}
A(y! _) -> A(y) @1
%obs: 'goal' C()

%agent: A(x,y)
%agent: B(x,y)
%agent: C()

**Comment by feret** [comment]
Moreover, we will have to take care about the difference between stochastic and differential semantics. 
In differential semantics, a binary rule is never applied in a unary context unless its unary rate is given explicitly. 

For instance: 

A(x),B(y) -> @ 1  and A(x),B(y) -> @ 1{1}

have a different semantics in the differential semantics, since the first applies only in binary context, whereas the second one apply in both cases.  (@1 means @1{0}) 

Thus, I think we would need a flag to rune semi-links disambiguation, so as to
consider the refinement that changes the connectedness of the lhs of rules only if a unary rate is given, and it that case, assign the rate of the refined unary rule to the unary rate of the orignal rule.

**Comment by pirbo** [comment]
> Consider the following rule:
> A(x! _,y),B(x! _,y)-> A(x! _,y!1),B(x! _,y!1) @ 0{1}
> 
> If ! _ is interpreted as an internal semi-link, this rule should apply to the following pattern:
> A(x!1,y),B(x!1,y) -> A(x!1,y!2),B(x!1,y_2) @ 0{1}

indeed that is fixed.

- Are you aware that kade/unary2 test fails with ` +Fatal error: exception Invalid_argument("index out of bounds") ` is it my fault?
- There is a typo in kade/unary4/README where `unary3.ka` should be replaced by `unary4.ka` BUT unary4.ka is a polymerizing model so KaDe do not finish on it...

**Comment by feret** [comment]
Great thank you. 

The first bullet describes a  bug that looks like one I have encountered ten days ago, but that I was unaware to reproduce. 
If this is the same, this was during the application of a rule in a unary context. 

For the second bullet, I will add the option to bound the size of species.

**Comment by pirbo** [comment]
Note to self :-) : do not close this issue before that fixes were backported to KaSim4 branch

**Comment by feret** [comment]
On unary1.ka. 
The ODEs is correct, but the information to link back to the original model is confusing: 
lines 70-71 of ode.m 

kun(1)=100; % A(x!_,y), B(x!_,y) -> A(x!_,y!1), B(x!_,y!1), C()(unary context)
k(2)=100; % A(x!_,y), B(x!_,y) -> A(x!_,y!1), B(x!_,y!1), C()

lines 203-2011:
% rule    : A(x!_,y), B(x!_,y) -> A(x!_,y!1), B(x!_,y!1), C()
% reaction: A(x!1, y), B(x!1, y) -> C() + A(x!1, y!2), B(x!1, y!2) 

dydt(1)=dydt(1)-k(2)*y(1);
dydt(2)=dydt(2)+k(2)*y(1);
dydt(3)=dydt(3)+k(2)*y(1);
dydt(4)=1;

Is there a way to inform KaDe that the second rule is a unary refinement of the first one, so that KaDe does not introduce a new rate, and use the proper one (kun(1)) ? 
If not could we add this information in an optional field ?

**Comment by feret** [comment]
Thank you @pirbo for commit b1802c1116ad9919d8d15cce34d6dadc0e30061d.

**Comment by feret** [comment]
OK, now I understand. 
There had been a misunderstanding in the way to handle rule. 
I know what to do, but it will take some time.

**Comment by feret** [comment]
@pirbo, could you have a look at: 2b13038

Could you have a look at the function valid_modes in odes/ode_interface.ml. 

Three cases: 
A) if the arity has not changed: unary/usual application is allowed provided when the corresponding rate is given and not equal to 0. 

B) if the arity has changed to 2 to 1: I declare it as a Unary_refinement when the unary rate is given and not equal to 0. 
Unary refinements behave as the usual case, but with the unary rate instead. 

C) if the arty has changed to n to n'<1 and n<>2, then the rule is ignored. 
Reactions in the ODEs semantics preserve arities, except is a unary rate is given explicitly. 

I am not so happy, because I have recomputed the arity of the original rule. 

If there is a way, to simplify this function, because maybe the information I need, is already stored somewhere. Please let me know. 
In the meantime I propagate this to KaSim4.

**Comment by feret** [comment]
@Pirbo, did you find the time to look at commit 2b13038 ? 
If you are happy with the solution, we can close the issue, 
If not, let me know.

**Comment by pirbo** [comment]
I finally did and I'm happy :-)
