### ISSUE TITLE
Apply time-sensitive perturbations before the event modifies the mixture

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#400]
Requesting a snapshot at `[T] > 10`, KaSim will produce a snapshot at the first moment time goes above the value 10, which is during the time update of the Gillespie algorithm, but the snapshot yields the mixture _after_ the event has modified it. Thus the snapshot does not hold the state of the mixture at `[T] > 10`, but rather `[T] > 10 + 1 event`.

**Comment by pirbo** [comment]
Fixed in 9bb6f27f7575fd76850e9a6ed7d77fb124fb792d

I'm worried it changes some data.csv too but late Friday evening commits won't be fun elsewhere!
