### ISSUE TITLE
Error message in token expression

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#410]
%token: a
%token: b

| 1 a -> | 1 b @ 1

outputs ".... I was expecting a_0 t_0 + ... + a_n t_n"
when the correct error should be "a_0:t_0 + ... + a_n: t_n"
An alternative is to change the token expression accordingly (it may make more sense since it would correspond to the way we express initial conditions: %init: 100 A() not 100:A()

**Comment by vd1** [comment]
On 28 June 2017 at 12:43, Krivine <notifications@github.com> wrote:

> An alternative is to change the token expression accordingly (it may make
> more sense since it would correspond to the way we express initial
> conditions: %init: 100 A() not 100:A()
>
> ​if that is​ possible without too much complication it would be nice indeed
Vincent

**Comment by pirbo** [comment]
I've also modified `%init:` to allow token introduction as agent one `%init: arg_expr token`. The only specific syntax is in perturbation but it make sense as ` tok <- val` really means __set__ the value of `tok`to `val` which is completely different than intro/delete (i.e increase/decrease the value)
