### ISSUE TITLE
Snapshot statistic file

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#414]
In the style of compression statistics, it would be great if some statistic describing snapshot could be dumped as well. I am thinking of a csv of the form:
# species_by_size number
1  120
4 22
5 2 
which reads as: there are 120 monomers, 22 species of size 4 and 2 species of size 5 which could be displayed eventually as a nice histogram.

**Comment by hmedina** [comment]
I have a small toolset for this precise purpose: https://github.com/hmedina/KaSaAn

Warning: a biologist wrote that code.

**Comment by hmedina** [comment]
If we're planning real dev. time for this, I would be most interested in having a metric akin to a graph's strength, but ported to site graphs, with causal constraints.

One thought would be:
  * 2 types of strength, both would be a property of a species (not a snapshot).
    * Strength 1 would be the ratio of current bonds in the complex divided by the total possible bonds achievable (as defined by the contact map). This would not use causal constraints.
    * Strength 2 on the other hand would be the ratio of current bonds in the complex divided by the current + 1-jump reachable bonds. This would use the causal constraints.

The rationale for these is:
  * A complex with 'n' bonds and strength 1 of 0.1 and strength 2 of 0.9 might suggest a deadlock or "frustrated" state.
  * A similar one with strength 1 of 0.1 and strength 2 of 0.1 would suggest the snapshot is of a transcient state.
  * A similar one with strength 1 of 0.9 and strength 2 of 0.9 might suggest a (dynamic) steady state.

I believe @pirbo had some other thoughts on the notion of "strength of a graph" ?

**Comment by pirbo** [comment]
Let's close that.
An external analyser that loads the JSON of snapshots and compute stuff on it is the answer for any further extension
