### ISSUE TITLE
setting parameters in kappa simulation from Python 2

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#419]
I'm calling Kappa programmatically using Python 2 via the interface described Issue #390 -
 which I call using my simplified wrapper here (https://gist.github.com/yarden/afd8291ea1d8e5049f84906bb5e34410). It takes a Kappa model file name, simulates the model for the given time interval, and returns the results as a pandas DataFrame. 

I had a couple of questions regarding the interface used here:

1. Is it possible to access and change the initial conditions or rate constants for the Kappa model here? If I want to run a model multiple times with different initial conditions, or with different rate constants for the rules, it seems that in the current interface the only way to do this is to create an entirely new Kappa file with those constants changed.

2. Related question: the current interface requires ``FileMetadata/File`` objects, which means a file has to be created for the Kappa model to be simulated. Is there an easy way to bypass this and load a Kappa model without having to serialize a file?

Thanks very much.

**Comment by pirbo** [comment]
If I understand it correctly, second item is easy. You can just give a dummy argument to FileMetadata and everything is fine.
I've added to kappa_common.py
```
def stringAsFile(content,position=1):                     
    return(FileFileMetadata("inlined_input",position),content)  
```
in order to make it more intuitive.
Tell me if an other API would be clearer...

That allows me to simplify your wrapper up to https://gist.github.com/pirbo/43e9ddb537bb65e5b4edb6e6a59a16e1

I'm working on first item, Everything is nearly there but nothing is exposed to the REST/Python API...

**Comment by pirbo** [comment]
Here you are. I have to document this in a better place:
method `project_parse` now takes as (optional) argument the list of overwritten variables.

That means that if your model uses an algebraic variable called `foo`, you can overwrite the value of `foo` to 42 for 1 simulation by calling `project_parse([("foo",42)])`

In your case, you would typically write
```python
model_code = "[...]\n\
A () -> B () @ 'fluctuating_rate'\n\
[...]\n\
%init: 'variable_quantity' A()\n\
[...]\n"
file_object = kappa_common.stringAsFile(model_code)
runtime.file_create(file_object)
for x in xrange(10, 100):
  for y in xrange(20,50):
    runtime.project_parse[("fluctuating_rate",x),("variable_quantity",y)]
    data = run_this_model_variant()
    analyse(data)
```

**Comment by yarden** [comment]
You wrote:

```
def stringAsFile(content,position=1):                     
    return(FileFileMetadata("inlined_input",position),content)  
```

I assume you meant:

```
def stringAsFile(content,position=1):                                                                                                                                
    return(File(FileMetadata("inlined_input",position),content))        
```

I'm not sure about ``runtime.project_parse[("fluctuating_rate",x),("variable_quantity",y)]`` -- isn't project_parse a method? In any case when I try this:

```
    model_code = '''
    A () -> B () @ 'fluctuating_rate'
    %init: 'variable_quantity' A()
    '''
    file_object = kappa_common.stringAsFile(model_code)
    runtime = kappa_std.KappaStd(URL_TO_USE)
    runtime.file_create(file_object)
    print runtime.project_parse()
```

I get: 

```
Traceback (most recent call last):
  File "kappa_model.py", line 69, in <module>
    print runtime.project_parse()
  File "kappa_std.py", line 78, in project_parse
    return(self.dispatch("ProjectParse"))
  File "kappa_std.py", line 56, in dispatch
    return self.projection(response)
  File "kappa_std.py", line 75, in projection
    raise kappa_common.KappaError(data)
kappa_common.KappaError
```

**Comment by pirbo** [comment]
> I assume you meant:
```
def stringAsFile(content,position=1):                                                                                                                                
    return(File(FileMetadata("inlined_input",position),content))
```

Yes, sorry!

For the second error, did you update the KaSimAgent and the kappa_std.py that you are using?

**Comment by yarden** [comment]
ah, I didn't recompile agents. Now your example from kappa_model.py works, but I still get an error when calling ``project_parse()`` to try to modify variables:

```
   model_code = '''
   A () -> B () @ 'fluctuating_rate'
   %init: 'variable_quantity' A()
   '''
   file_object = kappa_common.stringAsFile(model_code)
   runtime = kappa_std.KappaStd(URL_TO_USE)
   runtime.file_create(file_object)
   print runtime.project_parse()
```

**Comment by pirbo** [comment]
The error is indeed not really readable but it is: `"B" is not a declared agent.` and indeed your example lacks
```
%agent: A()
%agent: B()
```

**Comment by yarden** [comment]
Yes, just figured all the errors come from the model itself. Fixed it so that it now runs, but I am still not sure what the right way is to mutate ``project_parse()`` returns so that values can be changed dynamically. This:

```
if __name__ == "__main__":
    model_code = '''
    A () -> B () @ 'fluctuating_rate'
    %agent: A()
    %agent: B()
    %var: 'fluctuating_rate' 0.0
    %var: 'variable_quantity' 0.0
    %init: 'variable_quantity' A()
    '''
    try:
        file_object = kappa_common.stringAsFile(model_code)
        runtime = kappa_std.KappaStd(URL_TO_USE)
        runtime.file_create(file_object)
        vals = runtime.project_parse()
        print "vals: "
        print vals
    except kappa_common.KappaError as e:
        print e.errors
```

gives:

```
{u'project_parse_raw_ast': u'{"signatures":[{"name":{"val":"A","loc":{"file":"inlined_input","from_pos":{"line":3,"chr":12},"to_pos":{"line":3,"chr":13}}},"sig":[],"mod":null},{"name":{"val":"B","loc":{"file":"inlined_input","from_pos":{"line":4,"chr":12},"to_pos":{"line":4,"chr":13}}},"sig":[],"mod":null}],"tokens":[],"variables":[{"first":{"val":"fluctuating_rate","loc":{"file":"inlined_input","from_pos":{"line":5,"chr":10},"to_pos":{"line":5,"chr":28}}},"second":{"val":0.0,"loc":{"file":"inlined_input","from_pos":{"line":5,"chr":29},"to_pos":{"line":5,"chr":32}}}},{"first":{"val":"variable_quantity","loc":{"file":"inlined_input","from_pos":{"line":6,"chr":10},"to_pos":{"line":6,"chr":29}}},"second":{"val":0.0,"loc":{"file":"inlined_input","from_pos":{"line":6,"chr":30},"to_pos":{"line":6,"chr":33}}}}],"rules":[{"first":null,"second":{"val":{"lhs":[{"name":{"val":"A","loc":{"file":"inlined_input","from_pos":{"line":2,"chr":4},"to_pos":{"line":2,"chr":5}}},"sig":[],"mod":null}],"rm_token":[],"bidirectional":false,"rhs":[{"name":{"val":"B","loc":{"file":"inlined_input","from_pos":{"line":2,"chr":12},"to_pos":{"line":2,"chr":13}}},"sig":[],"mod":null}],"add_token":[],"k_def":{"val":["VAR","fluctuating_rate"],"loc":{"file":"inlined_input","from_pos":{"line":2,"chr":19},"to_pos":{"line":2,"chr":37}}},"k_un":null,"k_op":null,"k_op_un":null},"loc":{"file":"inlined_input","from_pos":{"line":2,"chr":0},"to_pos":{"line":2,"chr":37}}}}],"edit_rules":[],"observables":[],"init":[{"first":{"val":["VAR","variable_quantity"],"loc":{"file":"inlined_input","from_pos":{"line":7,"chr":11},"to_pos":{"line":7,"chr":30}}},"second":{"val":["mixture",[{"name":{"val":"A","loc":{"file":"inlined_input","from_pos":{"line":7,"chr":31},"to_pos":{"line":7,"chr":32}}},"sig":[],"mod":null}]],"loc":{"file":"inlined_input","from_pos":{"line":7,"chr":31},"to_pos":{"line":7,"chr":34}}}}],"perturbations":[],"configurations":[]}', u'project_parse_project_version': 1}
```

**Comment by pirbo** [comment]
No, you overwrite the values by giving them as argument to project_parse.
and each time, you want to run the model with a different set of values, you (re)parse.
```
try:
        file_object = kappa_common.stringAsFile(model_code)
        runtime = kappa_std.KappaStd(URL_TO_USE)
        runtime.file_create(file_object)
        runtime.project_parse([("fluctuating_rate", 0.01),("variable_quantity",1000)])
        do_something()
        runtime.project_parse([("fluctuating_rate", 0.1),("variable_quantity",500)])
        do_something()
```
The values returned by parse are "useless" (unless you want to feed the static analyser with them but the python wrapper is not there yet)

**Comment by yarden** [comment]
Oh I see, thanks, I was thrown off by your original line:

```
    runtime.project_parse[("fluctuating_rate",x),("variable_quantity",y)]
```

I thought that was a typo for getting the result of project_parse and then doing something with it, but it was just missing parens :)

**Comment by pirbo** [comment]
sorry, my bad...

**Comment by yarden** [comment]
Thanks very much, it now works:

```
    model_code = '''
    %agent: A()
    %agent: B()
    A () -> B () @ 'rate'
    %var: 'rate' 0.0
    %var: 'variable_quantity' 0.0
    %init: 'variable_quantity' A()
    %init: 0.0 B()
    %obs: 'a' |A()|
    %obs: 'b' |B()|
    '''
    try:
        ka_model = KappaModel(model_code)
        rates = [3.0, 5.0]
        all_data = []
        for rate in rates:
            data = ka_model.simulate(var_values=[("rate", rate),
                                                 ("variable_quantity", 20.0)],
                                     seed=10)
            data["rate"] = rate
            all_data.append(data)
        result = pandas.concat(all_data)
        import matplotlib.pyplot as plt
        import seaborn as sns
        sns.set_style("ticks")
        g = sns.FacetGrid(hue="rate", data=result)
        g.map(plt.plot, "time", "b")
        plt.ylabel("|B()|")
        plt.legend()
        plt.show()
    except kappa_common.KappaError as e:
        print e.errors
```
gives:

![image](https://user-images.githubusercontent.com/96318/28678092-731127e0-72bd-11e7-9fa1-87da07a021ac.png)

I will experiment further with changing the values of an ongoing simulation as opposed to restarting.

**Comment by yarden** [comment]
One quick follow up question related to this: using the Python API, what's the proper way to retrieve various initial values (of rate constants, for instance) that are set in the Kappa model? I.e., to get these even *before* running any simulations? E.g., if I have a model like:

```
%agent: A()
A() -> @ 'k1'
%var: 'init_A' 0.0
%var: 'k1' 0.01
...
```

how could I access values of ``init_A`` and ``k1`` before running the simulation? It doesn't seem to be in what ``simulation_info()``  returns. Thanks!

**Comment by pirbo** [comment]
There is a way but it is super heavy and I wish I find some time to make it easier:
First, you need to use `simulation_perturbation(perturbation_code)` (that looks obviously buggy, I'll fix it) in order to ask for a print. For example: `simulation_perturbation("$PRINT \"init_val_a\" < |A()| >")` but you don't get the result back, you then need to `simulation_detail_file_line("init_val_a")` to query the result...

**Comment by pirbo** [comment]
I'll make the remaining wish of being able to introspect the kappa model from the python interface as an independent issue and close this one.
