### ISSUE TITLE
UI feature request: optionally show "direct production" relationships

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#426]
If we ignore conservation of mass, it's useful to have models where one agent leads to the production of another agent. For instance:

```
%agent: A()
%agent: B()

A() -> B() @ 'k1'

%var: 'k1' 0.0
```

Here A leads to production of B. This information isn't presented in the UI (so this model isn't visualized at all). If we add a rule that concerns binding, e.g.,

```
%agent: A(s)
%agent: B()
%agent: C(s)

A() -> B() @ 'k1'
A(s),C(s) -> A(s!1),C(s!1) @ 'k2'

%var: 'k1' 0.0
%var: 'k2' 0.0
```

Then the binding relationship will be displayed, of course, but without the relationship that A "directly produces" B:

![image](https://user-images.githubusercontent.com/96318/28878227-a5ee85a0-776c-11e7-998b-ca73e9914a47.png)

Would it be possible to add this information to the graph (optionally, perhaps by ticking a box)? One possibility is to show these relationships as directed edges, e.g., **A ---> B**, that would look different from the binding site edges. If the rule is ``A() -> B()``, you can imagine a directed edge going from the blob representing agent A to the blob representing agent B, whereas if it was ``A(s) -> B()`` the edge would be from binding site ``s`` on A to the agent blob B, and so on.

Thanks very much, Yarden

**Comment by feret** [comment]
Dear Yarden , 

I think that this information is present in the influence map (to be integrated in the UI soon). 
The contact map is just a summary of potential bonds and potential states. This is a purely static information, It has nothing to do with influence/causality relations. 

I would prefer to mix these two kinds of properties. 

Best regards. 
Jérôme.

**Comment by hmedina** [comment]
I agree on the distinction, also because the contact map has no dynamics information. However, shouldn't it at least display agent `B` somewhere? After all, it _is_ an agent and it _is_ involved in some rules.

**Comment by feret** [comment]
Yes you are right. 
The json output is OK. 
The point is that the UI does not display agent with no site. 

(which explain why nothing is shown on Yarden’s first example).

**Comment by yarden** [comment]
Thanks very much, Jérôme. I appreciate the distinction too. The reason I found it counter-intuitive that it's not in the UI though is cases like these:

```
%agent: A(x)
%agent: B(y)
%agent: C(z)

A(x) -> B() @ 'k'
B() -> C(z) @ 'k'
A(x),C(z) -> A(x!1),C(z!1) @ 'k'

%init: 10 A()
%var: 'k' 0.1
%obs: 'A' |A()|
%obs: 'B' |B()|
%obs: 'C' |C()|
```

Here, agent B has a binding site, but it's still not displayed:

![image](https://user-images.githubusercontent.com/96318/28893781-b97051a6-77a0-11e7-8441-dd2da43010a9.png)

Since the interaction between agent A and agent C can only take place via B, it appears counter-intuitive that it's not displayed. I'm not too familiar with contact maps, but it would be nice to have a single visualization that presents both types of information (perhaps making a distinction between "X produces Y" rules and binding interactions).

**Comment by pirbo** [comment]
The follow up is #428

**Comment by feret** [comment]
Sites with neither a binding state, nor an internal state are not displayed in the contact map. 
(a site is considered as a binding site if it occurs with a binding state in a rule or  in the initial state) 
Thus, in your example, B has no site either. 

If you add the following rule: 
A(x!x.A) -> B(y!1),B(y!1) @ ‘k'

The site y becomes a binding state. 
There will be a self bond on y.B at low resolution. 
This bond disappear at higher resolution, since the rule is dead.
