### ISSUE TITLE
Self-bonds not shown in CM under strange conditions

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#427]
Given the code:
```
%agent: A(w,x,y,z)
%agent: B(a)
%init: 11 A()
A(w!.),B(a!.) <-> A(w!1),B(a!1) @ 1.0, 1.0e-4
A(x!.),B(a!.) <-> A(x!1),B(a!1) @ 1.0, 1.0e-4
A(y!.),B(a!.) <-> A(y!1),B(a!1) @ 1.0, 1.0e-4
A(z!.),B(a!.) <-> A(z!1),B(a!1) @ 1.0, 1.0e-4

A(w!.),A(w!.) <-> A(w!1),A(w!1) @ 1.0 {1.0}, 1.0e-4
A(x!.),A(x!.) <-> A(x!1),A(x!1) @ 1.0 {1.0}, 1.0e-4
A(y!.),A(y!.) <-> A(y!1),A(y!1) @ 1.0 {1.0}, 1.0e-4
A(z!.),A(z!.) <-> A(z!1),A(z!1) @ 1.0 {1.0}, 1.0e-4

-> B() @ 1.0
```
One would expect to see the self bonds in agent `A`, however the CM does not render them. If however I delete the first rule-block (lines 4-7), then the self bonds appear.

**Comment by feret** [comment]
They are in the json output, but are not drawn. 
Playing a little bit with the model, it seems to be that self bonds are not displayed when in competition with some other bonds. 

Cheers. 
Jérôme.

**Comment by aznmonkey** [comment]
Fixed it. My bad...I was returning in the filter the result of the check on the first link on the site always...

**Comment by feret** [comment]
No problem. 
Thank you for the fix.
