### ISSUE TITLE
Agents with no sites should still be drawn in the contact map

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#428]
See #426 to get problematic examples

**Comment by pirbo** [comment]
If I understand correctly your remark @feret on #426, this is the expected behaviour. I let you close this issue then.

**Comment by feret** [comment]
No, this is not the expected behavior. 
The JSon produced by KaSa describes the agents that have no sites. 
But these agents are not shown in the graphical rendering.

**Comment by feret** [comment]
In the following model: D is not shown in the contact map: 

%agent: D() # Declaration of agent D 
%agent: A(x~u~p)
%init: 10 D()
-> A(x~u),A(x~p) @ 2

**Comment by pirbo** [comment]
Sorry, my bad :-)

**Comment by aznmonkey** [comment]
It should now be fixed, do you mind trying with some more complicated models to make sure that the sites and link nodes are still being rendered properly? Thanks.

**Comment by feret** [comment]
OK for me. 
Thank you very much.

**Comment by aznmonkey** [comment]
Closing issue :)
