### ISSUE TITLE
UI fails to wrap long lines, scrolls pas the edge of the screen, hides code

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#432]
When typing a long line into the UI, very weird wrapping behavior occurs. Try copy-pasting the following line:
```
%obs: '32' |A(n,m!1),A(n!1,m!2),A(n!2,m!3),A(n!3,m!4),A(n!4,m!5),A(n!5,m!6),A(n!6,m!7),A(n!7,m!8),A(n!8,m!9),A(n!9,m!10),A(n!10,m!11),A(n!11,m!12),A(n!12,m!13),A(n!13,m!14),A(n!14,m!15),A(n!15,m!16),A(n!16,m!17),A(n!17,m!18),A(n!18,m!19),A(n!19,m!20),A(n!20,m!21),A(n!21,m!22),A(n!22,m!23),A(n!23,m!24),A(n!24,m!25),A(n!25,m!26),A(n!26,m!27),A(n!27,m!28),A(n!28,m!29),A(n!29,m!30),A(n!30,m!31),A(n!31,m)|
```

Under Firefox, I get a page (canvas?) that is much wider than my screen, with a scroll bar at the bottom. However, the text editor is wrapping the line, just not to the width of my screen. Hitting the `toggle` button toggles the contact map pane, but still leaves the page too wide.

Under Chrome, the page is also too wide. Toggling out the map pane leaves a page of just the right size though. However, toggling the map back in doesn't resize anything, yielding a page again too wide for the screen.

Issue present using WebWorker on `http://dev.executableknowledge.org/try/index.html`, using whatever version of KaSimCloud available ~4:50pm Boston time.

**Comment by hmedina** [comment]
In case it might be useful, there is a discrepancy between what Firefox considers to be the full page, and what is actually the full page. Here are two images, one using the Firefox console command `screenshot [file] --fullpage`, the other a composite of many normal screenshots (the former is what Firefox thinks is the full page, the latter what actually is the full page).

Firefox fullpage:
![capture-fullpage](https://user-images.githubusercontent.com/1588553/29231542-9c5c6ef8-7eb5-11e7-88c8-2517622958e3.png)


Firefox composite:
![capture](https://user-images.githubusercontent.com/1588553/29231549-a0726d12-7eb5-11e7-9d08-4e40482fe08c.png)

Things to note:
  * In the composite, the long line actually spans the entire width of the text editor, whereas in the fullpage view, it spans half of it, wrapping too soon (but without resizing the editor).
  * In the composite, the contact map tab is visible but tiny. In the fullpage view, it is altogether not shown.

Code used:
```
%agent: A(n,m)
%init: 1 A()
%obs: 'A128' |A(n,m!1),A(n!1,m!2),A(n!2,m!3),A(n!3,m!4),A(n!4,m!5),A(n!5,m!6),A(n!6,m!7),A(n!7,m!8),A(n!8,m!9),A(n!9,m!10),A(n!10,m!11),A(n!11,m!12),A(n!12,m!13),A(n!13,m!14),A(n!14,m!15),A(n!15,m!16),A(n!16,m!17),A(n!17,m!18),A(n!18,m!19),A(n!19,m!20),A(n!20,m!21),A(n!21,m!22),A(n!22,m!23),A(n!23,m!24),A(n!24,m!25),A(n!25,m!26),A(n!26,m!27),A(n!27,m!28),A(n!28,m!29),A(n!29,m!30),A(n!30,m!31),A(n!31,m!32),A(n!32,m!33),A(n!33,m!34),A(n!34,m!35),A(n!35,m!36),A(n!36,m!37),A(n!37,m!38),A(n!38,m!39),A(n!39,m!40),A(n!40,m!41),A(n!41,m!42),A(n!42,m!43),A(n!43,m!44),A(n!44,m!45),A(n!45,m!46),A(n!46,m!47),A(n!47,m!48),A(n!48,m!49),A(n!49,m!50),A(n!50,m!51),A(n!51,m!52),A(n!52,m!53),A(n!53,m!54),A(n!54,m!55),A(n!55,m!56),A(n!56,m!57),A(n!57,m!58),A(n!58,m!59),A(n!59,m!60),A(n!60,m!61),A(n!61,m!62),A(n!62,m!63),A(n!63,m!64),A(n!64,m!65),A(n!65,m!66),A(n!66,m!67),A(n!67,m!68),A(n!68,m!69),A(n!69,m!70),A(n!70,m!71),A(n!71,m!72),A(n!72,m!73),A(n!73,m!74),A(n!74,m!75),A(n!75,m!76),A(n!76,m!77),A(n!77,m!78),A(n!78,m!79),A(n!79,m!80),A(n!80,m!81),A(n!81,m!82),A(n!82,m!83),A(n!83,m!84),A(n!84,m!85),A(n!85,m!86),A(n!86,m!87),A(n!87,m!88),A(n!88,m!89),A(n!89,m!90),A(n!90,m!91),A(n!91,m!92),A(n!92,m!93),A(n!93,m!94),A(n!94,m!95),A(n!95,m!96),A(n!96,m!97),A(n!97,m!98),A(n!98,m!99),A(n!99,m!100),A(n!100,m!101),A(n!101,m!102),A(n!102,m!103),A(n!103,m!104),A(n!104,m!105),A(n!105,m!106),A(n!106,m!107),A(n!107,m!108),A(n!108,m!109),A(n!109,m!110),A(n!110,m!111),A(n!111,m!112),A(n!112,m!113),A(n!113,m!114),A(n!114,m!115),A(n!115,m!116),A(n!116,m!117),A(n!117,m!118),A(n!118,m!119),A(n!119,m!120),A(n!120,m!121),A(n!121,m!122),A(n!122,m!123),A(n!123,m!124),A(n!124,m!125),A(n!125,m!126),A(n!126,m!127),A(n!127,m)|
```

**Comment by aznmonkey** [comment]
should be fixed now.
