### ISSUE TITLE
Pressing return in a box without filling a field make the UI restarts. 

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#434]
-> Go to Contact map 
-> Select the field between SVG and export 
-> Press return 

The UI restarts and the model is lost.

**Comment by aznmonkey** [comment]
What browser are you using? I can't seem to reproduce this in Chrome?

**Comment by feret** [comment]
I am on Safari 10.1.2 (12603.3.8). 
mac OS Sierra 
Version 10.12.6
