### ISSUE TITLE
KaDe: unary application of rules that have not be disambiguated by the fronted are not detected.

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#436]

**Comment by feret** [comment]
I have followed the track of the bug until the handling of renaming. 
The points is that the set of the agents that has an antecedent are wrong, and thus fictitious clashes are detected. 

It is possible to fix the issue in two steps: 
 - in Ode_interface.find_embeddings_unary_binary l:305 
   call the function Renaming.compose with the first arg equal to true. 
  Otherwise, when called with the identity, it will not changed the second renaming.
(whereas f \circ id_A is the restriction of f to the elements of A, which in our case is different of f). 

 - in Renaming.compose l 138. 
The computation dsts is wrong. the set of the agents in Codomain(I') that have an antecedent by I' \circ I is not equal to the set of the agents of Codomain(I') that have an antecedent by I'. 

The proper set is \{I'(v') | v' in the set of the agents of Codomain(I) that have an antecedent by I\}. 
 
Please find the corresponding patch in attachment.
[patch_to_fix_kade.patch.txt](https://github.com/Kappa-Dev/KaSim/files/1269890/patch_to_fix_kade.patch.txt)

You may test on the following example: 
%agent: A(y)
%agent: B(x,y)
%agent: C(x,y)
%agent: D(x)

%init: 1 A(y!1),B(x!1,y!2),C(x!2,y!3),D(x!3)
%init: 1 A(y!1),C(x!1,y!2),B(x!2,y!3),D(x!3)

A(),D() -> B() @ 1{1}

in which a unary reaction is expected.

**Comment by feret** [comment]
@pirbo , when you will have spare working time, could you check, correct and apply the patch ? 

Firstly, I do not know precisely the assumptions about renaming function (total functions VS partial functions), and secondly I do not know the meaning of the special_value. 
Since the code is used not only in KaDe, I do not want to damage the soundness, the safety, or the efficiency of the rest of the code.

**Comment by pirbo** [comment]
Thank you for this patch @feret.
It will probably the kill the performance of the simulator as `Renaming.compose` is very hot code intensively used during the update phase of the event loop but you need to be correct before being fast so let's apply it!

I'm super disappointed too that my recent "improvement" of Renaming did not change the performance of the simulator at all... work to do on Renaming remains!

**Comment by feret** [comment]
Sorry about this. 
I am pretty sure you will find how to improve the performance of this module soon.
