### ISSUE TITLE
Error calling Kappa from Python: 'Equality test on time requires an alarm' 

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#445]
Hi,

I believe something might have changed recently in KaSim that broke previously working code I had to call it from Python. I'm calling Kappa from Python 2 as follows:

```
import numpy as np
import kappa.kappa_sim as kappa_sim

def test():
    # set random seed
    seed = 30
    np.random.seed(seed)
    model = kappa_sim.KappaModel()
    ka_code = '''
    %agent: A()
    %agent: B()
    
    A() -> @ 'A_deg'
    B() -> @ 'B_deg'

    %var: 'A_deg' 0.01
    %var: 'B_deg' 0.01

    %init: 0 A()
    %init: 0 B()

    %obs: 'A' |A()|
    %obs: 'B' |B()|

    %mod: [T]=0.0 do $ADD 60.0 A()
    %mod: [T]=0.0 do $ADD 60.0 A()
    %mod: [T]=0.0 do $DEL |B()| B()

    %mod: [T]=20.0 do $ADD 60.0 B()
    %mod: [T]=20.0 do $ADD 60.0 B()
    %mod: [T]=20.0 do $DEL |A()| A()

    %mod: [T]=40.0 do $ADD 60.0 A()
    %mod: [T]=40.0 do $ADD 60.0 A()
    %mod: [T]=40.0 do $DEL |B()| B()

    %mod: [T]=60.0 do $ADD 60.0 B()
    %mod: [T]=60.0 do $ADD 60.0 B()
    %mod: [T]=60.0 do $DEL |A()| A()

    %mod: [T]=80.0 do $ADD 60.0 B()
    %mod: [T]=80.0 do $ADD 60.0 B()
    %mod: [T]=80.0 do $DEL |A()| A()
    '''
    model.add_code(ka_code)
    t_start = 0.
    t_end = 150
    sim = kappa_sim.KappaSim(model)
    print model.model_code
    results = sim.simulate(t_end=t_end, seed=seed)
    print "results: "
    print results
```

This is the simple wrapper I'm using to run Kappa simulations, building on @pirbo's code: [kappa_sim.py](https://gist.github.com/yarden/b2749bfd4f46ea581ca911f574326b58)

It yields the error:

```
[{u'message_text': u'Equality test on time requires an alarm', u'message_range': {u'from_pos': {u'line': 20, u'chr': 10}, u'to_pos': {u'line': 20, u'chr': 17}, u'file': u'inlined_input'}, u'message_severity': u'error'}]
```

If I remove all the perturbations (i.e., all the %mod lines) then it runs correctly. Any idea what went wrong here? 

Thanks very much! Best, Yarden

**Comment by icristescu** [comment]
Hi, 

Indeed we recently change the perturbation language. We wanted to allow periodic perturbation dependent on time. For that, we introduced an alarm, which ticks at regular time units. 

http://dev.executableknowledge.org/docs/KaSim-manual-master/KaSim_manual.htm#x1-340003.7

You can write the following Kappa code, and it should work as you expect:

```
%mod: [true] do $ADD 60.0 A()
%mod: [true] do $ADD 60.0 A()
%mod: [true] do $DEL |B()| B()

#the following perturbations are applied only once, at the specified time
%mod: alarm 20.0 do $ADD 60.0 B()
%mod: alarm 20.0 do $ADD 60.0 B()
%mod: alarm 20.0 do $DEL |A()| A()

%mod: alarm 40.0 do $ADD 60.0 A()
%mod: alarm 40.0 do $ADD 60.0 A()
%mod: alarm 40.0 do $DEL |B()| B()

%mod: alarm 60.0 do $ADD 60.0 B()
%mod: alarm 60.0 do $ADD 60.0 B()
%mod: alarm 60.0 do $DEL |A()| A()

%mod: alarm 80.0 do $ADD 60.0 B()
%mod: alarm 80.0 do $ADD 60.0 B()
%mod: alarm 80.0 do $DEL |A()| A() 

```
You can also group the perturbations that add A's as follows:

```
#in the following perturbations the alarm ticks every 40.0 time units. The perturbations are applied twice: once at 0.0 and once at 40.0 time units. For the rest of the alarm ticks, the precondition does not hold.  
%mod: alarm 40.0 (([T] < 40) || ([T] = 40)) do $ADD 60.0 A() repeat [true]
%mod: alarm 40.0 (([T] < 40) || ([T] = 40)) do $ADD 60.0 A() repeat [true]
%mod: alarm 40.0 (([T] < 40) | |([T] = 40)) do $DEL |B()| B() repeat [true]

```

**Comment by yarden** [comment]
Thanks for the clarification. It seems like there's another backwards incompatible change, though. When I change the code to use the alarm syntax (see below), and pass KaSim the same pause condition as before (``[T] > 150``), the simulation seems to run without pause:

```
def test():
    # set random seed
    seed = 30
    np.random.seed(seed)
    # make Kappa model for nutrients
    model = kappa_sim.KappaModel()
    ka_code = '''
    %agent: A()
    %agent: B()
    
    A() -> @ 'A_deg'
    B() -> @ 'B_deg'

    %var: 'A_deg' 0.01
    %var: 'B_deg' 0.01

    %init: 0 A()
    %init: 0 B()

    %obs: 'A' |A()|
    %obs: 'B' |B()|

    %mod: alarm 0.0 do $ADD 60.0 A()
    %mod: alarm 0.0 do $ADD 60.0 A()
    %mod: alarm 0.0 do $DEL |B()| B()

    %mod: alarm 20.0 do $ADD 60.0 B()
    %mod: alarm 20.0 do $ADD 60.0 B()
    %mod: alarm 20.0 do $DEL |A()| A()

    %mod: alarm 40.0 do $ADD 60.0 A()
    %mod: alarm 40.0 do $ADD 60.0 A()
    %mod: alarm 40.0 do $DEL |B()| B()

    %mod: alarm 60.0 do $ADD 60.0 B()
    %mod: alarm 60.0 do $ADD 60.0 B()
    %mod: alarm 60.0 do $DEL |A()| A()

    %mod: alarm 80.0 do $ADD 60.0 B()
    %mod: alarm 80.0 do $ADD 60.0 B()
    %mod: alarm 80.0 do $DEL |A()| A()
    '''
    model.add_code(ka_code)
    # make a Kappa environment object
    t_start = 0.
    t_end = 150
    sim = kappa_sim.KappaSim(model)
    print model.model_code
    results = sim.simulate(t_end=t_end, seed=seed)
    print "results: "
    print results
```

It keeps running without pause. Did something in the pause condition change in the interface? 

Thanks.

**Comment by hmedina** [comment]
> Final update: I find the alarm syntax very confusing because it's a bit unnatural to phrase a perturbation as happening every x time units if all you want to say is: at time [T] = t, do something.

I agree with Yarden. Don't we have a `(x [mod] x )==0 DO foo repeat foofoo` construct for this type of thing? It would make far more intuitive sense to have a clock that can be used for equality (when time is 10.0s, do this) as well as to make regular interventions (every 10s, do this).

For example, if my simulation is run for 5s, and I set `%mod: alarm 5 do $SNAPSHOT`, I'll get my snapshot, but it is a very silly use of the syntax.

I would suggest having a keyword `simTime` instead of the `alarm` clock, that would track time. Thus `simTime = x DO foo` does `foo` when one wants, and `(simTime [mod] y ==0) DO foo` can be used for time-regular foorturbations.

**Comment by pirbo** [comment]
I agree with you if the syntax is not intuitive. We need to change it.

Please see anyway why equality on time in perturbation was a disgusting hack and the rationale that leads us to introduce this notion of clock in my message to kappa-users: https://groups.google.com/d/msg/kappa-users/V0PKnqNYK5k/vGSgHvF1EgAJ

**Comment by yarden** [comment]
Thank you all for the comments. I haven't fully followed the discussion @pirbo linked to, so I'm sure I don't know all the complexities, but I agree with Hector that having some syntactic sugar for something like "do x at time T" would be very useful. 

To summarize, the behavior I was getting in the original post seemed to have been caused by using a 0.0 value for the ``alarm`` keyword. As I understand it, this reveals that the ``alarm`` semantics will not make sense for instantaneous perturbation because "do x every 0 time steps without repeating" essentially means "do nothing" whereas "do something at time 0" means you have to do something :). (While "do x every T time steps without repeating" where T > 0 still results in some action.) That's my simple-minded interpretation of the difference. Still, though, there are two results that I don't understand regarding my original program: (1) why KaSim returns output with a time stamp greater than 150 (T > 150 was the pause condition); that seems like a bug, and (2) why the simulation did not pause with the ``alarm`` syntax used for the first perturbation. Although it makes sense, in light of the semantic difference, that ``%mod: alarm 0.0 do $ADD 60.0 A()`` would not actually result in any perturbation being performed, I believe that once T > 150 the simulation should have still paused.

**Comment by icristescu** [comment]
Hi, 

> (1) why KaSim returns output with a time stamp greater than 150 (T > 150 was the pause condition)

The simulation stops when T>150, but not at T=150. If you want the second behaviour, you need an alarm. 

If your condition is T>150 then the simulation stops _at the first event_ occurring after 150 time units, lets say at 151.0. You therefore see that the simulation ends at 151.0. Is this the behaviour you observe?

> (2) why the simulation did not pause with the alarm syntax used for the first perturbation. Although it makes sense, in light of the semantic difference, that %mod: alarm 0.0 do $ADD 60.0 A() would not actually result in any perturbation being performed

You are correct; it does not make sense to have a repeating condition at 0.0 time units. The simulator now stops with an error whenever you have a smaller than or equal to 0.0 alarm.

**Comment by pirbo** [comment]
Not every wish made here has been granted but, if I'm not mistaken, all the remaining ones are now their own issue...
If so, there is no point in keeping this issue open. (Reopen if I mess up)

**Comment by yarden** [comment]
Thanks. I am going to try to upgrade to new Kappa with the revised syntax - I'm guessing the Python interface should still work.

**Comment by pirbo** [comment]
The python interface is now available in pip as the package `kappy`. You should get it from there. If you know how to autogenerate some doc from python code, I'll be more than happy to describe the API of kappy somewhere...

**Comment by yarden** [comment]
@pirbo: I just tried it but I think we have the same issue as before which is that it seems to only support Python 3:

```
Python 2.7.13 |Anaconda 2.1.0 (x86_64)| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import kappy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-513993c28888> in <module>()
----> 1 import kappy

/Users/yarden/anaconda/lib/python2.7/site-packages/kappy/__init__.py in <module>()
      3 """
      4 
----> 5 from .kappa_common import *
      6 from .kappa_rest import *
      7 from .kappa_std import *

/Users/yarden/anaconda/lib/python2.7/site-packages/kappy/kappa_common.py in <module>()
      1 """ Shared functions of api client for the kappa programming language"""
      2 from __future__ import absolute_import, print_function, unicode_literals
----> 3 from builtins import dict, str
      4 
      5 __all__ = ['SimulationParameter', 'PlotLimit', 'KappaError']

ImportError: No module named builtins
```

Is ``kappy`` required to interface with the new Kappa? I have my own interface code that wraps your ``kappa_rest.py``, ``kappa_std.py`` and ``kappa_common.py`` files - but I wonder if there were many changes made to these? Those files don't really make any commitments to the old syntax.

**Comment by pirbo** [comment]
Sorry, for some reason. My email decided that your last reply was spam so I read it only now...

I see on Google that `pip install future` is the solution to `ImportError: No module named builtins`. 
future is listed as a dependency of kappy in the setup.py so I don't understand how you can not have it but just in case can you check?

**Comment by yarden** [comment]
It turns out ``builtins`` requirement was already satisfied, i.e., it was installed. But apparently you're using something from a later version of builtins module. The solution was to call ``pip install future --upgrade``

https://github.com/dedupeio/dedupe/issues/374#issuecomment-86512217

**Comment by yarden** [comment]
Just wanted to confirm that kappy works with Python 2.7. Had to change a few variables names on my end (``legend`` instead of ``plot_legend``) but it works great. 👍
