### ISSUE TITLE
UI feature request: import ka/json snapshot

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#447]
@aznmonkey 's visualization of snapshots is highly interactive, but difficult to store to disk. One can dump snapshots as `.json`, `.png`, or even `.ka` files, but one then looses the interactivity. It would be highly desired to be able to load a snapshot, somewhere not necessarily the UI that is project-centric, to view them using the tree/node visualization.

**Comment by pirbo** [comment]
Save them a json,
making an (offline) loader/visualizer of these will be easy (but not done immediately sorry)...

**Comment by aznmonkey** [comment]
I'll try to get the VSCode extension working with the snapshots before I head out to China :).

**Comment by pirbo** [comment]
https://tools.kappalanguage.org/viz/ :-)
