### ISSUE TITLE
Inconsistent syntax for tokens in snapshots

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#454]
In the UI, snapshots use ye olde syntax for tokens:
```
%init: 18 /*1 agents*/ A(a)
%init: X <- 241.000000
```
Whereas in KaSim, this has been changed to:
```
%init: 18 /*1 agents*/ A(a)
%init: 241 X
```
KaSim's syntax is the closest to the one documented in the manual, differing only in the addition of the comment for agent number between the algebraic expression and the kappa expression. What is the official syntax supposed to be moving on?

The issue is that this broke my snapshot parser when encountering tokens, see https://github.com/hmedina/KaSaAn/issues/1

**Comment by pirbo** [comment]
Syntax of everything has been unified (for the second one)
