### ISSUE TITLE
Wrong error syntax for dead reversible rules with binary, unary, reverse rates

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#458]
The following code produces a warning about a dead rule.
```
%agent: A(n)
A(n),A(n) <-> A(n!1),A(n!1) @ 1 {1}, 1
```
The message repeats the rule, but states the rates in a different order as to they were written.
```
« 1/2 » [model.ka] Dead rule A(n), A(n) <-> A(n!1), A(n!1) @ 1, 1 {1:} 
```

Rewriting the rule with the syntax used by the UI's error message, the next error message changes and no longer displays any unary rate.
```
%agent: A(n)
A(n),A(n) <-> A(n!1),A(n!1) @ 1 , 1 {1}
```
```
« 1/2 » [model.ka] Dead rule A(n), A(n) <-> A(n!1), A(n!1) @ 1, 1 
```

The manual does not specify what is the correct syntax for rules of ambiguous molecularity that are also reversible.

Am I correct to assume:
```
[ambiguous pattern] <-> [unary pattern] @ r1 {r2}, r3 {r4}
```
  * If LHS embeds in a disconnected graph, use `r1`
  * If LHS embeds in a connected graph, use `r2`
  * RHS always proceeds at `r3`
  * `r4` is never used and must be a syntax error

If the last point is correct, the UI's error message must be corrected.

**Comment by feret** [comment]
Two things: 

1) The comment is generated by the call to Ast.print_ast_rule. 
e.g see: prepreprocess.ml  line 783. 

Let me know if I should use another function. 

2) In case of reversible rules, the direct way is unreachable if and only if the reverse rule is unreachable. 
I would propose to insert a new field in the json description of rules. 
And to ignore reverse rule in the web interface. 

Let me know.

**Comment by pirbo** [comment]
Sorry I'm completely lost.

Hector is right `A(n),A(n) <-> A(n!1),A(n!1) @ 1 , 1 {1}` is an non sense and rewriting `A(n),A(n) <-> A(n!1),A(n!1) @ 1 {1}, 1` into it is a bug...

**Comment by feret** [comment]
Indeed the function Ast.print_ast_rule is completely rock'n roll. 

I tried to correct this, but I do not why I cannot use the web interface locally anymore. 

I do: 
make clean 
make 
make site/index.html 
open site/index.html 

Then I cannot write in the "model" window. 

It is quite difficult to fix this without testing... 

Any idea?

**Comment by pirbo** [comment]
> I cannot use the web interface locally anymore.
Probably because you're using Safari and you've updated MacOS recently... I so (sorry I'm too lazy to infer the translation in english) you need to check "Desactiver les restrictions de fichier local" in the "Development" menu.

**Comment by pirbo** [comment]
That being said, we need to not hammer the same lines of code at the same time but this is Prepreprocess that I find completely rock'n roll:
- Why do you have a bidirectional field in Kappa_sig if you split bidirectional rules in 2?
(- and why do you store rates for the reverse direction if you redefine bidirectional to false in the end ...)
- Why don't you change rates when you define the Reverse rule?

**Comment by pirbo** [comment]
OK `Ast.print_rates` were indeed completely wrong!

I've pushed some changes where I don't print the rates in the rules printed by KaSa anymore. I'm not sure thats OK. Can you review them @feret? If they work for you, let's close this issue

**Comment by feret** [comment]
Dead rule detection seems to be broken on the js interface. 
Maybe should we come back to a safe situation, and just repair the Ast.print_rates function.

**Comment by feret** [comment]
As said in my previous post, the reverse of a rule is dead iff the direct rule is dead. 
To lighten the interface, when a bidirectional rule is dead, we prompt the bidirectional rule if no available labels are available, otherwise we prompt the labels of both direction of the rules. 

The previous behavior may be got back by set to false the boolean ref 
let hide_reverse_rule_without_label_from_dead_rules = ref true
in KaSa_rep/config/config.ml (currently line 98). 

When several warnings occur on a line of code, I have reordered the warnings to put the direct rule before the reverse one (when labels are available).
