### ISSUE TITLE
Weird influence map (probably related to dead rules)

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#465]
Take the toy model (stripped down to this minimality by @bgyori and @johnbachman)
```
%agent: X(kinase)
%agent: Substrate1(phos{u p})
%agent: Kinase(x)
%agent: Substrate2(phos{u p})

'Kinase_X_phosphorylation_Substrate1'
    Kinase(x[_]),Substrate1(phos{u}) -> Kinase(x[_]),Substrate1(phos{p}) @ 1
'Kinase_X_phosphorylation_Substrate2'
    Kinase(x[_]),Substrate2(phos{u}) -> Kinase(x[_]),Substrate2(phos{p}) @ 1

%init: 1 X(kinase)
%init: 1 Substrate1(phos{u})
%init: 1 Kinase(x)
%init: 1 Substrate2(phos{u})
```
Its influence map (at any accuracy) is (according to KaSa)
![capture d ecran 2017-11-07 a 17 15 09](https://user-images.githubusercontent.com/564669/32520847-714e8056-c3df-11e7-859f-44f56d631593.png)

Now, KaSa also complain accurately that the rules are dead. And if you add a rule like
```
Kinase(x[./1]),X(kinase[./1]) @ 0
```
to make them reachable, the influence map becomes (as expected)
![capture d ecran 2017-11-07 a 17 15 30](https://user-images.githubusercontent.com/564669/32520968-d083b1fe-c3df-11e7-957c-79f92cbb07be.png)
and the weird negative influences disappear.

Do you know what's going on?

**Comment by feret** [comment]
The short answer is Yes. 

The long one is that for KaSa a state is a binding site only if it occurs on the rhs of a rule or in the initial state. A site that is not a binding site (for KaSa) with a binding state on the left hand side is said to have a dead binding state. I was asked to take dead agents/sites/states into account, but I did it in a very conservative way. 

In your example, the third rule make the site/state alive. 

I have tried to be a little but more precise. please check if this is satisfying.

**Comment by pirbo** [comment]
Seems good, I'll double check whether it fixes the real issue with Ben and John tomorrow...

**Comment by bgyori** [comment]
Thanks a lot @feret and @pirbo for looking into this. I tried a few examples and everything is working as expected!

**Comment by pirbo** [comment]
Good
