### ISSUE TITLE
Command line option for old syntax

### ISSUE THREAD

**Issue by bgyori** [Kappa-Dev/KaSim#467]
I've been trying KaSim/KaSa from the latest master, and I found that using the old syntax works if I add `-syntax V3` rather than `-syntax 3` (as given in CHANGES.md). I found a lot of files in the repo such as man/scripts/influence.sh that seem to be using `-syntax 3`, should these be replaced with `-syntax V3`?

**Comment by pirbo** [comment]
We advertize indeed only `-syntax 3` while the tools in reality accept alternatives (`3` `v3` and `V3` on the one side and `4` `v4` and `V4` on the other).
There is no need to change the test suites. But, if you find that `-syntax V3` would be better in the CHANGES.md. I have no opinion and I'm happy to do so.

**Comment by pirbo** [comment]
Sorry I replied too fast!
KaSa works as I just described. KaSim and KaDE on the contrary expect an integer as argument of `-syntax` and therefore only `3` and `4` are valid options...
We need at least to synchronise the possibilities in between all tools.

**Comment by bgyori** [comment]
Oh I see, so this is not really a problem then, but the reason I was confused is that KaSa prints ```Syntax
  -syntax V3 | V4 
 (default: V4)
      Version of the lexer/parser
```
as the command line help.

**Comment by feret** [comment]
KaSa is usually a little bit permissive on the command line options. 
V3 and V4 are the officially supported options (and I need a minimal list to make the clickable list in the GUI), some variants are allowed v3, v4, 3, and 4 (without being documented). 
Yet, this is better to use V3 and V4.
