### ISSUE TITLE
KaDe output is completely bugged.

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#475]
In comments:
-> the choice of the syntax is not respected. 
-> many commas are missing.

**Comment by feret** [comment]
The problem comes from the primitives in LKappa. 

-> print_rule should request version number, and dump the rules in the good format. 
-> why using space to separate sites, and not comma ?

**Comment by pirbo** [comment]
- print_rule (as any printer) hardwired in the last syntax is made on purpose "for simplicity". The rationale being to try to pollute the code with history the least we can, I've considered as sufficient to "understand old models" and overkill to "allow to remain fully in the old world".
- commas have become facultative between sites. (It has been discussed during the syntactical debate) The argument is that it lightens a bit the syntax while staying unambiguous.
As commas are still allowed, printers can print commas indeed. My statement would be "why increase verbosity?" but if there is a reason, let's change.

**Comment by feret** [comment]
I did not want to close the issue...
