### ISSUE TITLE
enhanced Green's Function Reaction Dynamics

### ISSUE THREAD

**Issue by UnixJunkie** [Kappa-Dev/KaSim#478]
Hello,
I'm just dropping this here, since it might be of interest to implementors of KaSim:
http://gfrd.org/index
Regards,
F.

**Comment by feret** [comment]
Thank you François. 

Kappa's goal is not to model diffusion process. 
Obviously, you may self)assemble a grid and implement diffusion of agents gliding along the edges of the grid, it works reasonably well but this is not done for that. 

For agent)based diffusion tools, you may have a look at the following references: 
 
- Donald Stewart (Kappa + discrete diffusion) 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.186.2650&rep=rep1&type=pdf

- Adelinde Uhmacher's group in Rostock 
Bittig, Arne T. and Uhrmacher, Adelinde M. (2016) ML-Space: Hybrid Spatial Gillespie and Particle Simulation of Multi-level Rule-based Models in Cell Biology. IEEE/ACM Transactions on Computational Biology and Bioinformatics, PP (99). pp. 1-16. ISSN 1545-5963

- Peter Dittrich's group in Jena
Jerzy Gorecki, Konrad Gizynski, J. Guzowski, J.B. Gorecka, P. Garstecki, Gerd Grünert, Peter Dittrich (2015) 
Chemical computing with reaction diffusion processes 
Phil. Trans. R. Soc. A}, 373(2046): 20140219 (19 pages) 

Best 
Jerome.
