### ISSUE TITLE
KaSim4 reading KaSim3 file: underspecified internal state

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#483]
KaSim3 inputs files are all written in edit notation. When KaSim4 reads that, some rules fail sanity checking for underspecified internal states. For example:
```
%agent: A(s~a~b)
-A(s?) @ 1
```
Stdout:
```
Parsing foo.ka...
done
+ simulation parameters
+ Sanity checks
File "foo.ka", line 2, characters 3-4:
The internal state of agent 'A', site 's' on the right hand side is underspecified
```

Further, the message mentions a "right hand side", which we can't talk about when using edit notation. Also, it should explicitly call this an error, unless this is just a warning?

Rewritting the rule to ``A(s?) -> @ 1`` removes the issue.

**Comment by hmedina** [comment]
KaSim v4.0rc1-41-ga48fcae now properly produces pound signs in the archive file. However it can't read back the archive it just wrote. Same error.

Original V3 syntax:
```
%agent: A(s~a~b)
-A(s?) @ 1
```
Conversion to V4 syntax (UUID escaped by me, see #485):
```
//# "uuid" : "684511004"
%def: "seed" "707561117"
%def: "dumpIfDeadlocked" "true"
%def: "maxConsecutiveClash" "2"
%def: "plotPeriod" "1" "t.u."
%def: "outputFileName" "data.csv"

%agent: A(s{a b})

%plot: [T]
A(s[#])- @ 1



```
Error message when reading that:
```
File "foo_V4.ka", line 11, characters 2-3:
The internal state of agent 'A', site 's' on the right hand side is underspecified
```

**Comment by hmedina** [comment]
Addendum: notice KaSim interprets V3 wild card `?` purely as a link state specifier. It is _not_ adding the correct wildcard `{#}` when porting to V4.

**Comment by hmedina** [comment]
Side note: is `[#]` allowed? It seems like it ought to be a syntax error. We can say "I don't care about link state" by not specifying any... On the other hand `{#}` is very much required.

**Comment by pirbo** [comment]
I argue that `#` should be called "whatever" instead "don't care". It is mandatory for both link state and internal state when they are modified. Not writing any `[]` or `{}` means "don't care" but if you modify something, you do care about it. 

You may still want to modify "whatever" state it was in and that's the exact purpose of `#`
There is 1 exception (debatable according to me) to "If you modify something, you must talk about it": deletion of agent. In this case, it is OK to not write a site to mean that neither its internal state nor its linking state matter (even if it may introduce visible modification...).
