### ISSUE TITLE
Use consistent colors in the UI for agents!

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#488]
Related to #441 
An agent has one color in the circular contact map, and a different one in every graphical snapshot taken. If the user takes 10 snapshots, there is no color consistency between snapshots, and the agent will be colored 11 different ways. This makes it _very_ difficult to see changes in the reaction mixture through snapshots.

Once the contact map has decided on a color, the snapshots should inherit that choice, not invent it anew.

**Comment by pirbo** [comment]
Colors should be now shared in between snapshots.
The contact map still use its own colouring but the shared array of colors is sent to the ContactMap object (of shared/render-contactmap.js) when it is created so is it is only a question of correct plumbing.

**Comment by pirbo** [comment]
Done
