### ISSUE TITLE
KaDE omits reactions from output file?

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#494]
Hello,

I have the following Kappa model with a single degradation reaction:

```
%agent: S(x)

'R1' S(x) -> @ 'k'

%var: 'k' 0.001
%obs: 'S' |S(x)|
%init: 50 S()
```

Kappa simulates it correctly:

![image](https://user-images.githubusercontent.com/96318/35301940-f3dcc480-005a-11e8-9a74-0fba4e188383.png)

But when I try to export ODEs using ``kade``:

```
$ kade -i test.ka --ode-backend sbml
```

I get an XML file that has no reactions:

```
<listOfReactions>
</listOfReactions>
```

See the full output XML [here](https://gist.github.com/yarden/3d90098aa1fb0df4c20cf7aaafac185e). Any ideas what went wrong? Thank you.

**Comment by yarden** [comment]
Nevermind, my mistake; the ``-i`` prevents the file from being parsed.

**Comment by feret** [comment]
Indeed there are two issues here. 
1) KaDe should have warned that the list of input files is empty.
2) KaDe should accept files that are provided with the option -i (even if it is not documented), so as to prevent KaSim user to make this kind of mistake.
