### ISSUE TITLE
Connectivity export broken for visual formats

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#498]
When viewing the connectivity of a species, and exporting it as either png or svg, the resulting file is broken. The png is all white (all pixels have 255 value for R, G, and B), the svg lacks the connection nodes (as far as Firefox, Edge, or Chrome render that).

Example code:
```
%agent: A(a)
%init: 2 A(a[.])
A(a[./1]),A(a[./1]) @ 1
%mod: [E] = 1 do $STOP "state" ;
```

The screenshot via Firefox shows the correct thing:
![screenshot](https://user-images.githubusercontent.com/1588553/35487863-bb0d6ec8-044e-11e8-865a-6c0c78705aee.png)

The exported png is however all white:
![foo](https://user-images.githubusercontent.com/1588553/35487867-c5d40920-044e-11e8-995b-10c3a9a9d0c8.png)

The svg lacks all connectivity (seen in Chrome, I can't insert svgs into github issues):
![capture](https://user-images.githubusercontent.com/1588553/35487879-022bccaa-044f-11e8-8e28-6a90d8da0c59.PNG)

**Comment by pirbo** [comment]
One half is #580 Other half is #489
