### ISSUE TITLE
Nightly build for KaSim app is broken

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#500]
Hi,

I used to regularly get nightly build for KaSim app for Mac OS X here: http://www.kappalanguage.org/nightly-builds/Kappapp.app.zip

But link seems to be broken not; not sure if that was intentionally discontinued? Thanks.

**Comment by pirbo** [comment]
Absolutely not. 
http://kappalanguage.org has been integrated into the Harvard web infrastructure therefore only a Drupal instance can live there. Everything else had to move to https://tools.kappalanguage.org/. Nightlybuilds are still there but now at https://tools.kappalanguage.org/nightly-builds/ . 
There is a link to it from the new kappalanguage.org but it may be a bit hidden for now. The website needs more care...
