### ISSUE TITLE
Parse error in KaSim app 

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#501]
I'm transitioning to the new Kappa syntax and found that the latest (Dec. 2017) KaSim app on Mac OS X throws an error ``1/1 Parsing.Parse_error`` on any Kappa program I try. Normally errors (e.g., in syntax) are flagged to specific lines when they occur, but this one isn't. The ``outputs``, ``log`` and other tabs are all empty so I'm not sure how to debug it. Thanks. 

P.S. It'd be helpful to have a simple Kappa and runnable program in docs (or as default in the interactive web version) that can be copy-pasted. The first example in [docs](https://tools.kappalanguage.org/docs/KaSim-manual-master/KaSim_manual.htm) is not that simple (3 agents, some with multiple binding sites, 26 lines long) and cannot be copy and pasted because of line number prefixes and because the quotes are formatted incorrectly (``’`` instead of `` ` ``).

**Comment by yarden** [comment]
Restarting made that weird parse error go away; no idea what went wrong. But I'm leaving this here because I think the docs comment is still relevant.

**Comment by hmedina** [comment]
For having the UI load a default model on startup, and since we have a
penchant for ABC, how about the prozone model? It's three agents, two
reversible bindings, one production rule, one observable...

I'm happy to write it up, with comments, and pretty formated if useful.

Or we could just link to the raw view of one of the test suite models?

HF

**Comment by pirbo** [comment]
I've replugged the fact that the UI shows `models/abc-pert.ka` when you click on the link from kappalanguage.org but I am fully open to a simplification of the 101 example...

Error location is a gentle art. What you win somewhere, you loose somewhere else: Now that "new lines have no meaning", you can very well write
```
%mod: [true] do $SNAPSHOT "foo"
// some comments
// more comments
;
```
So for the parser, when you forget the semicolon, the unterminated sentence is not simply the first line. It is the whole 3 lines...

**Comment by hmedina** [comment]
For a simplified default basic 101 example, how about the following. Takes less than a second to run in WebWorker, shows the prozone inhibition in the plot, and a nice explanation when viewing the snapshot (in anything other than the default size view though...)

```
// Define agents
%agent: DIYa(b)
%agent: DIYb(a,c)
%agent: DIYc(b)

// Initial conditions
%init: 10 DIYa(),DIYc()

// Rules in chemical notation (LHS -> RHS)
// Bind DIYa and DIYb
DIYa(b[.]),DIYb(a[.]) -> DIYa(b[6]),DIYb(a[6]) @ 1
// Unbind DIYa and DIYb
DIYa(b[3]),DIYb(a[3]) -> DIYa(b[.]),DIYb(a[.]) @ 1

// Rules in edit notation
// Bind DIYc and DIYb
DIYc(b[./1]),DIYb(c[./1]) @ 1
// Unbind DIYc and DIYb
DIYc(b[1/.]),DIYb(c[1/.]) @ 1

// Produce DIYb from nothing
. -> DIYb() @ 1

// after 100 simulated seconds, stop and produce a snapshot called "T 100"
%mod: alarm 50 do $STOP "T 50" ;

// Measure amount of trimer
%obs: 'Trimer' |DIYa(b[17]),DIYb(a[17],c[99]),DIYc(b[99])|

```

**Comment by pirbo** [comment]
(Finally) Pushed to repo. 
Thanks
