### ISSUE TITLE
Ghost in the shell

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#504]
Stuff gets persisted even though they have been erased. To reproduce:

Point browser (e.g. Firefox) to http://dev.executableknowledge.org/try/index.html?

Type the name of agent, e.g.:
```
%agent: Sanchez(s)
```
Let it parse, get the contact map, then erase that line. Write a new model and run it. E.g.
```
%agent: A()
A()+ @ 1
%mod: [E] = 2 do $STOP "state" ;
```
View the snapshot in graph format. Why is Sanchez still present?
![screenshot-2018-2-5 kasim in browser](https://user-images.githubusercontent.com/1588553/35829127-d9aae1fc-0a8f-11e8-8bf1-04048b7f3e26.png)

Worth noting, the plain text view shows the correct agents. The graph view uses the same color for both agents, probably as both were the first agent declared and that position corresponds to dark blue. It seems the UI has persisted there be a blue Sanchez, and when drawing the snapshot, includes it in the legend.

**Comment by yarden** [comment]
I noticed this too, in a different context. If I load one model in Kappa app, visualize it, and then "unload" it (by unticking it from the menu), then its agents appear in the graph format even after I load a different model and visualize that model's snapshot.
