### ISSUE TITLE
1/1[] Bug: Link 1 is problematic! LKappa is either broken or unused! Please report. 

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#510]
The following code yields a very cryptic error message:
```
%agent:A(b c{=0 / 4})
B(a[./1]), A(b[./1] c{=c}) @ c
C(a[./1]), A(c[./1] c{=c}) @ c
```
In the second rule, A contains two `c` sites, one for counters, one for binding. Meanwhile, the signature lists one site called `c`, so A does have a `c` site used for counters. Shouldn't the error be complaining about:
 * binding a counter site?
 * stating the same site twice within an agent?

**Comment by icristescu** [comment]
The error is now `Site 'c' occurs both as port and as counter in 'A'` and it should show up now if you use a counter as a port (or a port as a rule) in rules.

**Comment by pirbo** [comment]
Thank you very much! (And don't worry about travis-ci failing, this is OCaml guys fault: https://discuss.ocaml.org/t/ann-dune-jbuilder-1-0-beta18/1635/2)
