### ISSUE TITLE
Unwanted warning from KaSa

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#511]
In the default abc model, KaSa raises the following warning:

« 1/4 » [abc-pert.ka] Rule 'mod x2' may induce non wealky reversible events in the following context: C(x1{p},x2{u},x1[.],x2[c.A]) -> C(x1{p},x2{p},x1[.],x2[.])

It says that the broken bond may not be reformed. But the interesting information is the opposite: when a bond may never be broken.

**Comment by jkrivine** [comment]
For instance KaSa raises no warning for the following model:
A(x{u}[./1]),B(x[./1]) @ 1
A(x{u}[1/.]),B(x[1/.]) @ 1

A(x{u/p}) @ 1
A(x{p/u}) @ 1

where the bond A(x{p}[x.B]) is not breakable.

**Comment by feret** [comment]
All of this is expected. 
KaSa computes non weakly reversible transitions. 
(A transition is weakly reversible if it can be reversed in 1 or more steps (in the strict (without id recycling) individual semantics, neglecting degradation and creation of agents).

In the abc, all transitions operating on C are non-weakly reversible, as show in the following local transition system: 
[agent_C.pdf](https://github.com/Kappa-Dev/KaSim/files/1780703/agent_C.pdf)

In your second example, the bond A(x{p}[1]),B(x[1]) may be broken in three steps: 
A(x{p}) -> A(x{u}) 
A(x{u}[1]),B(x[1])-> A(x{u}[.]),B(x[.])
A(x{u}) -> A(x{p}). 
Thus this step is weakly reversible. 

The property that you seem to ask is different. 
This is just the fact that a rule refinement is not exhaustive. 
This is available in complx, but not yet in KaSa (I am not sure this is related to static analysis anyway).

**Comment by jkrivine** [comment]
If you consider the following model:

%agent: A(x{u p})
%agent: B(x)

A(x{u}[./1]),B(x[./1]) @ 1
A(x{u}[1/.]),B(x[1/.]) @ 1

A(x{u/p}) @ 1

%init: 1 A(),B()

the bond A(x{p}[x.B]) is not even weakly breakable.

**Comment by feret** [comment]
Events may be weakly reversible (or not), not states. 

In your example, there is no event binding a phosphorylated A: 
You may 1) bind A and B, then 2) phosphorylate A. 
The first event is weakly reversible, not the second one. 
 (which is well detected by the analysis). 

Anyway, there is a bug in the frontend (It must be a reminiscence of the update from Syntax3 to Syntax4) in the last rule, KaSa consider the site x to be free, whereas it is not specified. 
I will see how to fix this.

**Comment by feret** [comment]
This is a discussion, not an issue.
