### ISSUE TITLE
Corruptible preference file for the UI in local ??? 

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#530]
Sometimes, after having changed and saved the preferences option for the UI (in local), 
the edit window is now longer usable (even if I restart the browser, or use another one). 
The only solution that I have found until now is to remove KaSim repository, clone the sources again from the depot, and recompile. 

Where is the preference files ? May it get corrumpted ? 

Sorry I do not have an exact sequence of steps to reproduce the bug.

**Comment by pirbo** [comment]
The preference file is in ... "the browser". It is the feature called in javascript "localStorage"... So, I have absolutely no idea until I reproduce. 
First, what webbroswer are you using?
When it is no longer usable (even after a restart of the browser), Are there errors in the javascript console?

Then I guess you're playing only with  "Show dead rules" and "Show non weakly reversible transitions", right?

**Comment by feret** [comment]
OK, thus I do not understand what happened. 
I used Safari. 
I switch "show non weakly (...)" on and save the setting as default. 
Then, the edit window was stuck. 
Then, I tried on Chrome and the window was stuck as well. 

I will look at the console if it ever happend again.

**Comment by feret** [comment]
OK I cannot reproduce today. 
I close the issue until the issue rises again.
