### ISSUE TITLE
"jump to rule" button in static influence tab

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#539]
The UI provides a visualizer for rule static influences. However navigating the rules is implemented with a serial `next` & `previous` selector. In models with a large number of rules, _having to click the_ `next` _button thousands of times is very burdensome_.

Could the rule displayed be the one where the caret is in the code editor? Alternatively, could there be a `jump to rule` option? How about a drop-down selector with the rule-names (or line-numbers if rule is anonymous)?

**Comment by hmedina** [comment]
While we are at it, what's the status of Observables? They appear in the old static influence map; will they also appear on the UI's version? @feret

**Comment by feret** [comment]
Dear Hector, 

They already appear, see for instance… 


mod x1
is influenced by	influences
ab.c	ab.c
C()+ 	Cuu
ab.c
a.c
mod x2
Cpu
Cpp

Yet it would be nice to have different pairs of colors to discriminate rules from observables. 

Cheers. 
Jérôme.

**Comment by hmedina** [comment]
What's the status of this? After a couple hundred clicks on the `Previous` button, WebSim tends to freeze...

**Comment by feret** [comment]
You should be able to click on a node on the influence map 'graph mode), or directly to a rule name (tabular mode). 

You rare right, there is no jump to rule option.

**Comment by pirbo** [comment]
:tada:
