### ISSUE TITLE
KaSim -store trace fails

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#545]
On the model abc-pert.ka, adding the intervention:
`%mod: alarm 10.0 do $ADD 10000 C(); $TRACK 'Cpp' [true] ;`
`%mod: alarm 12.0 do $TRACK 'Cpp' [false] ;`

and running KaSim with the options: 
`'KaSim' 'models/abc-pert.ka' '-u' 'time' '-l' '15' '-trace' 'essai.dat' -seed 690088503`
produces an assertion failure : 
`File "simulation/generic_rule_interpreter.ml", line 85, characters 13-19: Assertion failed`

**Comment by pirbo** [comment]
euhhh WorksForMe™ I can't reproduce.

**Comment by jkrivine** [comment]
Tu bluffes Martelli.
`Kappa Simulator: v4.0rc1-117-gecf1510ca-dirty sous mac OS X.`
The perturbations of ABC:
`%mod: alarm 10.0 do $ADD 10000 C(); $TRACK 'Cpp' [true] ;
%mod: alarm 12.0 do $TRACK 'Cpp' [false] ;`
The command line:
`./bin/KaSim models/abc-pert.ka -trace es.trace -u time -l 100`
the error:
`Command line to rerun is: 'KaSim' 'models/abc-pert.ka' '-trace' 'es.trace' '-u' 'time' '-l' '100' -seed 542210065
0.00 time units (0.00%) in 1 events
File "simulation/generic_rule_interpreter.ml", line 85, characters 13-19: Assertion failed`

**Comment by pirbo** [comment]
c'ta-dire, tu es à une version de `Wed Feb 14 15:33:22 2018`. Il s'est passé quelque trucs depuis... genre 252 commits!

**Comment by jkrivine** [comment]
OK j'ai compris je suis sur la branche ext_bases!
