### ISSUE TITLE
Inhibition incorrectly shown as arrow in Kappapp

### ISSUE THREAD

**Issue by slegare2** [Kappa-Dev/KaSim#549]
In the Kappapp, inhibitions are not represented properly. They are shown as a causal arrow. 

The following example reproduces the bug. It is a modified version of model abc-pert.ka where the binding of A to C is made to no longer require prior phosphorylation of x1.

```
/* Signatures */
%agent: A(x,c) // Declaration of agent A
%agent: B(x) // Declaration of B
%agent: C(x1{u p},x2{u p}) // Declaration of C with 2 modifiable sites

/* Rules */
'a.b' A(x[.]),B(x[.]) -> A(x[1]),B(x[1]) @ 'on_rate' //A binds B
'a..b' A(x[1/.]),B(x[1/.]) @ 'off_rate' //AB dissociation

'ab.c' A(x[_],c[.]),C(x1{u}[.]) ->A(x[_],c[2]),C(x1{u}[2])
       @ 'on_rate' //AB binds C
'mod x1' C(x1{u}[1]),A(c[1]) ->C(x1[.]{p}),A(c[.]) @ 'mod_rate' //AB modifies x1

//'a.c' A(x[.],c[.]),C(x1{p}[.],x2[.]{u}) ->
//      A(x[.],c[1]),C(x1{p}[.],x2[1]{u}) @ 'on_rate' //A binds C on x2
//'mod x2' A(x[.],c[1]),C(x1{p},x2{u}[1]) ->
//         A(x[.],c[.]),C(x1{p},x2{p}[.]) @ 'mod_rate' //A modifies x2
'a.c' A(x[.],c[.]),C(x1[.],x2[.]{u}) ->
      A(x[.],c[1]),C(x1[.],x2[1]{u}) @ 'on_rate' //A binds C on x2
'mod x2' A(x[.],c[1]),C(x2{u}[1]) ->
         A(x[.],c[.]),C(x2{p}[.]) @ 'mod_rate' //A modifies x2

/* Variables */
%var: 'on_rate' 1.0E-3 // per molecule per second
%var: 'off_rate' 0.1 // per second
%var: 'mod_rate' 1 // per second
%obs: 'AB' |A(x[x.B])|
%obs: 'Cuu' |C(x1{u},x2{u})|
%obs: 'Cpu' |C(x1{p},x2{u})|
%obs: 'Cpp' |C(x1{p},x2{p})|

%var: 'n_ab' 1000
%obs: 'n_c' 1000
%var: 'C' |C()|

/* Initial conditions */
%init: 'n_ab' A(),B()
%init: 'n_c' C()

//%mod: alarm 10.0 do $ADD 10000 C();

%mod: [T] < 10 do $TRACK 'Cpp' [true];
```
Here is a story computed from that input using KaStor. There is an inhibition between rule 'ab.c' and 'a.c' because 'a.c' requires that site x1 of C be free, while the AB complex binds to site x1.
![cflow_weakly_1](https://user-images.githubusercontent.com/23327316/51486329-b29b3600-1da0-11e9-837c-bf5bb2f6110a.png)

Here is the same story represented in the Kappapp (the incorrect arrow highlighted in red).
![screenshot_2019-01-21_16-22-43](https://user-images.githubusercontent.com/23327316/51486356-c6469c80-1da0-11e9-9896-39f5cb258180.png)

**Comment by feret** [comment]
@Pirbo, in classical graphs, do edges directives pass into json? If so are they properly interpreted in the d3 rendering?

From classical_graphs/graph_loggers_sig: 

type headkind = Normal | Vee | Tee | No_head
type linestyle = Plain | Dotted | Dashed
type options =
(...)
    | ArrowHead of headkind
(...)
   | LineStyle of linestyle
(...)
