### ISSUE TITLE
Inconsistent documentation for token grammar

### ISSUE THREAD

**Issue by althonos** [Kappa-Dev/KaSim#553]
Hi all,

In the online Kappa manual (v4 / 2018-09-14), token names are supposed to be declared as `Label`s according to Grammar 12, yet in the following example they are declared with a `Name`. Furthermore, there is no actual declaration for the `<token-name>` rule which appears in Grammar 7. In my understanding a token name should be a `Name` everywhere, but I could be wrong.

**Comment by feret** [comment]
Thank you for your feedback.

You are right. 
In grammar 7, "token name" should be replaced with “declared_token_name"
In grammar 12, “declared_token_name” should be declared as “Name” 

Best. 
Jérôme.

**Comment by pirbo** [comment]
Finally fixed... Sorry for the delay and thanks for reporting!
