### ISSUE TITLE
Bug with self loops

### ISSUE THREAD

**Issue by slegare2** [Kappa-Dev/KaSim#559]
There seem to be a problem with the detection of intra-agent bonds, which causes them to never break.
In this small example, I have agent A which can form an intramolecular bond between its sites x and y.
```
%agent: A(x y)
%init: 10 A()

'A binds intra'     A(x[./1] y[./1]) @ 0.1
'A unbinds intra'   A(x[1/.] y[1/.]) @ 0.01

%obs: 'A self' |A(x[1] y[1])|
```
When I run this simulation, I get 10 instances of rule "A binds intra" and then I reach a deadlock. I also get zero instances of A(x[1] y[1]) at all time in the output.csv.
Maybe I made some mistake in my unbinding rule, but I expected the intramolecular bond to form and unform repeatedly in that simulation.

**Comment by hmedina** [comment]
I get a deadlock too with this (slightly) smaller code:
```
%agent: A(x y)
%init: 10 A(x[1] y[1])
'A unbinds intra'   A(x[1/.] y[1/.]) @ 0.1
%mod: [E] > 5 do $STOP ;
```

Log file contains:
```
+ Building initial simulation conditions...
 -variable declarations
 -rules
 -interventions
 -observables
 -update_domain construction
 5 (sub)observables 2 navigation steps
 -initial conditions
Random seed used: 655323245
Warning: A deadlock was reached after 0 events and 0.000000E+00s (Activity = 0.00000)
```

KaSim in browser, whatever version is running today in the cloud.

**Comment by hmedina** [comment]
This may be more serious; the following code also produces a T0 deadlock:
```
%agent: A(x y)
%init: 10 A(x[1] y[1])
'A unbinds intra'   A(x[1] y[1]) -> . @ 0.1
%mod: [E] > 5 do $STOP ;
```
The `deadlock.ka` snapshot contains the right mixture, 10 copies of intra-bound monomer. But the rule is not embedding in it?

**Comment by hmedina** [comment]
Changing the LHS bond pattern to wildcards allows events, as the following does not deadlock and produces the expected reduction in the monomer pool.
```
%agent: A(x y)
%init: 10 A(x[1] y[1])
'A unbinds intra'   A(x[#] y[#]) -> . @ 0.1
%mod: [E] > 5 do $STOP ;
```

**Comment by pirbo** [comment]
This is SUPER serious indeed and occurs at 2 hours of me living with no internet connection for a week as Murphy loves it...
Sorry, I'll look into it first thing when I'm back!

**Comment by feret** [comment]
When compiling into KADE, the rule 'A unbinds intra' is not taken into account.
