### ISSUE TITLE
Snapshot cannot be visualized on tablets

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#564]
Double clicking on the snapshot visualizer does not trigger the opening of the graph window on IPAD.

**Comment by hmedina** [comment]
Single tap on iOS triggers the on-hover action, double tap triggers the click action ([source](https://w3reign.com/double-tapclick-issue-on-iosiphone-ipad-devices-solved/)). There doesn't seem to be a tap arity that would trigger the double click action (maybe four taps? If only iOS behaved like Windows, where a tap is a click :p).

That said, as the snapshot viewer in the GUI has no usage for the single click, why do we have the double click? Could we not drop double click and just use the single-click? I.e. single-click on a patch to open its level2 network, click on the "back to root" to go back to the patch layout.

**Comment by jkrivine** [comment]
Yes I support the single click to expand the graph view of snapshots (if that can help using the editor on iPads)

Le 16 avril 2019 21:26:57 GMT+02:00, Hector Medina <notifications@github.com> a écrit :
>Single tap on iOS triggers the on-hover action, double tap triggers the
>click action
>([source](https://w3reign.com/double-tapclick-issue-on-iosiphone-ipad-devices-solved/)).
>There doesn't seem to be a tap arity that would trigger the double
>click action (maybe four taps? If only iOS behaved like Windows, where
>a tap is a click :p).
>
>That said, as the snapshot viewer in the GUI has no usage for the
>single click, why do we have the double click? Could we not drop double
>click and just use the single-click? I.e. single-click on a patch to
>open its level2 network, click on the "back to root" to go back to the
>patch layout.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kappa-Dev/KaSim/issues/564#issuecomment-483810722

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by hmedina** [comment]
While you're at it:
1. `count` mode should state the **count** of entity hoverd/clicked/darkened (currently, it does)
1. `size` mode should state the **size** of entity (currently, it states just the count)
1. `mass` mode should state **both count & size** of entity  (currently, it states just the count)
