### ISSUE TITLE
Paste (Ctrl-v) does not work in the Kappapp

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#568]
I can copy text from the code mirror editor inside the app but no way to paste (even what I just copied...)
Probably related to the switch to Electron. An opinion @yvan-sraka ?

**Comment by yvan-sraka** [comment]
Yes, I just figured out that!

It seems that we have to enable something in `main.js` config to allow us copy-pasting after packaging electron: https://github.com/electron/electron/issues/2591

**Comment by yvan-sraka** [comment]
I follow what's adviced in the electron issue discussion, and fixed it in the PR https://github.com/Kappa-Dev/KaSim/pull/570

I tested it on my MacBook, I can now paste code in Kappa editor!

**Comment by pirbo** [comment]
Euhhh, we're not there yet. I've just download the last MacOS binary but when I open it I see :
![Capture d’écran 2019-04-19 à 13 32 32](https://user-images.githubusercontent.com/564669/56422439-a5122100-62a7-11e9-8fb9-6f87f2d80bac.png)

**Comment by yvan-sraka** [comment]
Oups, I just paste two times the same code ... sorry for the dumb mistake, I put a fix of my fix in the PR https://github.com/Kappa-Dev/KaSim/pull/571 !
