### ISSUE TITLE
documentation for binary releases?

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#575]
I've been trying to install the new suite. I don't see any readme associated with ``KappaBin`` (https://github.com/Kappa-Dev/KaSim/releases/download/v4.1beta/KappaBin.zip) though. The github page says it has binaries for Mac OS X as well as Windows. Most of the files look like windows-related (Kappapp.exe, various dlls). I don't see a read me and wasn't sure if there are Mac OS X binaries here? ``resources/bin'' looks like all *.exe files. 

Update: nevermind; I see that Kappa.app is the right thing; I had mistakenly assumed it was just the GUI. It'd be good to add a note explaining what is the Windows binary (since ``KappaBin'' doesn't necessarily mean Windows). Thanks.

**Comment by pirbo** [comment]
I tried to make the name on the release page clearer
