### ISSUE TITLE
pattern variables

### ISSUE THREAD

**Issue by nilsbecker** [Kappa-Dev/KaSim#576]
When writing some of my first Kappa files, I had the wish to name and reuse a pattern. Patterns of multimers can get quite long, and it would be nice to be able to reuse them across rules and observables. e.g. something like this:

`PAT1 = A(x[1], internal {i1}), B(y[1])`

and then 

`'rule' PAT1 -> something @ something`

`%obs 'someobservable' |PAT1|`

there are possibly issues about scope of the link numbers defined in the pattern etc. but already a primitive implementation that just does textual replacement seems potentially useful to me.

**Comment by glucksfall** [comment]
I think KaSim cannot interpret any declaration of that kind. I would be surprised if '%var:' can be used to define an agent pattern and use the variable to define rules and observables.

**Comment by feret** [comment]
Hello, 

Rodrigo, you are right. 
What you would need is a macro-processing language as metakappa?
Unfortunately, development has biffurcated when we passed from simplx to KaSim 3, and metakappa syntax is not compatible with KaSim’s one. 

Note also that metakappa solution, does not involve complex matching during the solution, the tools was just expanding the rules with macros into rules without (hence enumerating all the potential cases of application). 

Cheers. 
Jérôme.

-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr
