### ISSUE TITLE
duplication of complexes

### ISSUE THREAD

**Issue by nilsbecker** [Kappa-Dev/KaSim#577]
I am trying to implement a rule that duplicates a complex, including its internal state configuration. 

Concretely, let's say a monomer has interface `E(i1{a b c}, i2{d e}, x[y.E], y[x.E])`. Each monomer thus has 6 internal states, and a trimer has already 6^3. It's infeasible to write exact duplication of trimers explicitly with definite values of the internal states. I have not found a way to describe this in Kappa. Is there one?

**Comment by glucksfall** [comment]
Hello,

Rules should be explicit. If you want to duplicate A you need to write something like A -> A + A. You could try using PySB, where you can define a python variable as the complex, and use that variable to write a simple rule. Then when exporting to kappa, PySB will translate the variable to the full agent definition. I used it before to duplicate a long chain of agents.

Another thing to keep in mind is that if you want to duplicate an agent, polymerize an agent or make a ring of agents. Those three reactions have associated three different rules.

Also, you could ask your doubts through the Gitter channel https://gitter.im/Kappa-Dev/KaSim

Best regards,
PS: I'm not a developer of KaSim... I don't know every trick the language allows to do.

**Comment by nilsbecker** [comment]
@glucksfall thanks. i will investigate the PySB route. however, i am doubtful that it will work; in my actual use case, the complexes that need to be duplicated are 9-mers, which have around 1E6 internal states. even if generated programmatically, the rule set would become too big. 

to me this seems a use case for which kappa is not flexible enough? or maybe there is another way to represent the internal states, e.g. fake additional agents that implement the internal states? but then i think i would still need a way to express something like `E(arbitrary fake ligand bound (one of 6))-> 2 x E(the same ligand bound)`

**Comment by nilsbecker** [comment]
one possible way to represent this situation would be to allow state-valued variables on the LHS and RHS of a rule , e.g. `E(i1{_X})-> E(i1{X}), E(i1{X})` where `_X` is a variable that captures the state on the left and `X` is the same value on the right. obviously i have no clue if something like that is a simple extension of the simulation loop or if it is incompatible with the architecture of kappa.

**Comment by vd1** [comment]
Hello

You could try to do it the way nature does it.

+ add a `rep` site to E
+ make a new agent REP with a `co-rep` site and a `train` site
+ add a rep/co-rep landing rule where by REP lands on the site `rep` of E
provided its `x` is free - the `x-most` monomer
+ add (rougly 6x2) sliding rules for REP to duplicate one E at a time
attaching them to the growing train
+ add a rule to terminate duplication by detaching REP and its trailing
copy when REP reaches the y-most monomer

Cheers
Vincent

**Comment by feret** [comment]
Very nice indeed!!!

**Comment by nilsbecker** [comment]
@vd1 thanks, that does sound like a possible answer! 

i don't want or need the replication intermediates, but guess i could just not observe them. i'll give it a go i think.

one thing to beware of is that the availability of polymerases (REP) should not become limiting as the population grows. to avoid that, it might be possible to make the polymerase fully implicit, building the replication fork into E as another residue. to be seen.

as a more general comment, i think that supporting rules with variables would increase the expressiveness of kappa a lot, but may come at a price in terms of feasibility of static analysis and potentially, speed (although i don't see why it would make the core simulation loop slow necessarily)

**Comment by hmedina** [comment]
You can also play around with the rates. Make the extension step have an
infinite rate, and the ejection one too. Given a finite attachment rate,
you'll always finish a replication process before attaching a new one.

I use a variant of this for degrading arbitrarily long polymers, using a
PacMan agent :)

**Comment by glucksfall** [comment]
One of my first models was to reproduce replication of a bacterial plasmid (https://www.sciencedirect.com/science/article/pii/S0006291X17323173). In the model (as well in nature), replication cannot restart at the origin until the deletion of the RNA primer. For simplicity, the rule that duplicates the plasmid also deletes the RNA at the origin.

What I didn't follow was "one also wants to prevent multiple replication forks progressing on the same complex at the same time". Do you mean prevent reinitiation at the origin of replication? Because there are multiple forks in eukaryotes (reply to " it involves knowing if a fork exists somewhere down the polymer").

**Comment by vd1** [comment]
I think he thought of another REP landing on the growing copy rather -
which is not possible with existing template based polymerases. But maybe
possible with synthetic ones.

**Comment by nilsbecker** [comment]
@hmedina ah good to know that infinite rates do actually work and don't lead to overflow errors. @glucksfall @vd1 yes, i wanted to avoid re-initiation of replication at the start site while a previous round of replication is not finished. i know this does exist in bacterial replication, but for my present use case i don't want it. it seems that infinite replication progress rates can solve that problem.

**Comment by vd1** [comment]
I think I misunderstood then - i thought you wanted to prevent the
duplication of the nascent chain

**Comment by nilsbecker** [comment]
ah yes, i also don't want to allow duplication of the nascent chain. that seems to be a similar problem since the nascent end can in principle also accept a new REP. with infinite rates this should also disappear i think

**Comment by vd1** [comment]
incidentally, infinite rates are creating a special compartment of
"infinite" events which are prioritised - there is no guarantee on the
order in
which the infinite events are selected by the simulator, so it can become
difficult to understand the implications (if the infinite
event structure ahead has conflicts).
