### ISSUE TITLE
Toplevel syntax for repeat perturbations?

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#586]
What exactly is the syntax one should use at the toplevel (aka interactive mode) for perturbations? The manual is unclear, and I get syntax errors for the standard kappa file syntax. Trying without the `%mod:` keyword produces the same cryptic error of "unrecognized command", without stating what is the command that was not recognized.

![Capture](https://user-images.githubusercontent.com/1588553/58044801-ad5fb500-7b0e-11e9-9bfd-ed97002a49ca.PNG)

**Comment by pirbo** [comment]
Like in the GUI, you don't write a perturbation in the cli but only interventions aka the `$SNAPSHOT;` part in your example...

**Comment by hmedina** [comment]
I see, so this is not a bug. I'll put add stuff to #582 then.
