### ISSUE TITLE
Influence map at level Realisable raises exception (Direct doesn't)

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#587]
On [ryan_xor.ka.txt](https://github.com/Kappa-Dev/KaSim/files/3199743/ryan_xor.ka.txt)

running `bin/KaSa --reset-all --compute-influence-map --influence-map-accuracy-level Realisable ryan_xor.ka` raises 
```
error: file_name: KaSa_rep/frontend/ckappa_sig.ml; message: line 356; exception:Exit
error: file_name: KaSa_rep/frontend/cckappa_sig.ml; message: line 641; exception:Exit
error: file_name: KaSa_rep/frontend/ckappa_sig.ml; message: line 356; exception:Exit
error: file_name: KaSa_rep/frontend/cckappa_sig.ml; message: line 641; exception:Exit
```
while
`bin/KaSa --reset-all --compute-influence-map --influence-map-accuracy-level Direct ryan_xor.ka` works well.

I tried to minimised the model but as I was removing lines (of `%obs:`), the number of exception raised was increasing! So I left it as it.

**Comment by feret** [comment]
I am a bit surprised in the preprocessing to receive an empty list for the binding state associated to [#] rather than [LKappa.LNK_ANY,position]

I would have expected the following: 
A(x) => [] 
A(x[#]) => [LKappa_LNK_ANY,pos] 

Did I miss anything ?

**Comment by pirbo** [comment]
No you're right but where when do you receive an empty list?

**Comment by feret** [comment]
IN the following test case: 
%agent: A(x{u p})

A(x{u/p}) @1
A(x{u/p}[#]) @1

%init: 10 A()

I would expect an empty list for the first rule, and LNK_ANY in the second one. 
I understand they are observationally equivalent, but I would have the opportunity to go back to the string representation from ckappa and I cannot do it if the encoding is not one to one.

**Comment by pirbo** [comment]
This is what the parser is doing, we really need to have a look together...

**Comment by feret** [comment]
Sorry you are right. 
In example that is attached in the first message of this issue, I was looking at empty list as a binding state and found none in the rules, but the problem is in the observables. 
Thus, there are no problem and  commit 6bb2b28, extend KaSa frontend to deal with missing bondong states.

**Comment by feret** [comment]
Mes plus plates escuses :-)
