### ISSUE TITLE
how to debug reactions

### ISSUE THREAD

**Issue by nilsbecker** [Kappa-Dev/KaSim#590]
hi, i have a set of reactions which yield a product species which i did not expect to be possible. to debug my rules, i have created a stopping condition that stops when the offending species first appears. what i would like is to be able to see what reaction event created it. is there a way to achieve this?

(please feel free to close this and point me to a different place if this question is not appropriate for the github issues list)

**Comment by nilsbecker** [comment]
from the recent bioinformatics article i gathered that 'stories' are probably what i could use, however i was unable to find documentation on those?

**Comment by nilsbecker** [comment]
after some digging in outdated docs, i found a way to make it work using the CLI programs KaSim and KaStor. still no luck with the GUI. for now, i can work with my solution.

**Comment by pirbo** [comment]
If your simulation is not too big, you can do that in the GUI. Check "Store the trace" in the "preferences" (top right of the screen). redo your simulation with $TRACK directive. Now the tab "story" is available...

**Comment by nilsbecker** [comment]
ah i see, nice. it would be great to make this feature more discoverable
