### ISSUE TITLE
ocamlgraph / parsing and analysis of snapshots

### ISSUE THREAD

**Issue by nilsbecker** [Kappa-Dev/KaSim#591]
hi, 

what is the best way to save snapshots in order to read them back in for analysis with `ocamlgraph`? e.g. is there a way to read in `.ka` files in ocaml and make them into an ocamlgraph graph? or json? alternatively, is there a python library which can parse snapshot output into a graph?

**Comment by nilsbecker** [comment]
i found `parse_dot_file` in ocamlgraph. is this the way to go? i.e. save snapshots as `.dot` then parse using that function?

**Comment by nilsbecker** [comment]
hmm. in `kappa-library` there seem to be functions for serializing/deserializing mixture graphs to json. but i can't really figure out how to use them. 

here is what i actually want to do: from a snapshot, pick out all complexes that follow a certain structure, namely being a linear chain starting in a node with site `n{left}` and ending with a node with `n{right}`. then i want to walk along these chains and compile a list of site states along the way. i figured ocamlgraph is probably a good tool to do that but maybe kappa-library has all that is needed?

**Comment by hmedina** [comment]
Hi Nils,

There are some rudimentary Python scripts that may help with what you are
looking for at:
https://github.com/hmedina/KaSaAn

They don't have support yet for traversing a site graph, and I don't have
the time to figure out an implementation. It can only check agent-by-agent
(locally, without following bonds); that said, it may have enough for your
usecase.

Is a connected set of N agents with N-1 bonds sufficient to call that a
linear polymer in your case? If so, KaSaAn can get both pieces of
information and identify them.

Iterating over the set of agents within a complex and querying a specific
state is also straightforward.

As for a way of getting the head or tail, if those are the two agents in
the complex that have a single bond, or a specific state, that information
is also obtainable.

Best,
Hector

**Comment by nilsbecker** [comment]
thanks, that looks like it could work! i will give it a try. that said, if someone knowns a way to get snapshots imported as ocamlgraph graphs for general purpose graph analysis, i would still be interested, too.

**Comment by nilsbecker** [comment]
i cloned and tried to install it with `python setup.py install`. i can `import KaSaAn` but there are no classes available? in the build/ directory i get just a pretty empty __init__.py, nothing else?!

**Comment by hmedina** [comment]
The classes are documented on the readme.
Try importing them from the core module, i.e.

from KaSaAn.core import KappaSnapshot

**Comment by nilsbecker** [comment]
no, the installation results in a empty module:
```
[ins] In [1]: from KaSaAn.core import KappaSnapshot
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f43c2e1fd491> in <module>
----> 1 from KaSaAn.core import KappaSnapshot

ModuleNotFoundError: No module named 'KaSaAn.core'

[ins] In [2]: import KaSaAn

[ins] In [3]: KaSaAn.core
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-d92c4a994084> in <module>
----> 1 KaSaAn.core

AttributeError: module 'KaSaAn' has no attribute 'core'
```
somehow it finishes the installation but nothing is actually available

**Comment by nilsbecker** [comment]
i tried again by starting ipython from the root directory of KaSaAn -- i can now import it successfully. so it's only the actual installation via setup.py which fails!

**Comment by nilsbecker** [comment]
just fyi, although the installation is still not working normally, i can load the module; i have used the query functions to write a 'parser' that finds one end and then follows the links along the chain; so this is working for me now. thanks!

(for future use, i am still interested in a way to read snapshots into a ocamlgraph compatible structure. i suspect some functions in KaSim must be able to (almost) do that)

**Comment by pirbo** [comment]
Hi, Sorry to reply that late.
If you speak OCaml, the easiest is to load a snapshot from its JSON representation and to work on it. In a toplevel, It looks like
```ocaml
#use "topfind";;
#require "bigarray";;
#require "kappa-library.runtime";;

let load_snapshot_file fname =
  let ic = open_in fname in
  let bf = Lexing.from_channel ic in
  let st = Yojson.init_lexer ~fname () in
  let out = Kappa_runtime.Data.read_snapshot st bf in
  let () = close_in ic in
  out

open Kappa_mixtures.User_graph

let example = (load_snapshot_file "toy.json").Kappa_runtime.Data.snapshot_agents
```
The translation to an ocamlgraph structure is not obvious to me and would probably lose some information into the site-graph -> plain-graph translation but I would be curious to see how you're doing it if you have a way. You can also very well work directly on the User_graph. (I fantasize code from the element you've given :-), I take the contact map `A(x[y.A] y[x.a] n{left middle right} s{stuff to store}`)

```ocaml
let rec find_n_left complex i =
  if i < 0 || i >= Array.length complex then None
  else match complex.(i) with
    | None -> find_n_left complex (succ i)
    | Some ag ->
      if ag.node_type = "A" then
        match ag.node_sites.(2 (* "n" *)).site_type with
        | Counter _ -> assert false
        | Port p ->
          if p.port_states = Some ["left"] then Some i
          else find_n_left complex (succ i)
      else find_n_left complex (succ i)

let rec gather_s_states_upto_n_right complex acc ag =
  match complex.(ag) with
  | None -> assert false
  | Some ag ->
    let () = assert (ag.node_type = "A") in
    let state_s = match ag.node_sites.(3 (* "s" *)).site_type with
        | Counter _ -> assert false
        | Port p -> match p.port_states with
          | Some [h] -> h
          | _ -> assert false in
    match ag.node_sites.(2 (* "n" *)).site_type with
        | Counter _ -> assert false
	| Port p ->
          if p.port_states = Some ["right"] then List.rev (state_s :: acc)
          else match ag.node_sites.(1 (* "y" *)).site_type with
	| Counter _ -> assert false
	| Port p -> match p.port_links with
          | LINKS [(ag',site')] ->
            let () = assert (site' = 0 (* "x" *)) in
            gather_s_states_upto_n_right complex (state_s::acc) ag'
          | _ -> assert false

let get_s_states snapshot =
  List.fold_left
    (fun acc (_nb,complex) ->
       match find_n_left complex 0 with
       | None -> acc
       | Some i ->
         let out = gather_s_states_upto_n_right complex [] i in
         out::acc)
    [] snapshot.Kappa_runtime.Data.snapshot_agents
```

**Comment by nilsbecker** [comment]
> If you speak OCaml, the easiest is to load a snapshot from its JSON representation and to work on it.

thanks! in the meantime i made a version of this using plain `Yojson.Basic` which was doable but a bit tedious. i think i ended up with something similar to your solution (except using association lists instead of arrays to represent complexes, but performance is not an issue in my case). in the future i will certainly use the User graph functions you point out. 

about ocamlgraph, i agree that the mapping is not obvious. either one loses information about site properties or one would have to blow up an agent into multiple graph-nodes. alternatively, it might be possible to list all the sites as a cargo for the node and the information which link is attached to which site, as a link label? not sure.

in any case, for my use case losing information would be totally fine. for me the representation of agent-agent links, discarding from which to which site, is enough, and i imagine that to it could be of interest to others who want to extract/analyze the composition of generated complexes. i guess this kind of reduced representation would map to ocamlgraph more or less straightforwardly.
