### ISSUE TITLE
outputting snapshots in JSON format with KaSim

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#593]
This is more of a feature request - since I believe it's not possible to do this - but it'd be nice to get snapshots from ``KaSim`` in JSON format. This is possible to do through the GUI by manually loading a snapshot and saving it as JSON. As far as I can tell, ``KaSim`` on the command line doesn't have an option to do this. If you call a model that dumps a snapshots, e.g.: ```%mod: alarm 10.0 do $SNAPSHOT;``` it will by default produce *.ka files that are in non-JSON format. Thanks!

**Comment by pirbo** [comment]
Give an explicit name with the extension `.json` to the snapshot to produce and it will be in the JSON format. For example: `%mod: alarm 10.0 do $SNAPSHOT "foo.json";` It is simply that the default name for snapshots is "snap.ka" and therefore in kappa syntax...

Personal message :-) : I'm actively hamering the software to understand why kappy is so inefficient at generating snapshots... I do reproduce but I can't understand where it comes from, there is no good reason!

**Comment by yarden** [comment]
@pirbo: thanks! regarding "foo.json" - for a single snapshot it works, but if I repeatedly dumping snapshots (say every ``$PLOTENTRY``) then doesn't this string get interpreted as the prefix of the snapshot or its name? e.g.,

```
%mod: alarm 1.0 do $SNAPSHOT "snap.json"; repeat [T] < 2
```

I'm not sure how to distinguish snapshot name/prefix from format?

**Comment by hmedina** [comment]
You can also name snapshots with event or time values, e.g.
`$SNAPSHOT "snap_time_".[T].".ka"`, which will insert the time value (time as a float, probably has a period in it somewhere) into the name. The `.` serves as concatenator for strings. The same for using `[E]`, or other variables; it may even work with _observables_ ...

**Comment by yarden** [comment]
Thanks @hmedina. I figured out how to do what I want from KaSim. Here's a complete example that dumps JSON snapshots at every event. Quite large. (@pirbo I think this shows that the slowness in dumping JSON snapshots is specific to kappy - I wanted to test if it's maybe a problem with the JSON serializer, but it seems pretty fast when I do it from command line.)

```
%agent: C()
%init: 1000 C()
%var: 'event_count' 0
'R1' C() -> . @ 0.05

%obs: 'C' |C()|

%mod: do $PLOTENTRY; $SNAPSHOT "snap_".event_count.".json"; $UPDATE 'event_count' 'event_count'+1; repeat [true]
```

**Comment by yarden** [comment]
> Give an explicit name with the extension `.json` to the snapshot to produce and it will be in the JSON format. For example: `%mod: alarm 10.0 do $SNAPSHOT "foo.json";` It is simply that the default name for snapshots is "snap.ka" and therefore in kappa syntax...
> 
> Personal message :-) : I'm actively hamering the software to understand why kappy is so inefficient at generating snapshots... I do reproduce but I can't understand where it comes from, there is no good reason!

To close the thread on this: I figured out the inefficiency in kappy, I believe, and it was due to the fact that the output was being read one character at a time. When retrieving a long string corresponding to a JSON snapshot, the cost is largest, hence the behavior of snapshot dumping appearing so inefficient. I rewrote the IO interface in ``kappa_std`` to read the output in chunks instead (see: https://github.com/yarden/KaSim/blob/master/python/kappy/kappa_std.py#L97)
