### ISSUE TITLE
manual bug: "[mod]", not "mod", for modulo

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#595]
The [manual](https://kappalanguage.org/sites/kappalanguage.org/files/inline-files/Kappa_Manual.pdf) gives this example on p. 24:

```
// periodic snapshots of the system state
%mod: ( [E] mod 1000 ) = 0 do $SNAPSHOT ”abc.ka”; $SNAPSHOT ”abc.dot”;
repeat [true]
```

but this won't run; the ``mod`` arithmetic operator should actually be ``[mod]``. I found this out by searching the repo and finding [this example](https://github.com/Kappa-Dev/KaSim/blob/422e1c6ade478e5ad71670150dd77b55b35535a8/models/test_suite/cflows/abc-cflow/abc-cflow.ka). It'd be useful to have a listing in the manual of all the exposed arithmetic operations that are allowed in perturbations. 

Also, just wanted to flag this in case there are plans to eliminate more exotic arithmetic operations like ``[mod]`` in the future. If there are, let me know, because otherwise I'm planning to use them heavily :). 

P.S. I'd have happily made this into a pull request but the manual TeX isn't on github as far as I know.

Thanks, Yarden

**Comment by pirbo** [comment]
Removing arithmetic operation is not planned, go ahead :-)

The guardian of the manual is @plucky Only him can fix that :-)

**Comment by plucky** [comment]
> Removing arithmetic operation is not planned, go ahead :-)
> 
> The guardian of the manual is @plucky Only him can fix that :-)

Typo in manual is fixed. (The BNF was correct, see Table "Grammar 7" and Appendix.)
wf

**Comment by plucky** [comment]
Fixed.
