### ISSUE TITLE
%mod function is not working

### ISSUE THREAD

**Issue by ajeet619** [Kappa-Dev/KaSim#612]
As mentioned on the page 25 of the manual.

_// periodic snapshots of the system state
%mod: ( [E] mod 1000 ) = 0 do
$SNAPSHOT ”abc.ka”; $SNAPSHOT ”abc.dot”;
repeat [true]

% mod function is not working

it gives the following error

"Incorrect beginning of sentence"

I don't know what mistake I am making as I am using the same abc model given in the manual.

**Comment by jkrivine** [comment]
Did you try Adding a semi colon:
> %mod: ( [E] mod 1000 ) = 0 do
> $SNAPSHOT ”abc.ka”; $SNAPSHOT ”abc.dot”;
> repeat [true] ;
> 

Jean Krivine
CNRS researcher at IRIF
+33157279263
www.irif.fr/~jkrivine

**Comment by ajeet619** [comment]
Yes I just did that but it didn't work.
It is showing the same error

**Comment by pirbo** [comment]
The "mod" algebraic operation has to be put in square bracket as any of the algebraic operations.
```
%mod: ( [E] [mod] 1000 ) = 0 do
$SNAPSHOT ”abc.ka”; $SNAPSHOT ”abc.dot”;
repeat [true]
```
works as expected and is (now?) in the manual
