### ISSUE TITLE
Supplying initial condition in a file

### ISSUE THREAD

**Issue by ajeet619** [Kappa-Dev/KaSim#614]
Is it possible to supply initial condition to a Kappa script in a separate file?  I am asking this because I want to use one of the snapshots as the initial condition.

**Comment by hmedina** [comment]
Yes, use the '-mixture [file]' option from the command line. It was
developed for precisely this reason. KaSim will ignore '%init:' commands
except those in the file specified. E.g.

'$ KaSim -i ruleset.ka -i otherRules.ka -mixture someSnap.ka'

**Comment by hmedina** [comment]
If this doesn't answer your question, feel free to reopen the issue, or post a message to the Kappa forum: https://groups.google.com/forum/#!forum/kappa-users
