### ISSUE TITLE
Runtime error Node.bit_encode: Cannot encode view in one word

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#73]
Agents whose signatures include many multi-state sites sometimes cause a runtime error when attempting to print snapshots.
```
%agent: ABC(S1~a~b~c~d~e, S2~a~b~c~d~e, S3~a~b~c~d~e, S4~a~b~c~d~e, S5~a~b~c~d~e, S6~a~b~c~d~e, S7~a~b~c~d~e, S8~a~b~c~d~e, S9~a~b~c~d~e, S10~a~b~c~d~e, S11~a~b~c~d~e, S12~a~b~c~d~e, S13~a~b~c~d~e, S14~a~b~c~d~e, S15~a~b~c~d~e, S16~a~b~c~d~e, S17~a~b~c~d~e, S18~a~b~c~d~e, S19~a~b~c~d~e, S20~a~b~c~d~e)
'ABC/' -> ABC() @ 1.0
'ABC\' ABC() -> @ 1.0
%mod: [T] > 1 do $SNAPSHOT "T1"
```
In the above code, the likelihood of error increases as sites of the form "Sx~a~b~c~d~e" are added, or as the number of states per site increases. The error is much less frequent, if at all present, if the the multiple states are absent (e.g. ABC(S1, S2,...) ), or if sites have much less possible states (e.g. ABC(S1~a, S2~a, ...)).

**Comment by pirbo** [comment]
KaSim4 has dropped this encoding into Int64
