### ISSUE TITLE
Link type combinatorics

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#80]
As per the KaSim Manual:
"```%var: 'ab' A(x!y.B),B(y!x.A)``` will count the number of As whose site x is connected to a site y of B, plus the number of Bs whose site y is connected to a site x of A."

Should it not be the combinatoric of the pattern, instead of the addition of the agents? The simulator does give the combinatoric result. For example:

```
%agent: A(w)
%agent: B(x,y)
%agent: C(z)
%init: 3 A(w!1),B(x!1)
%init: 5 B(y!1),C(z!1)

%obs: 'ab' A(w!x.B),B(x!w.A)
%obs: 'bc' B(y!z.C),C(z!y.B)
%obs: 'AB' A(w!x.B),B(y!z.C)
```

Gives the output:

```
# time 'ab' 'bc' 'AB'
 0.000000E+00 9 25 15
```

**Comment by pirbo** [comment]
I tried to improve it. Reopen if it is still problematic
