### ISSUE TITLE
Build the concrete syntax tree of models

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#83]
I would like to have the original string with algebraic expressions ? 
Can it be included as an additional field in the type Term.with_pos ?

**Comment by pirbo** [comment]
Sorry this is probably at least the second time I ask but "What would you use it for?"

This is either expensive in memory (if you dissociate a string from its subpart) or extremely dangerous (someone will end editing a string forgetting that he is in fact touching a all hierarchy of strings!)

I consider less dangerous to "re"query a substring of the model when necessary (using the knowledge of the beginning and ending positions) than providing it systematically.

**Comment by feret** [comment]
OK if I can requerying a substring in a model and get exactly the same I am happy. 
I am not sure I can do this, but you will explain me in Boston.

What I want is to be sure that no information is lost (as rounding of non floating point numbers, or comments in the models), so that I can create either an annotated version of initial code, or a clickable version of the initial code.

**Comment by feret** [comment]
Also, it is important to identify which string will be often requested and memorize them. 

For instance, the commit: e4c9ca959be3a7cb5ede96dc3815667f7ba37b2d
Optimization. Strings are costly. We should avoid recomputing them as… …
feret committed 10 days ago
… much as possible.
 
has drastically improved the scalability of the computation of the canonic form of dags, by avoiding the rebuilding the labels of the nodes. 

It would be I think more appropriate to do it in the frontend, and make the string for rules/observables/variables available once for all.

**Comment by pirbo** [comment]
The new parser does not drop any single char of the input file. `Ast` does still and ,as it reorganises sentences, solving that would mean solving the question of commentary ownership:
in
```
foo
/* something */
bar
``` 
is `something` the comment of `foo` or of `bar`?

In
```
%var: 'x' 3 + 2 //g-1
``
does `g-1` comments `2` or `3 + 2` or the all line?

That's where I leave the ship :-)

**Comment by feret** [comment]
Excellent. 
Thank you very much. 


Envoyé de mon iPad

**Comment by hmedina** [comment]
Personally, I would think of the model as a tree, rooted at the filename,
where every line is a node, and comments belong to what they're bound: the
file or the line.

Thus for your examples:
```
foo
/* something */
bar
```
The comment is neither owned by foo nor by bar, but by the model / file.

```
%var: 'x' 3 + 2 //g-1
```
The comment is owned by that variable declaration.

```
%var: 'x' 3 + /*tricky comment*/ 2
```
Same as above, owned by the variable declaration.

Another perspective would be "a rule ends when the next rule starts". Under
that, the foo-something-bar comment would be owned by foo.

Those are my 2 cents.
HF

**Comment by feret** [comment]
I would put the comments that are not at the same line of another syntactic token as independent units. 


Cheers. 
Jérôme.
-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr
