### ISSUE TITLE
Some binaries operator are infix, others are prefix. Please fix the manuel. 

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#92]
Min and Max are prefix operators, whereas there are described as infix one in the manual.

**Comment by vd1** [comment]
Il y a un truc qui cloche a la fin du manuel - dans la legende de la figure
6.4:

"Note that observable C(x1 ̃u?,x2 ̃u?) is not activated by any other rule.
This implies that its number of occurrences does not change during a
simulation. "

mais cette observable change bcp pendant la simulation!

Sinon on n'a plus acces a la contact dans l'implementation presente?

V.

**Comment by feret** [comment]
1) Il y a des influences négatives, donc ce nombre peut décroître au cours du temps.
2)La carte de contact et la carte d'influence sont calculées par KaSa: 
Exécuter: 
   KaSa abc.ka 
pour avoir les fichiers influence.dot et contact.dot

**Comment by vd1** [comment]
2015-01-03 4:52 GMT-05:00 Jérôme Feret <notifications@github.com>:

> Exécuter:
> KaSa abc.ka
> pour avoir les fichiers influence.dot et contact.dot
>
>
super - merci
vous comptez ajouter ca au manuel dans un futur proche?
V.

**Comment by feret** [comment]
Oui ça va venir...

**Comment by pirbo** [comment]
I think we are clearer now. Reopen if you disapprove
