### ISSUE TITLE
adding tokens (perturbations)

### ISSUE THREAD

**Issue by vd1** [Kappa-Dev/KaSim#93]
I would like to be able to add tokens in perturbations:

```
  %token: a
  %mod: [T]=10 do $ADD 100 a
```

but I get:

```
$ ks --compile -i tmp
Parsing tmp...
Error (tmp) line 2, character 28: Malformed agent 'a'
```

PS: even if the alternative works (i have not checked)

```
%mod: [T] = 0.1 do a <-  |a| + 100
```

i think there is no conceptual distinction between adding a token and a bunch of agents - so perhaps there should be no syntactic one either

**Comment by feret** [comment]
Indeed, token should be dealt with fully transparently. 
What I mean is that there should be no syntax for token at all, there should be discovered dynamically, as small patterns with a lot of instances, and handled differently has the main site graph by the simulator.

**Comment by pirbo** [comment]
There is no syntax `a <-  |a| + 100` anymore. You now modify the amount of tokens as you add/remove agents in a modification: by applying a rule. 
Your example becomes `%mod: [T]=10 do $APPLY -> | 100 a` 
So I think this issue is closed. Reopen if you disagree...
