### ISSUE TITLE
Consistency in the Influence map

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#98]
The influence map includes both rules and observables. For rules, it displays the label. For observables, it displays the definition. It would be useful to produce a map that used labels for both, or definitions for both. As an added feature, the definition could be displayed in kappa, or in graphical "potato diagram" .dot, as can be requested of snapshots. For example, these could be the settings:

`"dumpInfluenceMap" {"false","true"}` [if true, defaults to using labels globally]
`"useDefinitionsInMaps" {"false","true}` [if true, defaults to printing kappa definitions globally]
`"useDotDefinitionsInMaps" {"false","true","both"}` [if true, prints potato diagrams; if both, prints two maps, one in kappa the other with potatoes]

**Comment by feret** [comment]
Dear Hector, 

You should use KaSa influence map instead:
  ./KaSa essai.ka 

There is currently no option to tune between using labels or definition. 
The label is always used if available, otherwise the definition is used. 

Best wishes. 
Jerome.

**Comment by feret** [comment]
Dear Hector, 

Are you happy with the current solution ? 
 1) Display the label if available, 
 2) If not, display the text kappa definition. 

I do not think that showing a graphical description of the rule inside a node of an influence map is reasonable. Firstly, we do not know how to draw a site graph (snapshots are quite ugly, thus image what we would get if we put a snapshot of the rule in each node of the influence map, and even if we were knowing how to do that, I do not think it would be readable. 

If you really want a command line option to toggle between label and text definition in node I can add it. 

Cheers. 
Jerome.

**Comment by hmedina** [comment]
Hi Jérôme! Yes, I'm happy with that usage.
