### ISSUE TITLE
Run time error with svg output on OCaml 4.01

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#99]
I have a strange runtime error on one of my laptop.
 -> Ubuntu 14.04 LTS
 -> Ocaml 4.01 (installer par apt-get)

KaSim/models/test_suite/cflows/weak_only$ rm output/data.svg 

                                                                       sh README > LOG 2> LOG2
LOG2:

***Runtime error Format.fprintf: bad format '@[<!DOCTYPE@ svg@ PUBLIC@ "-//W3C//DTD SVG 1.1//EN"@ ', giving up at character number 3 (!).***

LOG:
+ Command line is: 'KaSim' '-i' 'weak_only.ka' '-seed' '924556145' '-e' '100000' '-d' 'output' '-o' 'data.svg' '-p' '50'
Parsing weak_only.ka...
done
+ Initialized random number generator with seed 924556145
+ Compiling...
         -simulation parameters
         -agent signatures
         -variable declarations
         -initial conditions
         -rules
         -observables
         -perturbations
         Done
+ Analyzing non local patterns...
+ Building initial simulation state...
         -Counting initial local patterns...
         Done
____________________________________________________________
############################################################

Everything works fine on my other computers, but I use OCaml 4.02 on them.

**Comment by pirbo** [comment]
fixed by c4ef89b2245b86402a68fec54e49a09c8b9bce9d
